import type { GlossaryTerm } from './types'

/**
 * The glossary. Written to the same rule as the rest of the course: define the
 * term before it is used, and define it in language a beginner can hold rather
 * than language that is technically airtight and useless.
 *
 * `short` is what appears in the searchable list. `full` is what appears when
 * a term is opened, and it usually contains the thing that actually confuses
 * people about the term rather than a restatement of the definition.
 */
export const GLOSSARY: GlossaryTerm[] = [
  { term: 'Algorithm', seenIn: ['m01', 'm03'],
    short: 'A fixed set of steps that turns an input into an output.',
    full: 'Think of an algorithm as a recipe: a series of steps that always gives the same result for the same input. Sorting a list is an algorithm. This matters for AI in a specific way — the training process is an algorithm, but the trained model itself is a huge set of numbers, not a set of steps you can read line by line. When someone says "the algorithm decided this", they usually mean the model, not a readable procedure. That difference matters when someone asks you to explain a decision.' },
  { term: 'Agent', seenIn: ['m09'],
    short: 'A model connected to a loop, so it can act, see what happens, and act again.',
    full: 'An agent is not a smarter model — it is a model with consequences. An agent can call tools, read what comes back, and decide what to do next. Every weakness of the underlying model is still there. The difference is that now a mistake might send an email instead of just printing a wrong sentence. The key design question is always: which of its actions can be undone?' },
  { term: 'Alignment', seenIn: ['m10'],
    short: 'The problem of getting a system to do what you actually meant, not just what you said.',
    full: 'This is not about machines turning hostile. It is about how hard it is to state a goal clearly enough that a powerful system cannot follow the exact words while missing the point. Example: pay people for every rat tail they bring you, and some people will start farming rats instead of catching wild ones. Some version of this problem shows up in every AI system in use today.' },
  { term: 'Attention', seenIn: ['m08'],
    short: 'The part of a model that lets every word update its meaning using every other word.',
    full: 'For each word in a sentence, the model works out how relevant every other word is, and blends their meanings together based on that. This is how a model knows that "bank" means a riverbank in "the bank was steep", not a place that holds money. The everyday meaning of "paying attention" is only a loose comparison here, and it can mislead as often as it helps.' },
  { term: 'Backpropagation', seenIn: ['m06'],
    short: 'The method used to work out how to adjust every number inside a network.',
    full: 'After a model makes an error, backpropagation works backwards from that error to figure out how much each individual number (weight) contributed to it. Without this method, you would have to test billions of numbers one at a time, and training would be far too slow to be possible. People described how to do this in 1986, but it only became usable at large scale once GPUs arrived.' },
  { term: 'Benchmark', seenIn: ['m05', 'm07'],
    short: 'A shared test that everyone reports scores against.',
    full: 'Benchmarks are useful for comparing systems, but risky if you treat them as the whole story. Over time, a field tends to get very good at its own tests without necessarily getting better at everything else. For language models there is an extra problem: the test questions may already have been part of what the model was trained on, so a high score does not always mean real understanding. Always ask whether the test material was kept separate from the training data.' },
  { term: 'Bias', seenIn: ['m10'],
    short: 'A consistent, unfair pattern in what a model does, usually coming from its data.',
    full: 'Bias can enter at five points: how the problem was framed, who is included in the data, how the data was labelled, what the model was told to aim for, and how the output is later used. Most public arguments about "biased AI" are really arguments about different points on this list, which is why they talk past each other. Removing an obvious field like race or gender from the data rarely fixes this, because other pieces of information can still point to the same thing.' },
  { term: 'Compute', seenIn: ['m06', 'm07'],
    short: 'The amount of computer processing power used to train or run a model.',
    full: 'Compute is often called the currency of modern AI. Training the biggest, most capable models uses enormous amounts of it, which is one reason only a small number of large organisations can build them. In most cases, how much computing power a team has access to limits what they can build more than how good their ideas are.' },
  { term: 'Context window', seenIn: ['m08'],
    short: 'How much text a model can look at and use at one time.',
    full: 'This is measured in tokens, which are small chunks of text. Anything outside this window does not exist for the model — it is not that the model forgot it, it simply never saw it. A longer window helps, but models are not perfect at using everything inside a very long context. So text "fitting" inside the window is not the same as the model actually using it well.' },
  { term: 'Dataset', seenIn: ['m05'],
    short: 'The collection of examples used to train a model.',
    full: 'A dataset does not occur naturally. Someone chose what to collect, where to collect it from, over what period of time, and how to describe it — and the model absorbs every one of those choices invisibly. Saying "the algorithm is neutral, it just learns from data" is not a real defence, because the data itself already carries all these choices and assumptions.' },
  { term: 'Deep learning', seenIn: ['m01', 'm06'],
    short: 'Machine learning that uses neural networks with many layers.',
    full: 'Deep learning is one part of machine learning, not another name for the same thing. "Deep" simply means the network has several hidden layers stacked on top of each other. It became the dominant approach after 2012 — not because one brand-new idea appeared, but because enough data, powerful graphics chips (GPUs), and a decade of small practical fixes all came together at the same time.' },
  { term: 'Diffusion model', seenIn: ['m09'],
    short: 'An image generator that works by slowly removing noise from a random image.',
    full: 'During training, the model is shown real images with random noise added to them, and it learns to undo that noise one step at a time. To create a new image, the process starts from pure random noise and cleans it up step by step, guided by a text prompt. Nothing is copied or blended from existing images — this is also why the same prompt gives a different image every time, since the starting noise is different each time.' },
  { term: 'Embedding', seenIn: ['m08'],
    short: 'A piece of data turned into a set of numbers, treated as a position in space.',
    full: 'During training, the model learns to place things that are used in similar ways close together in this space. This is what people mean when they say a model "represents meaning": meaning becomes a location, and similarity becomes distance between two locations. This is also how search works inside a retrieval system — it finds documents whose position is close to the position of your question.' },
  { term: 'Expert system', seenIn: ['m03'],
    short: 'A program that follows hand-written IF-THEN rules written by a human expert.',
    full: 'Expert systems were AI\'s first commercial success, in the 1980s. They work very well inside the rules they were given, but fail badly — and confidently — the moment a case falls just outside those rules, because the system has no way of knowing where its own knowledge ends. They eventually fell out of favour mainly because of the cost and effort of writing and maintaining all those rules, not because they gave wrong answers.' },
  { term: 'Fine-tuning', seenIn: ['m08'],
    short: 'Training an already-built model further, on a smaller, more specific set of examples.',
    full: 'Fine-tuning costs far less than training a model from scratch. It is better at changing how a model behaves than at teaching it completely new facts. If you need a model to know information from your own documents, a retrieval system (see RAG) is usually the better tool. If you need the model to respond in a particular tone or format, fine-tuning is usually the better tool.' },
  { term: 'Foundation model', seenIn: ['m08'],
    short: 'A large model trained broadly, then adapted for many different uses.',
    full: 'The name comes from a 2021 Stanford research paper, and it points to something important: when many products are built on top of one foundation model, they all inherit its strengths, its limits, and its mistakes together. If there is a flaw in the foundation model, it can show up in every product built on it, all at once.' },
  { term: 'Generative AI', seenIn: ['m01', 'm09'],
    short: 'Models that create new content, instead of giving a label or a number.',
    full: 'This is the smallest of the four nested circles — AI, machine learning, deep learning, and generative AI — and it is what most people actually mean when they say "AI". It covers generating text, images, audio and video. It is a type of deep learning, which is a type of machine learning, which is a type of AI.' },
  { term: 'GPU', seenIn: ['m06', 'm07'],
    short: 'A chip built for graphics that also turns out to be ideal for training AI models.',
    full: 'Both graphics rendering and neural network training need huge numbers of simple calculations done at the same time. GPUs are built to do exactly that: thousands of small calculations in parallel. This coincidence is one of the main reasons deep learning became practical when it did, rather than a decade earlier or later.' },
  { term: 'Hallucination', seenIn: ['m10'],
    short: 'Confident, well-written output from a model that is simply not true.',
    full: 'This is not a great name for the problem, because it suggests something is broken — but nothing is actually malfunctioning. A made-up citation is, in a strange sense, a very good prediction: right shape, right style, right-looking year. The only thing missing is that it does not actually exist, and the model was never specifically trained to check for that. This is a built-in limitation of how these models work, not a bug that can simply be patched.' },
  { term: 'Inference', seenIn: ['m08'],
    short: 'Running an already-trained model to produce an output.',
    full: 'This is different from training. Each single use is cheap compared with training the model in the first place, but because it happens millions of times, inference ends up being the bigger overall cost once a model is in wide use. When people talk about "the cost of AI", they usually mean one of these two costs — training or inference — often without saying which one.' },
  { term: 'Machine learning', seenIn: ['m01', 'm05'],
    short: 'Systems that improve at a task by learning from data, instead of following fixed rules.',
    full: 'Machine learning is one part of AI, and it covers much more than neural networks — decision trees and simple statistical methods, like linear regression, are machine learning too. The key idea is that a human supplies examples instead of writing out step-by-step reasoning. This idea is what got the field moving again after it got stuck in the 1980s, when writing rules by hand for every possible situation had become too slow and too hard.' },
  { term: 'Multimodal', seenIn: ['m09'],
    short: 'A model that can take in more than one kind of input, such as text and images together.',
    full: 'Every kind of input — text, images and so on — gets converted into tokens that live in the same shared space, so the model\'s attention mechanism can work across all of them without needing to know which type each one is. This means the model can handle several kinds of input at once. It does not mean the model has one single, unified understanding of the world.' },
  { term: 'Neural network', seenIn: ['m06'],
    short: 'A system built from many adjustable numbers, arranged in layers.',
    full: 'Ignore the comparison to the human brain — these are not realistic models of biological neurons. Numbers go in, get multiplied and added together, pass through several layers, and different numbers come out the other end. "Training" means adjusting all of those numbers, again and again, until the outputs match what you wanted.' },
  { term: 'Open-weight model', seenIn: ['m10'],
    short: 'A model whose trained numbers (weights) are published for anyone to download and run.',
    full: 'This is different from "open-source". The weights may be published under a licence with restrictions, and the training data and code are usually not shared at all. It matters in practice because you can run an open-weight model on your own computer — which means nothing you send it has to leave your control.' },
  { term: 'Overfitting', seenIn: ['m05'],
    short: 'When a model learns the training examples so closely that it also learns their noise.',
    full: 'Picture a student who has memorised last year\'s exam paper instead of understanding the subject. The way to guard against this is to test the model on data it has never seen before, and to report that score — not the score on the data it was trained on. A model that is only ever tested on its own training data is not really telling you anything useful.' },
  { term: 'Parameter', seenIn: ['m06', 'm08'],
    short: 'One of the adjustable numbers inside a model, set during training.',
    full: 'This is what a phrase like "70 billion parameters" is counting. More parameters usually means the model can represent more complexity, but the number is a weak guide to how useful the model actually is — the design, the quality of the data, and how it was trained all matter just as much. Treat a parameter count the way you would treat the engine size of a car: a real number worth knowing, but not the whole story.' },
  { term: 'Pretraining', seenIn: ['m08'],
    short: 'The first and biggest stage of training: predicting the next word across huge amounts of text.',
    full: 'This is where almost all of a model\'s knowledge and language ability comes from, and it uses the large majority of the total computing cost. Pretraining has a cut-off date — after that date, the model knows nothing new unless someone tells it directly or gives it a tool to search for it.' },
  { term: 'Prompt injection', seenIn: ['m10'],
    short: 'Hiding instructions inside content a model reads, so the model follows them.',
    full: 'This is a real, current security risk for anyone building AI agents. A model that reads a webpage or a document cannot always tell the difference between "content to read" and "instructions to obey". If your agent reads content from outside sources and can also take actions, this is exactly the risk you need to design against.' },
  { term: 'RAG (retrieval-augmented generation)', seenIn: ['m09'],
    short: 'Finding relevant passages and adding them to the prompt before the model answers.',
    full: 'This is the standard fix for a model that does not know your own documents. It greatly reduces made-up answers on questions the documents actually cover. It does not remove the risk completely — even when given the right passages, a model can still misread them, or add convincing-sounding details that are not actually in any of them.' },
  { term: 'Reinforcement learning', seenIn: ['m05', 'm07'],
    short: 'Learning from rewards and penalties, instead of from labelled examples.',
    full: 'The system tries something, gets a score for how well it did, and adjusts based on that score. This works very well where attempts are cheap and can be repeated many times, such as in games or simulations. It is much harder to use in the real, physical world, where a failed attempt can break something and you cannot simply try millions of times.' },
  { term: 'RLHF', seenIn: ['m08'],
    short: 'Adjusting a model based on which of two responses people prefer.',
    full: 'Here is how it works: people are shown two responses and asked which one is better; a separate model is trained to predict those preferences; then the main model is adjusted so it scores well by that measure. This is where a model\'s tone, its habit of hedging, and its refusals come from. In other words, a model\'s manner is a decision made by the company that built it, not a natural property of the technology itself.' },
  { term: 'Scaling laws', seenIn: ['m07'],
    short: 'The pattern that performance improves in a predictable way as data, compute and parameters increase.',
    full: 'This pattern has been well tested within the range that has actually been measured, and it is a big reason the AI industry has focused so heavily on raising money and buying computing power, not just on finding new ideas. Whether the pattern keeps holding beyond what has already been tested is a guess about the future, and serious researchers disagree about it in public. Confident claims either way — that it definitely will, or definitely will not, continue — are opinions, not proven facts.' },
  { term: 'Self-supervised learning', seenIn: ['m05', 'm08'],
    short: 'Creating the training signal from the data itself, with no human labelling needed.',
    full: 'The method: hide part of the input, then have the model guess the hidden part. The hidden part becomes the "correct answer", produced automatically at no extra cost. This is what made it possible to train models on far more text than any team of humans could ever have labelled by hand, and it is the reason large language models exist at all.' },
  { term: 'Supervised learning', seenIn: ['m05'],
    short: 'Learning from examples that already come with the correct answer attached.',
    full: 'This is the most common type of machine learning used in real products today. Its biggest cost is producing the labels — the correct answers — in the first place. Because of that, the important question to ask about any supervised learning system is: who labelled the data, and by what standard did they decide what counted as correct?' },
  { term: 'Symbolic AI', seenIn: ['m03'],
    short: 'AI built from explicit, readable rules and symbols, rather than learned from data.',
    full: 'This approach was dominant for the field\'s first thirty years, and it is still the right choice when a rule is simply decided by people rather than discovered from data, when you need to be able to explain a decision clearly, or when you do not have enough data to learn from. Most systems used in practice today combine symbolic AI with learned components, rather than relying on only one.' },
  { term: 'Token', seenIn: ['m08'],
    short: 'The small chunk of text a model actually works with — roughly a word or part of a word.',
    full: 'Common words are usually a single token; rarer or longer words get split into smaller pieces. This is part of why models can be strangely bad at tasks like counting the letters in a word — they never actually see individual letters, only tokens. Tokens are also the unit you are billed for when using these models, and the unit that context windows are measured in.' },
  { term: 'Training', seenIn: ['m05', 'm06'],
    short: 'Adjusting a model\'s numbers so its outputs get closer to what you want.',
    full: 'The process: show the model an example, measure how wrong its output was, nudge every number slightly in the direction that reduces that error, and repeat this billions of times. At no point does the model "understand" anything in a human sense — it is closer to slowly moving downhill, step by step, inside a space with billions of dimensions.' },
  { term: 'Transformer', seenIn: ['m08'],
    short: 'The 2017 model design that almost every current large AI model is built on.',
    full: 'Its key idea was to stop reading text one word at a time in order, and instead work out directly how much every word matters to every other word, all at once. This made training much easier to speed up using many processors working together — which mattered enormously once the field realised that simply scaling up was one of the most powerful ways to improve performance.' },
  { term: 'Turing test', seenIn: ['m02'],
    short: 'Turing\'s 1950 idea: can a judge tell a machine from a human just by chatting with both?',
    full: 'This test is often wrongly described as a definition of intelligence. Turing deliberately avoided trying to define "thinking" — instead, he replaced a question that could never be answered with a question that could actually be tested. So if you hear a claim that a system "passed the Turing test", treat it as a claim about how that specific test was run. Ask how long the judges had to decide, and how experienced they were.' }
]
