import type { GlossaryTerm } from './types'

/**
 * The glossary. Written to the same rule as the rest of the course: define the
 * term before it is used, and define it in language a beginner can hold rather
 * than language that is technically airtight and useless.
 *
 * `short` is what appears in the searchable list. `full` is what appears when
 * a term is opened, and it usually contains the thing that actually confuses
 * people about the term rather than a restatement of the definition.
 */
export const GLOSSARY: GlossaryTerm[] = [
  { term: 'Algorithm', seenIn: ['m01', 'm03'],
    short: 'A fixed procedure for getting from an input to an output.',
    full: 'A recipe: a sequence of steps that always does the same thing given the same input. Sorting a list is an algorithm. Note what this means for AI — the *training* procedure is an algorithm, but the trained model is a large set of numbers, not a readable procedure. Talking about "the algorithm" deciding something is usually talking about the model, and the difference matters when someone asks you to explain a decision.' },
  { term: 'Agent', seenIn: ['m09'],
    short: 'A model wired into a loop so it can take actions, see results and continue.',
    full: 'The addition is not intelligence but consequence. An agent can call tools, read what comes back, and decide the next step. Every failure mode of the underlying model still applies — but now a mistake sends an email rather than printing a sentence. The design question is always which actions are reversible.' },
  { term: 'Alignment', seenIn: ['m10'],
    short: 'The problem of getting a system to pursue what you actually intended.',
    full: 'Not a question of machines becoming hostile. It is the difficulty of specifying a goal precisely enough that a capable optimiser cannot satisfy the letter of it while defeating the point. Pay per rat tail, get rat farms. Present in every deployed system today.' },
  { term: 'Attention', seenIn: ['m08'],
    short: 'The mechanism by which each token\'s meaning is updated by every other token.',
    full: 'For each position in a sequence, the model computes how relevant every other position is, and blends their representations accordingly. This is what lets "bank" mean the right thing in "the bank was steep". The everyday sense of paying attention is a loose metaphor and misleads as often as it helps.' },
  { term: 'Backpropagation', seenIn: ['m06'],
    short: 'The efficient method for working out how to adjust every weight in a network.',
    full: 'Given how wrong the output was, backpropagation computes — working backwards from the output — how much each individual weight contributed to the error. Without it you would have to test billions of weights one at a time and training would be impossible. Described in usable form in 1986; unusable at scale until GPUs arrived.' },
  { term: 'Benchmark', seenIn: ['m05', 'm07'],
    short: 'A shared test set everyone reports scores against.',
    full: 'Useful for comparison and dangerous as a summary. Over time a field collectively overfits its benchmarks, and for language models there is the extra problem of contamination — the test may have been in the training data. Always ask whether the evaluation was on genuinely held-out material.' },
  { term: 'Bias', seenIn: ['m10'],
    short: 'Systematic skew in a model\'s behaviour, usually inherited from its data.',
    full: 'Enters at five points: how the problem was framed, who is in the data, how it was labelled, what the model optimised, and how the output is used. Most public arguments about biased AI are about different entry points, which is why they go nowhere. Removing a demographic field rarely helps — other features correlate with it.' },
  { term: 'Compute', seenIn: ['m06', 'm07'],
    short: 'The quantity of arithmetic used to train or run a model.',
    full: 'The currency of modern AI. Frontier training runs consume enormous amounts, which is why capability concentrates in organisations that can afford it. Usually the binding constraint on what is possible, more than ideas are.' },
  { term: 'Context window', seenIn: ['m08'],
    short: 'How much text a model can consider at once.',
    full: 'Measured in tokens. Everything outside it does not exist as far as the model is concerned — it is not forgotten, it was never there. Long windows help, and attention over very long contexts is imperfect, so "it fits" is not the same as "it was used well".' },
  { term: 'Dataset', seenIn: ['m05'],
    short: 'The collection of examples a model was fitted to.',
    full: 'Not a natural object. Somebody chose what to collect, from where, over what period, and how to describe it, and the model inherits every one of those choices invisibly. "The algorithm is neutral, it learns from data" is not a defence — the data is the argument.' },
  { term: 'Deep learning', seenIn: ['m01', 'm06'],
    short: 'Machine learning using neural networks with many layers.',
    full: 'A subset of machine learning, not a synonym. "Deep" simply means several hidden layers. It took over the field from 2012 because data, GPUs and a decade of practical fixes arrived together — not because a new core idea appeared.' },
  { term: 'Diffusion model', seenIn: ['m09'],
    short: 'An image generator that works by repeatedly removing noise.',
    full: 'Trained by adding noise to real images and learning to undo one step. To generate, start from pure random noise and denoise repeatedly, steered by a text prompt. Nothing is retrieved or blended, which is why the same prompt gives different images each time — the starting noise differs.' },
  { term: 'Embedding', seenIn: ['m08'],
    short: 'A piece of data represented as coordinates in a high-dimensional space.',
    full: 'Positions are learned so that things used similarly end up near each other. This is what people mean by a model "representing meaning": meaning is a location and similarity is distance. It is also how search over documents works in a retrieval system.' },
  { term: 'Expert system', seenIn: ['m03'],
    short: 'A program that applies hand-written IF–THEN rules from a human specialist.',
    full: 'AI\'s first commercial success, in the 1980s. Excellent inside its rules, and it fails confidently one step outside them because it has no representation of its own boundary. Killed by the knowledge bottleneck and by maintenance cost, not by inaccuracy.' },
  { term: 'Fine-tuning', seenIn: ['m08'],
    short: 'Further training of an existing model on a narrower set of examples.',
    full: 'Cheaper than training from scratch by orders of magnitude, and it changes behaviour more readily than it adds knowledge. If you need a model to know your documents, retrieval is usually the better tool; if you need it to respond in a particular way, fine-tuning is.' },
  { term: 'Foundation model', seenIn: ['m08'],
    short: 'A large model trained broadly and then adapted to many downstream uses.',
    full: 'The term comes from a 2021 Stanford paper. The point of the name is the dependency it describes: when many systems are built on one model, they inherit its properties — capabilities, limitations and failure modes alike — and a flaw upstream propagates everywhere at once.' },
  { term: 'Generative AI', seenIn: ['m01', 'm09'],
    short: 'Models whose output is new content rather than a label or a number.',
    full: 'The smallest of the four nested circles and the one most people mean by "AI". Text, images, audio, video. A subset of deep learning, which is a subset of machine learning, which is a subset of AI.' },
  { term: 'GPU', seenIn: ['m06', 'm07'],
    short: 'A processor built for graphics that happens to be ideal for training networks.',
    full: 'Graphics and neural networks both need enormous numbers of simple parallel multiplications. GPUs do thousands at once. This coincidence is one of the main reasons deep learning became practical when it did rather than a decade earlier or later.' },
  { term: 'Hallucination', seenIn: ['m10'],
    short: 'Confident, well-formed output that is simply not true.',
    full: 'A poor name — it implies malfunction, and nothing is malfunctioning. A fabricated citation is an excellent next-token prediction: right shape, right style, right year. The only missing property is existence, which the training objective never mentioned. Structural, not a bug.' },
  { term: 'Inference', seenIn: ['m08'],
    short: 'Running a trained model to produce an output.',
    full: 'As opposed to training. Cheap per use compared with training, and the dominant cost at scale because it happens millions of times. When people discuss the cost of AI they are usually discussing one of these two and rarely say which.' },
  { term: 'Machine learning', seenIn: ['m01', 'm05'],
    short: 'Systems that improve at a task by being shown data rather than given rules.',
    full: 'A subset of AI, and much wider than neural networks — decision trees and linear regression are machine learning too. The defining move is that a human supplies examples rather than reasoning, which dissolved the knowledge bottleneck that stalled the field in the 1980s.' },
  { term: 'Multimodal', seenIn: ['m09'],
    short: 'A model that accepts more than one kind of input, such as text and images.',
    full: 'Everything is converted into tokens in a shared representation space, so attention can work across them without caring which is which. It means the model handles several input types. It does not mean the model has a unified understanding of the world.' },
  { term: 'Neural network', seenIn: ['m06'],
    short: 'A function with very many adjustable numbers, arranged in layers.',
    full: 'Ignore the brain metaphor — these are not models of biological neurons in any serious sense. Numbers go in, get multiplied, added and squashed through layers, and numbers come out. Training means adjusting the numbers until the outputs are the ones you wanted.' },
  { term: 'Open-weight model', seenIn: ['m10'],
    short: 'A model whose trained parameters are published for anyone to download and run.',
    full: 'Distinct from open-source: the weights may be published under a licence with restrictions, and the training data and code usually are not. Matters practically because you can run it on your own hardware, so nothing you send it leaves your control.' },
  { term: 'Overfitting', seenIn: ['m05'],
    short: 'Fitting the training examples so closely that the model captures their noise.',
    full: 'The student who memorises last year\'s paper. The defence is to evaluate on data the model has never seen, and to report that number rather than the training one. A model evaluated only on its training data is reporting nothing at all.' },
  { term: 'Parameter', seenIn: ['m06', 'm08'],
    short: 'One of the adjustable numbers inside a model, set during training.',
    full: 'What "70 billion parameters" counts. More parameters generally means more capacity to represent complexity, and it is a weak predictor of usefulness — architecture, data quality and training all matter as much. Treat parameter counts the way you would treat engine size.' },
  { term: 'Pretraining', seenIn: ['m08'],
    short: 'The first and largest training stage: predict the next token across enormous text.',
    full: 'Where essentially all the knowledge and language ability comes from, and the overwhelming majority of the compute cost. It has a cut-off date, after which the model knows nothing new unless you tell it or give it a search tool.' },
  { term: 'Prompt injection', seenIn: ['m10'],
    short: 'Hiding instructions in content a model reads, so the model follows them.',
    full: 'The live security problem for anyone deploying agents. A model that reads a web page or a document cannot reliably distinguish "content to process" from "instructions to obey". If your agent reads untrusted input and can take actions, this is the thing to design against.' },
  { term: 'RAG (retrieval-augmented generation)', seenIn: ['m09'],
    short: 'Fetching relevant passages and putting them in the prompt before answering.',
    full: 'The standard fix for a model that does not know your documents. It substantially reduces invention on covered questions. It does not eliminate it — a model given the right passages can still misread them and still add plausible detail that is in none of them.' },
  { term: 'Reinforcement learning', seenIn: ['m05', 'm07'],
    short: 'Learning from rewards and penalties rather than from labelled examples.',
    full: 'The system acts, gets a score, and adjusts. Superb where attempts are cheap and repeatable — games, simulations. Much harder in the physical world, where a failed attempt breaks something and you cannot have millions of them.' },
  { term: 'RLHF', seenIn: ['m08'],
    short: 'Tuning a model against human preferences between pairs of responses.',
    full: 'Humans say which of two responses is better; a reward model is fitted to those judgements; the model is tuned to score well. This is where tone, hedging and refusal behaviour come from — which means a model\'s manner is a design decision made by a company, not a property of the technology.' },
  { term: 'Scaling laws', seenIn: ['m07'],
    short: 'The observation that performance improves predictably with more data, compute and parameters.',
    full: 'Well evidenced over the range measured, which is why the industry restructured around capital rather than ideas. Whether it continues beyond that range is an extrapolation that competent researchers publicly disagree about. Confident claims in either direction are positions, not findings.' },
  { term: 'Self-supervised learning', seenIn: ['m05', 'm08'],
    short: 'Generating the training signal from the data itself, with no human labelling.',
    full: 'Hide part of the input, predict it. The hidden part is the label, produced for free. This is what allowed training on quantities of text no labelling operation could ever have annotated, and it is the reason large language models exist.' },
  { term: 'Supervised learning', seenIn: ['m05'],
    short: 'Learning from examples that come with the right answer attached.',
    full: 'The workhorse: the large majority of deployed machine learning. Its cost is dominated by producing the labels, which is why the interesting question about any supervised system is who labelled the data and by what standard.' },
  { term: 'Symbolic AI', seenIn: ['m03'],
    short: 'AI built from explicit symbols and rules you can read.',
    full: 'Dominant for the field\'s first thirty years and still the right tool where the rule is stipulated rather than inferred, where you must justify a decision, or where you have no data. Most production systems today combine it with learned components rather than choosing.' },
  { term: 'Token', seenIn: ['m08'],
    short: 'The chunk of text a model actually processes — roughly a word or fragment.',
    full: 'Common words are one token, rarer ones split. This is why models can be oddly bad at counting letters: they do not see letters. It is also the unit you are billed in, and the unit context windows are measured in.' },
  { term: 'Training', seenIn: ['m05', 'm06'],
    short: 'Adjusting a model\'s parameters so its outputs match what you wanted.',
    full: 'Show an example, measure the error, nudge every parameter slightly in the direction that reduces it, repeat billions of times. There is no step at which the model understands anything — it is descent down a slope in a space of billions of dimensions.' },
  { term: 'Transformer', seenIn: ['m08'],
    short: 'The 2017 architecture underlying essentially every current large model.',
    full: 'Its move was to stop reading sequences one item at a time and instead compute directly how much every element matters to every other. That made training parallelisable, which mattered enormously in a field that had just discovered scale was the lever.' },
  { term: 'Turing test', seenIn: ['m02'],
    short: 'Turing\'s 1950 proposal: can a judge tell machine from human by conversation alone?',
    full: 'Often misdescribed as a definition of intelligence. Turing explicitly declined to define thinking; he substituted a measurable question for an unanswerable one. Any claim that a system "passed the Turing test" is a claim about a protocol — ask how long the judges had and how expert they were.' }
]
