/**
 * Word of the Day bank — uncommon-but-useful English vocabulary (~one year+).
 * Deterministic daily pick via local YYYY-MM-DD hash in useDailyWord.
 * Each entry includes a baked definition (API fallback) and a non-spoiler clue.
 */
export interface WotdEntry {
  word: string
  /** Part of speech label (noun, verb, adj, …). */
  pos: string
  definition: string
  example?: string
  /** Lateral hint for unscrambling — not the dictionary definition. */
  clue: string
}

export const WOTD_WORDS: readonly WotdEntry[] = Object.freeze([
  { word: "abate", pos: "verb", definition: "to become less intense or widespread", example: "The storm began to abate by midnight.", clue: "Storm or anger that cools off" },
  { word: "abjure", pos: "verb", definition: "to solemnly renounce a belief or claim", example: "She abjured the old doctrine.", clue: "Formal farewell to a belief" },
  { word: "abrogate", pos: "verb", definition: "to repeal or do away with formally", example: "Parliament abrogated the outdated law.", clue: "Officially cancel a law" },
  { word: "abstemious", pos: "adj", definition: "not self-indulgent, especially with food or drink", example: "His abstemious habits kept him sharp.", clue: "Restraint at the table" },
  { word: "acumen", pos: "noun", definition: "keen insight or judgment", example: "She has rare business acumen.", clue: "Sharp snap judgment" },
  { word: "admonish", pos: "verb", definition: "to warn or reprimand firmly", example: "The coach admonished the team gently.", clue: "Firm careful warning" },
  { word: "adroit", pos: "adj", definition: "clever or skillful", example: "An adroit negotiator closed the deal.", clue: "Skillful with hands or mind" },
  { word: "aegis", pos: "noun", definition: "protection or sponsorship", example: "Under the aegis of the foundation, the project thrived.", clue: "Shield of backing" },
  { word: "affable", pos: "adj", definition: "friendly and easy to talk to", example: "The host was warm and affable.", clue: "Easy to chat with" },
  { word: "alacrity", pos: "noun", definition: "brisk cheerful readiness", example: "She accepted with alacrity.", clue: "Eager speed to say yes" },
  { word: "ameliorate", pos: "verb", definition: "to make better", example: "Small changes can ameliorate stress.", clue: "Make a rough thing milder" },
  { word: "anachronism", pos: "noun", definition: "something belonging to another time", example: "The rotary phone felt like an anachronism.", clue: "Wrong decade for the scene" },
  { word: "anomaly", pos: "noun", definition: "something that deviates from the standard", example: "The reading was an anomaly.", clue: "Odd one out in the data" },
  { word: "antipathy", pos: "noun", definition: "a deep-seated dislike", example: "Quiet antipathy toward the plan.", clue: "Quiet lasting dislike" },
  { word: "aphorism", pos: "noun", definition: "a concise statement of a truth", example: "She collected aphorisms.", clue: "Tiny wisdom in one line" },
  { word: "apocryphal", pos: "adj", definition: "of doubtful authenticity though widely told", example: "The story is likely apocryphal.", clue: "Famous tale that may be fake" },
  { word: "approbation", pos: "noun", definition: "approval or praise", example: "Critical approbation.", clue: "Official nod of approval" },
  { word: "arbitrary", pos: "adj", definition: "based on random choice rather than reason", example: "The cutoff felt arbitrary.", clue: "Chosen without a clear why" },
  { word: "arcane", pos: "adj", definition: "understood by few; mysterious", example: "Arcane rules slowed the process.", clue: "Secret-club knowledge" },
  { word: "arduous", pos: "adj", definition: "involving hard persistent effort", example: "An arduous climb.", clue: "Hard long effort" },
  { word: "assiduous", pos: "adj", definition: "showing great care and perseverance", example: "Assiduous practice paid off.", clue: "Steady careful grind" },
  { word: "astute", pos: "adj", definition: "accurately assessing situations", example: "An astute observer.", clue: "Reads the room well" },
  { word: "atrophy", pos: "verb", definition: "to waste away from underuse", example: "Skills atrophy without practice.", clue: "Shrink from disuse" },
  { word: "audacious", pos: "adj", definition: "willing to take bold risks", example: "An audacious proposal.", clue: "Bold past the usual" },
  { word: "auspicious", pos: "adj", definition: "favorable; promising success", example: "An auspicious start.", clue: "Good-omen weather" },
  { word: "austere", pos: "adj", definition: "severe or stark in manner", example: "An austere room.", clue: "Bare and stern" },
  { word: "avarice", pos: "noun", definition: "extreme greed for wealth", example: "Avarice clouded judgment.", clue: "Greed with sharp teeth" },
  { word: "avid", pos: "adj", definition: "having keen interest", example: "An avid reader.", clue: "Keenly into it" },
  { word: "banal", pos: "adj", definition: "so unoriginal as to be boring", example: "A banal slogan.", clue: "Been-there phrase" },
  { word: "beleaguer", pos: "verb", definition: "to trouble or harass continuously", example: "Critics beleaguered the campaign.", clue: "Surrounded by hassle" },
  { word: "bellicose", pos: "adj", definition: "aggressive; ready to fight", example: "A bellicose tone.", clue: "Ready to spar" },
  { word: "benign", pos: "adj", definition: "gentle; not harmful", example: "A benign smile.", clue: "Kind, not dangerous" },
  { word: "bequeath", pos: "verb", definition: "to leave to someone in a will", example: "She bequeathed her library.", clue: "Pass on in a will" },
  { word: "blithe", pos: "adj", definition: "cheerfully carefree", example: "A blithe remark.", clue: "Carefree, maybe too much" },
  { word: "boon", pos: "noun", definition: "a helpful benefit", example: "Quiet hours were a boon.", clue: "A welcome gift" },
  { word: "brevity", pos: "noun", definition: "concise use of words", example: "Brevity made the note land.", clue: "Short and sharp" },
  { word: "bucolic", pos: "adj", definition: "pleasantly rural", example: "A bucolic weekend.", clue: "Pastoral countryside vibe" },
  { word: "cajole", pos: "verb", definition: "to persuade by coaxing", example: "He cajoled the team.", clue: "Sweet-talk into yes" },
  { word: "candor", pos: "noun", definition: "open honesty", example: "Her candor was refreshing.", clue: "Straight talk, kindly" },
  { word: "capitulate", pos: "verb", definition: "to surrender; cease resisting", example: "They refused to capitulate.", clue: "Wave the white flag" },
  { word: "capricious", pos: "adj", definition: "given to sudden changes", example: "A capricious schedule.", clue: "Mood swings of fate" },
  { word: "catharsis", pos: "noun", definition: "release of strong emotions", example: "Writing offered catharsis.", clue: "Emotional release valve" },
  { word: "caustic", pos: "adj", definition: "scathingly sarcastic", example: "A caustic joke.", clue: "Burning sarcasm" },
  { word: "caveat", pos: "noun", definition: "a warning or proviso", example: "One caveat: results vary.", clue: "Small warning label" },
  { word: "chicanery", pos: "noun", definition: "trickery to achieve a purpose", example: "The deal smelled of chicanery.", clue: "Sly fine-print tricks" },
  { word: "circumspect", pos: "adj", definition: "wary; unwilling to take risks", example: "Be circumspect with claims.", clue: "Look before you leap" },
  { word: "clairvoyant", pos: "adj", definition: "supposedly able to see beyond senses", example: "Clairvoyant about deadlines.", clue: "Sees around corners" },
  { word: "clemency", pos: "noun", definition: "mercy; lenience", example: "The judge showed clemency.", clue: "Mercy from the bench" },
  { word: "cogent", pos: "adj", definition: "clear, logical, convincing", example: "A cogent argument.", clue: "Argument that sticks" },
  { word: "cognizant", pos: "adj", definition: "aware; having knowledge", example: "Stay cognizant of trade-offs.", clue: "Aware and on it" },
  { word: "commensurate", pos: "adj", definition: "corresponding in size or degree", example: "Pay commensurate with skill.", clue: "Matching in size" },
  { word: "complacent", pos: "adj", definition: "smugly self-satisfied", example: "Success made them complacent.", clue: "Too cozy with success" },
  { word: "conciliate", pos: "verb", definition: "to stop someone being angry", example: "A quiet apology helped conciliate.", clue: "Soften anger" },
  { word: "concomitant", pos: "adj", definition: "naturally accompanying", example: "Growth brought concomitant costs.", clue: "Comes along with" },
  { word: "confluence", pos: "noun", definition: "a flowing together; meeting", example: "A confluence of ideas.", clue: "Rivers or ideas meet" },
  { word: "conjecture", pos: "noun", definition: "an opinion on incomplete info", example: "Pure conjecture.", clue: "Educated guess only" },
  { word: "connive", pos: "verb", definition: "to secretly allow wrongdoing", example: "Do not connive at abuse.", clue: "Quietly look away" },
  { word: "consign", pos: "verb", definition: "to deliver into someone's care", example: "Consigned the draft to an editor.", clue: "Hand over for keeping" },
  { word: "consternation", pos: "noun", definition: "anxiety or dismay", example: "News caused consternation.", clue: "Sudden dismay" },
  { word: "contiguous", pos: "adj", definition: "sharing a common border", example: "Contiguous rooms.", clue: "Touching edges" },
  { word: "contrite", pos: "adj", definition: "feeling remorse", example: "A contrite note.", clue: "Sorry and meaning it" },
  { word: "conundrum", pos: "noun", definition: "a confusing difficult problem", example: "Hiring became a conundrum.", clue: "Puzzle with no easy door" },
  { word: "convivial", pos: "adj", definition: "friendly and lively", example: "A convivial dinner.", clue: "Lively good company" },
  { word: "copious", pos: "adj", definition: "abundant", example: "Copious notes.", clue: "Lots and lots" },
  { word: "corroborate", pos: "verb", definition: "to confirm with evidence", example: "Data corroborated the hunch.", clue: "Back up with evidence" },
  { word: "credulous", pos: "adj", definition: "too ready to believe", example: "A credulous audience.", clue: "Believes too easily" },
  { word: "cryptic", pos: "adj", definition: "mysterious in meaning", example: "A cryptic subject line.", clue: "Coded on purpose" },
  { word: "culpable", pos: "adj", definition: "deserving blame", example: "Culpable for the delay.", clue: "Blame lands here" },
  { word: "cursory", pos: "adj", definition: "hasty and not thorough", example: "A cursory glance.", clue: "Quick skim only" },
  { word: "dauntless", pos: "adj", definition: "fearless and determined", example: "A dauntless volunteer.", clue: "Fear can't land" },
  { word: "dearth", pos: "noun", definition: "a scarcity or lack", example: "A dearth of quiet spaces.", clue: "Not enough of it" },
  { word: "debacle", pos: "noun", definition: "a sudden ignominious failure", example: "The launch became a debacle.", clue: "Public flop" },
  { word: "debilitate", pos: "verb", definition: "to make weak", example: "Fatigue can debilitate judgment.", clue: "Drain the strength" },
  { word: "decorum", pos: "noun", definition: "proper behavior", example: "Maintain decorum.", clue: "Proper manners" },
  { word: "deferential", pos: "adj", definition: "showing respect", example: "A deferential nod.", clue: "Respectful manner" },
  { word: "deleterious", pos: "adj", definition: "causing harm", example: "Deleterious effects.", clue: "Quietly harmful" },
  { word: "demure", pos: "adj", definition: "reserved and modest", example: "A demure smile.", clue: "Modest reserved" },
  { word: "denigrate", pos: "verb", definition: "to criticize unfairly", example: "Do not denigrate careful work.", clue: "Talk down unfairly" },
  { word: "derivative", pos: "adj", definition: "imitative of another's work", example: "The design felt derivative.", clue: "Copied the vibe" },
  { word: "desultory", pos: "adj", definition: "lacking a plan", example: "A desultory stroll.", clue: "Aimless wandering" },
  { word: "diaphanous", pos: "adj", definition: "light and translucent", example: "Diaphanous curtains.", clue: "See-through soft fabric" },
  { word: "didactic", pos: "adj", definition: "intended to teach", example: "Gently didactic.", clue: "Teaching tone" },
  { word: "diffident", pos: "adj", definition: "shy from lack of confidence", example: "A diffident speaker.", clue: "Shy from doubt" },
  { word: "dilatory", pos: "adj", definition: "slow to act", example: "Dilatory replies.", clue: "Dragging feet" },
  { word: "discreet", pos: "adj", definition: "careful not to attract attention", example: "Be discreet.", clue: "Quiet about secrets" },
  { word: "discretion", pos: "noun", definition: "careful judgment; freedom to decide", example: "Use your discretion.", clue: "Your careful call" },
  { word: "disparate", pos: "adj", definition: "essentially different", example: "Disparate views.", clue: "Very unlike" },
  { word: "dispassionate", pos: "adj", definition: "not swayed by emotion", example: "A dispassionate review.", clue: "Cool-head review" },
  { word: "disseminate", pos: "verb", definition: "to spread widely", example: "Disseminated the findings.", clue: "Scatter the news wide" },
  { word: "dissonance", pos: "noun", definition: "a lack of harmony", example: "Cognitive dissonance.", clue: "Notes that clash" },
  { word: "dogmatic", pos: "adj", definition: "asserting opinions as absolute", example: "A dogmatic stance.", clue: "My way only" },
  { word: "droll", pos: "adj", definition: "oddly amusing in a dry way", example: "A droll aside.", clue: "Dry funny" },
  { word: "duplicity", pos: "noun", definition: "deceitfulness", example: "Duplicity eroded trust.", clue: "Two-faced dealing" },
  { word: "ebullient", pos: "adj", definition: "cheerful and energetic", example: "An ebullient welcome.", clue: "Bubbling enthusiasm" },
  { word: "eclectic", pos: "adj", definition: "drawing from varied sources", example: "An eclectic playlist.", clue: "Mix from everywhere" },
  { word: "edify", pos: "verb", definition: "to instruct or improve", example: "Stories can edify.", clue: "Build the mind up" },
  { word: "effervescent", pos: "adj", definition: "vivacious and enthusiastic", example: "Effervescent energy.", clue: "Sparkling personality" },
  { word: "efficacious", pos: "adj", definition: "effective in producing a result", example: "An efficacious habit.", clue: "Actually works" },
  { word: "effrontery", pos: "noun", definition: "insolent boldness", example: "Had the effrontery to interrupt.", clue: "Cheeky nerve" },
  { word: "egregious", pos: "adj", definition: "outstandingly bad", example: "An egregious error.", clue: "Remarkably awful" },
  { word: "elucidate", pos: "verb", definition: "to make clear", example: "Elucidate that step.", clue: "Shine a light on it" },
  { word: "elusive", pos: "adj", definition: "hard to find or achieve", example: "The answer remained elusive.", clue: "Hard to pin down" },
  { word: "emaciated", pos: "adj", definition: "abnormally thin or weak", example: "Emaciated after drought.", clue: "Wasted thin" },
  { word: "embellish", pos: "verb", definition: "to decorate with extras", example: "Don't embellish the facts.", clue: "Dress up with extras" },
  { word: "emulate", pos: "verb", definition: "to match by imitation", example: "Emulate mentors.", clue: "Copy to catch up" },
  { word: "enervate", pos: "verb", definition: "to drain of energy", example: "Heat can enervate.", clue: "Sap the energy" },
  { word: "engender", pos: "verb", definition: "to give rise to", example: "Trust engenders collaboration.", clue: "Give birth to a feeling" },
  { word: "enigma", pos: "noun", definition: "a mysterious person or thing", example: "The ending remained an enigma.", clue: "Living riddle" },
  { word: "ennui", pos: "noun", definition: "listlessness from boredom", example: "Midweek ennui.", clue: "Bored blah feeling" },
  { word: "ephemeral", pos: "adj", definition: "lasting a very short time", example: "Fame can be ephemeral.", clue: "Here then gone" },
  { word: "equanimity", pos: "noun", definition: "calmness under stress", example: "Met news with equanimity.", clue: "Even keel under fire" },
  { word: "equivocal", pos: "adj", definition: "open to more than one reading", example: "An equivocal answer.", clue: "Could go either way" },
  { word: "erudite", pos: "adj", definition: "showing great knowledge", example: "An erudite footnote.", clue: "Book-smart depth" },
  { word: "esoteric", pos: "adj", definition: "understood by few", example: "An esoteric joke.", clue: "In-crowd only" },
  { word: "espouse", pos: "verb", definition: "to adopt or support a cause", example: "Espoused open standards.", clue: "Marry a cause" },
  { word: "ethereal", pos: "adj", definition: "extremely delicate and light", example: "An ethereal melody.", clue: "Almost otherworldly" },
  { word: "euphemism", pos: "noun", definition: "a mild word for something harsh", example: "A euphemism softened news.", clue: "Softer word for hard thing" },
  { word: "evanescent", pos: "adj", definition: "quickly fading", example: "An evanescent scent.", clue: "Fades like mist" },
  { word: "exacerbate", pos: "verb", definition: "to make a problem worse", example: "Noise can exacerbate fatigue.", clue: "Pour fuel on the problem" },
  { word: "exculpate", pos: "verb", definition: "to clear of blame", example: "Evidence helped exculpate her.", clue: "Clear of blame" },
  { word: "exigent", pos: "adj", definition: "pressing; demanding", example: "Exigent deadlines.", clue: "Urgent demand" },
  { word: "exonerate", pos: "verb", definition: "to officially clear of blame", example: "The audit exonerated the team.", clue: "Officially cleared" },
  { word: "exorbitant", pos: "adj", definition: "unreasonably high", example: "An exorbitant fee.", clue: "Price way off orbit" },
  { word: "expedient", pos: "adj", definition: "convenient though possibly improper", example: "An expedient fix.", clue: "Handy maybe-shady shortcut" },
  { word: "extol", pos: "verb", definition: "to praise enthusiastically", example: "Critics extolled the craft.", clue: "Sing high praise" },
  { word: "extraneous", pos: "adj", definition: "irrelevant or unrelated", example: "Cut extraneous detail.", clue: "Extra and unused" },
  { word: "facetious", pos: "adj", definition: "joking at an inappropriate time", example: "A facetious remark.", clue: "Wrong-time joking" },
  { word: "fallacious", pos: "adj", definition: "based on a mistaken belief", example: "A fallacious assumption.", clue: "Built on a false step" },
  { word: "fastidious", pos: "adj", definition: "very attentive to detail", example: "A fastidious editor.", clue: "Picky careful" },
  { word: "fatuous", pos: "adj", definition: "silly and pointless", example: "A fatuous claim.", clue: "Empty silly" },
  { word: "fervent", pos: "adj", definition: "passionately intense", example: "A fervent defense.", clue: "Warmly intense" },
  { word: "fidelity", pos: "noun", definition: "faithfulness", example: "Fidelity to the brief.", clue: "Loyal sticking-to" },
  { word: "flippant", pos: "adj", definition: "not showing serious respect", example: "A flippant reply.", clue: "Too casual about serious" },
  { word: "florid", pos: "adj", definition: "overly ornate in style", example: "Florid prose.", clue: "Overdecorated language" },
  { word: "fortuitous", pos: "adj", definition: "happening by lucky chance", example: "A fortuitous meeting.", clue: "Lucky accident" },
  { word: "fractious", pos: "adj", definition: "irritable and quarrelsome", example: "A fractious debate.", clue: "Ready to snap" },
  { word: "frugal", pos: "adj", definition: "sparing; economical", example: "A frugal approach.", clue: "Careful with spend" },
  { word: "furtive", pos: "adj", definition: "secretive; avoiding notice", example: "A furtive glance.", clue: "Sneaky glance" },
  { word: "garrulous", pos: "adj", definition: "excessively talkative", example: "A garrulous neighbor.", clue: "Won't stop chatting" },
  { word: "germane", pos: "adj", definition: "relevant to the matter", example: "Keep comments germane.", clue: "On-topic and useful" },
  { word: "gregarious", pos: "adj", definition: "fond of company", example: "A gregarious host.", clue: "People person" },
  { word: "guile", pos: "noun", definition: "sly cunning", example: "Negotiated without guile.", clue: "Cunning slyness" },
  { word: "hackneyed", pos: "adj", definition: "overused and unoriginal", example: "A hackneyed metaphor.", clue: "Worn-out phrase" },
  { word: "harbinger", pos: "noun", definition: "a sign of what is coming", example: "Clouds were a harbinger of rain.", clue: "Early messenger" },
  { word: "hegemony", pos: "noun", definition: "leadership or dominance", example: "Cultural hegemony.", clue: "Dominant grip" },
  { word: "heresy", pos: "noun", definition: "belief against orthodoxy", example: "Felt like heresy.", clue: "Against the official creed" },
  { word: "hiatus", pos: "noun", definition: "a pause or gap", example: "After a short hiatus.", clue: "Break in the run" },
  { word: "hubris", pos: "noun", definition: "excessive pride", example: "Hubris preceded the fall.", clue: "Pride before the fall" },
  { word: "iconoclast", pos: "noun", definition: "one who attacks cherished beliefs", example: "An iconoclast challenged ritual.", clue: "Breaker of sacred cows" },
  { word: "idiosyncrasy", pos: "noun", definition: "a peculiar personal habit", example: "A charming idiosyncrasy.", clue: "Personal quirky habit" },
  { word: "ignominious", pos: "adj", definition: "publicly disgraceful", example: "An ignominious exit.", clue: "Publicly shameful" },
  { word: "immutable", pos: "adj", definition: "unchanging over time", example: "Habits feel immutable.", clue: "Can't be changed" },
  { word: "impassive", pos: "adj", definition: "showing no emotion", example: "An impassive face.", clue: "Poker face" },
  { word: "impeccable", pos: "adj", definition: "flawless; of highest standard", example: "Impeccable timing.", clue: "Spotless quality" },
  { word: "impediment", pos: "noun", definition: "a hindrance", example: "Noise was an impediment.", clue: "Thing in the way" },
  { word: "impervious", pos: "adj", definition: "unable to be affected", example: "Impervious to flattery.", clue: "Nothing gets through" },
  { word: "impetuous", pos: "adj", definition: "acting quickly without thought", example: "An impetuous decision.", clue: "Rush without thinking" },
  { word: "implacable", pos: "adj", definition: "unable to be placated", example: "Implacable deadlines.", clue: "Cannot be soothed" },
  { word: "implicit", pos: "adj", definition: "implied but not stated", example: "Trust was implicit.", clue: "Said without saying" },
  { word: "importune", pos: "verb", definition: "to ask pressingly", example: "Do not importune busy people.", clue: "Pushy asking" },
  { word: "impugn", pos: "verb", definition: "to dispute honesty or truth", example: "Tried to impugn the data.", clue: "Attack credibility" },
  { word: "inane", pos: "adj", definition: "silly; senseless", example: "An inane debate.", clue: "Empty nonsense" },
  { word: "incisive", pos: "adj", definition: "clear and sharply analytical", example: "Incisive questions.", clue: "Cuts clean to the point" },
  { word: "incongruous", pos: "adj", definition: "not in harmony", example: "An incongruous joke.", clue: "Doesn't match the scene" },
  { word: "incredulous", pos: "adj", definition: "unwilling to believe", example: "An incredulous look.", clue: "Can't believe it" },
  { word: "indefatigable", pos: "adj", definition: "persisting tirelessly", example: "An indefatigable volunteer.", clue: "Never tires out" },
  { word: "indigenous", pos: "adj", definition: "originating in a place", example: "Indigenous knowledge.", clue: "Native to the place" },
  { word: "indolent", pos: "adj", definition: "wanting to avoid activity", example: "An indolent afternoon.", clue: "Lazy lounging" },
  { word: "ineffable", pos: "adj", definition: "too great for words", example: "An ineffable calm.", clue: "Beyond words" },
  { word: "ineluctable", pos: "adj", definition: "unable to be avoided", example: "Change felt ineluctable.", clue: "Can't escape it" },
  { word: "inexorable", pos: "adj", definition: "impossible to stop", example: "Inexorable deadlines.", clue: "Unstoppable march" },
  { word: "ingenuous", pos: "adj", definition: "innocent and unsuspecting", example: "An ingenuous question.", clue: "Innocent open-hearted" },
  { word: "inimical", pos: "adj", definition: "hostile; harmful", example: "Noise is inimical to focus.", clue: "Hostile to the goal" },
  { word: "innocuous", pos: "adj", definition: "not harmful", example: "An innocuous remark.", clue: "Harmless on paper" },
  { word: "inordinate", pos: "adj", definition: "unusually large", example: "An inordinate amount.", clue: "Way more than usual" },
  { word: "insidious", pos: "adj", definition: "gradually harmful", example: "Insidious doubt.", clue: "Sneaky harm" },
  { word: "insipid", pos: "adj", definition: "lacking flavor or interest", example: "An insipid slogan.", clue: "Flavorless and dull" },
  { word: "insolent", pos: "adj", definition: "rude and disrespectful", example: "An insolent reply.", clue: "Rude and bold" },
  { word: "insular", pos: "adj", definition: "narrowly isolated in outlook", example: "An insular view.", clue: "Island mindset" },
  { word: "intrepid", pos: "adj", definition: "fearless; adventurous", example: "An intrepid traveler.", clue: "Brave explorer energy" },
  { word: "inure", pos: "verb", definition: "to accustom to something unpleasant", example: "Inured to late nights.", clue: "Toughen by exposure" },
  { word: "invective", pos: "noun", definition: "abusive language", example: "Dripped with invective.", clue: "Angry insult stream" },
  { word: "inveigle", pos: "verb", definition: "to persuade by flattery or deception", example: "Tried to inveigle a pass.", clue: "Trick into agreeing" },
  { word: "irascible", pos: "adj", definition: "easily angered", example: "An irascible editor.", clue: "Quick to snap" },
  { word: "irony", pos: "noun", definition: "saying the opposite of what is meant", example: "Irony sharpened the essay.", clue: "Says opposite for effect" },
  { word: "itinerant", pos: "adj", definition: "traveling from place to place", example: "An itinerant teacher.", clue: "On the road for work" },
  { word: "jovial", pos: "adj", definition: "cheerful and friendly", example: "A jovial host.", clue: "Merry and warm" },
  { word: "judicious", pos: "adj", definition: "showing good judgment", example: "A judicious edit.", clue: "Wise call" },
  { word: "juxtapose", pos: "verb", definition: "to place side by side for contrast", example: "Juxtapose old and new.", clue: "Side-by-side contrast" },
  { word: "laconic", pos: "adj", definition: "using very few words", example: "A laconic reply.", clue: "Few words, big punch" },
  { word: "languid", pos: "adj", definition: "slow and lacking energy", example: "A languid afternoon.", clue: "Slow lazy calm" },
  { word: "latent", pos: "adj", definition: "present but not yet developed", example: "Latent talent.", clue: "Hidden potential" },
  { word: "laudable", pos: "adj", definition: "deserving praise", example: "A laudable effort.", clue: "Worth praising" },
  { word: "lethargic", pos: "adj", definition: "sluggish; low energy", example: "A lethargic Monday.", clue: "Low-energy sluggish" },
  { word: "levity", pos: "noun", definition: "humor or lightness", example: "A touch of levity.", clue: "Lightness in a heavy room" },
  { word: "lucid", pos: "adj", definition: "clear and easy to understand", example: "A lucid explainer.", clue: "Crystal clear" },
  { word: "lugubrious", pos: "adj", definition: "mournful; dismal", example: "A lugubrious tone.", clue: "Mournful and heavy" },
  { word: "lurid", pos: "adj", definition: "shockingly sensational", example: "Lurid headlines.", clue: "Shocking bright" },
  { word: "magnanimous", pos: "adj", definition: "generous or forgiving", example: "A magnanimous gesture.", clue: "Big-hearted forgive" },
  { word: "maladroit", pos: "adj", definition: "clumsy; awkward", example: "A maladroit apology.", clue: "Clumsy move" },
  { word: "malaise", pos: "noun", definition: "a vague discomfort", example: "A quiet malaise.", clue: "Vague unwell feeling" },
  { word: "malevolent", pos: "adj", definition: "wishing harm", example: "A malevolent rumor.", clue: "Wishing harm" },
  { word: "malleable", pos: "adj", definition: "easily shaped or influenced", example: "Habits are malleable.", clue: "Can be shaped" },
  { word: "maudlin", pos: "adj", definition: "self-pityingly emotional", example: "A maudlin speech.", clue: "Tearful over the top" },
  { word: "maverick", pos: "noun", definition: "an independent-minded person", example: "A maverick challenged the brief.", clue: "Goes their own way" },
  { word: "mendacious", pos: "adj", definition: "lying; untruthful", example: "A mendacious claim.", clue: "Lying by nature" },
  { word: "mercurial", pos: "adj", definition: "liable to sudden mood changes", example: "A mercurial temperament.", clue: "Mood like quicksilver" },
  { word: "meticulous", pos: "adj", definition: "extremely careful about detail", example: "Meticulous notes.", clue: "Detail-obsessed care" },
  { word: "modicum", pos: "noun", definition: "a small amount", example: "A modicum of patience.", clue: "Tiny bit" },
  { word: "mollify", pos: "verb", definition: "to soothe anger", example: "A soft reply mollified.", clue: "Soften the anger" },
  { word: "morose", pos: "adj", definition: "sullen and gloomy", example: "A morose silence.", clue: "Gloomy sulk" },
  { word: "multifarious", pos: "adj", definition: "many and varied", example: "Multifarious interests.", clue: "Many and varied" },
  { word: "mundane", pos: "adj", definition: "dull; everyday", example: "Mundane tasks.", clue: "Everyday dull" },
  { word: "munificent", pos: "adj", definition: "very generous", example: "A munificent gift.", clue: "Lavishly generous" },
  { word: "myopic", pos: "adj", definition: "lacking foresight", example: "A myopic plan.", clue: "Short-sighted" },
  { word: "nadir", pos: "noun", definition: "the lowest point", example: "Morale hit a nadir.", clue: "Bottom of the curve" },
  { word: "nascent", pos: "adj", definition: "just coming into being", example: "A nascent idea.", clue: "Just being born" },
  { word: "nebulous", pos: "adj", definition: "vague; unclear", example: "A nebulous brief.", clue: "Foggy and vague" },
  { word: "nefarious", pos: "adj", definition: "wicked or criminal", example: "A nefarious scheme.", clue: "Villain-level bad" },
  { word: "nemesis", pos: "noun", definition: "a long-standing rival or downfall", example: "Deadlines became his nemesis.", clue: "Arch-rival of fate" },
  { word: "nonchalant", pos: "adj", definition: "casually calm", example: "A nonchalant shrug.", clue: "Cool like it's nothing" },
  { word: "nostalgia", pos: "noun", definition: "sentimental longing for the past", example: "Nostalgia softened the memoir.", clue: "Sweet ache for then" },
  { word: "obdurate", pos: "adj", definition: "stubbornly unyielding", example: "An obdurate stance.", clue: "Hard-headed stubborn" },
  { word: "obfuscate", pos: "verb", definition: "to make unclear", example: "Jargon can obfuscate.", clue: "Cloud the meaning" },
  { word: "oblique", pos: "adj", definition: "indirect; not explicit", example: "An oblique hint.", clue: "Sideways approach" },
  { word: "obsequious", pos: "adj", definition: "excessively eager to please", example: "Obsequious praise.", clue: "Overly eager to please" },
  { word: "obstinate", pos: "adj", definition: "stubbornly refusing to change", example: "An obstinate bug.", clue: "Stubborn as a mule" },
  { word: "obtuse", pos: "adj", definition: "slow to understand", example: "An obtuse reply.", clue: "Missing the point" },
  { word: "odious", pos: "adj", definition: "extremely unpleasant", example: "An odious chore.", clue: "Deeply unpleasant" },
  { word: "officious", pos: "adj", definition: "assertively bossy", example: "An officious clerk.", clue: "Bossy without invite" },
  { word: "ominous", pos: "adj", definition: "suggesting something bad", example: "Ominous clouds.", clue: "Bad-sign vibe" },
  { word: "onerous", pos: "adj", definition: "burdensome", example: "An onerous checklist.", clue: "Heavy burden of work" },
  { word: "opaque", pos: "adj", definition: "not transparent; hard to understand", example: "The policy remained opaque.", clue: "Can't see through it" },
  { word: "opulent", pos: "adj", definition: "ostentatiously luxurious", example: "An opulent lobby.", clue: "Lavishly rich look" },
  { word: "ostensible", pos: "adj", definition: "appearing to be true", example: "The ostensible reason.", clue: "Stated reason maybe not real" },
  { word: "ostentatious", pos: "adj", definition: "showy in a vulgar way", example: "Ostentatious branding.", clue: "Show-off display" },
  { word: "overt", pos: "adj", definition: "done openly", example: "Overt hostility.", clue: "Out in the open" },
  { word: "palatable", pos: "adj", definition: "acceptable; pleasant enough", example: "A palatable compromise.", clue: "Easy enough to swallow" },
  { word: "panacea", pos: "noun", definition: "a cure for all problems", example: "No panacea for burnout.", clue: "Cure-all myth" },
  { word: "paradigm", pos: "noun", definition: "a typical pattern or model", example: "A new paradigm.", clue: "Model of how things work" },
  { word: "paragon", pos: "noun", definition: "a perfect example", example: "A paragon of patience.", clue: "Perfect example person" },
  { word: "paramount", pos: "adj", definition: "most important", example: "Clarity is paramount.", clue: "Top priority" },
  { word: "parsimonious", pos: "adj", definition: "unwilling to spend", example: "A parsimonious budget.", clue: "Tight with money" },
  { word: "partisan", pos: "adj", definition: "biased toward a side", example: "Partisan noise.", clue: "Team-loyalty bias" },
  { word: "pastiche", pos: "noun", definition: "a work imitating other styles", example: "Felt like a pastiche.", clue: "Patchwork imitation" },
  { word: "pathos", pos: "noun", definition: "quality that evokes pity", example: "Pathos deepened the scene.", clue: "Sad-string pull" },
  { word: "paucity", pos: "noun", definition: "insufficient quantity", example: "A paucity of examples.", clue: "Too few of them" },
  { word: "pedantic", pos: "adj", definition: "overly concerned with minor details", example: "A pedantic note.", clue: "Nitpick teacher mode" },
  { word: "pejorative", pos: "adj", definition: "expressing contempt", example: "Avoid pejorative labels.", clue: "Insulting label tone" },
  { word: "penchant", pos: "noun", definition: "a strong liking", example: "A penchant for walks.", clue: "Strong soft spot for" },
  { word: "penitent", pos: "adj", definition: "feeling sorrow for wrongdoing", example: "A penitent apology.", clue: "Sorry and showing it" },
  { word: "perfunctory", pos: "adj", definition: "done with minimum effort", example: "A perfunctory check.", clue: "Just going through motions" },
  { word: "pernicious", pos: "adj", definition: "gradually harmful", example: "Pernicious habits.", clue: "Slow poison harm" },
  { word: "perspicacious", pos: "adj", definition: "having keen insight", example: "A perspicacious editor.", clue: "Sees through quickly" },
  { word: "pertinent", pos: "adj", definition: "relevant", example: "Ask pertinent questions.", clue: "Fitting the topic" },
  { word: "pervasive", pos: "adj", definition: "spreading throughout", example: "A pervasive calm.", clue: "Everywhere in the air" },
  { word: "petulant", pos: "adj", definition: "childishly sulky", example: "A petulant sigh.", clue: "Childish sulk" },
  { word: "phlegmatic", pos: "adj", definition: "calm; unemotional", example: "A phlegmatic response.", clue: "Hard to ruffle" },
  { word: "pinnacle", pos: "noun", definition: "the highest point of success", example: "A career pinnacle.", clue: "Highest peak" },
  { word: "pithy", pos: "adj", definition: "concise and forceful", example: "A pithy summary.", clue: "Short and punchy" },
  { word: "placate", pos: "verb", definition: "to make less angry", example: "A soft word can placate.", clue: "Calm someone down" },
  { word: "platitude", pos: "noun", definition: "an overused remark", example: "A hollow platitude.", clue: "Empty wise-sounding line" },
  { word: "plethora", pos: "noun", definition: "an excessive amount", example: "A plethora of options.", clue: "Too many choices" },
  { word: "poignant", pos: "adj", definition: "evoking sadness or regret", example: "A poignant farewell.", clue: "Touchingly sad" },
  { word: "polemic", pos: "noun", definition: "a strong written or verbal attack", example: "The essay became a polemic.", clue: "Fighting argument piece" },
  { word: "pragmatic", pos: "adj", definition: "practical and realistic", example: "A pragmatic fix.", clue: "Practical first" },
  { word: "precarious", pos: "adj", definition: "not securely held", example: "A precarious balance.", clue: "Wobbly and risky" },
  { word: "precipitous", pos: "adj", definition: "dangerously steep or sudden", example: "A precipitous drop.", clue: "Steep sudden drop" },
  { word: "preclude", pos: "verb", definition: "to prevent from happening", example: "Rules preclude shortcuts.", clue: "Rule out in advance" },
  { word: "precocious", pos: "adj", definition: "having early ability", example: "A precocious reader.", clue: "Advanced too early" },
  { word: "predilection", pos: "noun", definition: "a preference", example: "A predilection for mornings.", clue: "Preferred leaning" },
  { word: "preeminent", pos: "adj", definition: "surpassing all others", example: "A preeminent voice.", clue: "Standing above the rest" },
  { word: "prescient", pos: "adj", definition: "knowing beforehand", example: "A prescient note.", clue: "Knew before it happened" },
  { word: "presumptuous", pos: "adj", definition: "overstepping bounds", example: "A presumptuous ask.", clue: "Overstepping boldly" },
  { word: "prevaricate", pos: "verb", definition: "to speak evasively", example: "Don't prevaricate.", clue: "Dodge the straight answer" },
  { word: "pristine", pos: "adj", definition: "in original clean condition", example: "A pristine draft.", clue: "Untouched clean" },
  { word: "probity", pos: "noun", definition: "strong moral honesty", example: "Probity built the brand.", clue: "Upright honesty" },
  { word: "proclivity", pos: "noun", definition: "a habitual tendency", example: "A proclivity for tinkering.", clue: "Habitual leaning toward" },
  { word: "prodigal", pos: "adj", definition: "wastefully lavish", example: "A prodigal launch.", clue: "Wastefully lavish" },
  { word: "prodigious", pos: "adj", definition: "impressively great", example: "A prodigious amount.", clue: "Impressively huge" },
  { word: "profligate", pos: "adj", definition: "recklessly extravagant", example: "Profligate spending.", clue: "Reckless spender" },
  { word: "profound", pos: "adj", definition: "very deep or intense", example: "A profound quiet.", clue: "Deeply felt" },
  { word: "prolific", pos: "adj", definition: "producing much", example: "A prolific month.", clue: "Turns out a lot" },
  { word: "propensity", pos: "noun", definition: "a natural inclination", example: "A propensity to overthink.", clue: "Natural pull toward" },
  { word: "propitious", pos: "adj", definition: "favorable", example: "A propitious moment.", clue: "Favorable timing" },
  { word: "prosaic", pos: "adj", definition: "commonplace; not poetic", example: "A prosaic truth.", clue: "Ordinary, not poetic" },
  { word: "proscribe", pos: "verb", definition: "to forbid", example: "The rule proscribes shortcuts.", clue: "Officially forbid" },
  { word: "protean", pos: "adj", definition: "able to change readily", example: "A protean career.", clue: "Shape-shifting" },
  { word: "protract", pos: "verb", definition: "to prolong", example: "Don't protract the meeting.", clue: "Drag it out longer" },
  { word: "provident", pos: "adj", definition: "showing foresight", example: "A provident habit.", clue: "Plans ahead wisely" },
  { word: "provisional", pos: "adj", definition: "temporary", example: "A provisional plan.", clue: "For now, temporary" },
  { word: "prudence", pos: "noun", definition: "careful good sense", example: "Prudence suggested waiting.", clue: "Careful good sense" },
  { word: "pugnacious", pos: "adj", definition: "eager to argue or fight", example: "A pugnacious tone.", clue: "Ready to scrap" },
  { word: "pulchritude", pos: "noun", definition: "beauty", example: "Architectural pulchritude.", clue: "Fancy word for beauty" },
  { word: "punctilious", pos: "adj", definition: "attentive to correct detail", example: "A punctilious host.", clue: "Fussy about etiquette" },
  { word: "quell", pos: "verb", definition: "to put an end to", example: "A calm voice can quell panic.", clue: "Put down the unrest" },
  { word: "querulous", pos: "adj", definition: "complaining peevishly", example: "A querulous email.", clue: "Whiny complaints" },
  { word: "quixotic", pos: "adj", definition: "unrealistically idealistic", example: "A quixotic plan.", clue: "Dreamy impractical" },
  { word: "quotidian", pos: "adj", definition: "everyday; ordinary", example: "The quotidian ritual.", clue: "Everyday ordinary" },
  { word: "rancor", pos: "noun", definition: "bitter resentfulness", example: "Old rancor resurfaced.", clue: "Bitter leftover feeling" },
  { word: "rapacious", pos: "adj", definition: "aggressively greedy", example: "Rapacious growth.", clue: "Grabby greed" },
  { word: "rarefied", pos: "adj", definition: "distant from ordinary life", example: "A rarefied debate.", clue: "Thin air elite" },
  { word: "recalcitrant", pos: "adj", definition: "obstinately uncooperative", example: "A recalcitrant bug.", clue: "Won't cooperate" },
  { word: "recant", pos: "verb", definition: "to withdraw a former belief", example: "He refused to recant.", clue: "Take back a belief" },
  { word: "recondite", pos: "adj", definition: "little known; abstruse", example: "A recondite reference.", clue: "Obscure deep cut" },
  { word: "redolent", pos: "adj", definition: "strongly suggestive", example: "Air redolent of rain.", clue: "Smell that evokes" },
  { word: "redress", pos: "noun", definition: "remedy or compensation", example: "They sought redress.", clue: "Make it right again" },
  { word: "refractory", pos: "adj", definition: "stubborn; hard to manage", example: "A refractory problem.", clue: "Hard to manage" },
  { word: "relegate", pos: "verb", definition: "to assign to a lower place", example: "Don't relegate craft.", clue: "Bump down the ranks" },
  { word: "remonstrate", pos: "verb", definition: "to protest reproachfully", example: "Parents remonstrated.", clue: "Protest with words" },
  { word: "renege", pos: "verb", definition: "to go back on a promise", example: "Don't renege on the brief.", clue: "Break the promise" },
  { word: "replete", pos: "adj", definition: "well filled", example: "A talk replete with examples.", clue: "Stuffed full of" },
  { word: "reprehensible", pos: "adj", definition: "deserving censure", example: "A reprehensible leak.", clue: "Blameworthy bad" },
  { word: "reprieve", pos: "noun", definition: "a temporary relief from trouble", example: "A brief reprieve.", clue: "Temporary mercy delay" },
  { word: "reprove", pos: "verb", definition: "to reprimand", example: "She reproved the claim.", clue: "Mild scold" },
  { word: "repudiate", pos: "verb", definition: "to reject", example: "They repudiated the rumor.", clue: "Reject outright" },
  { word: "rescind", pos: "verb", definition: "to revoke or cancel", example: "The offer was rescinded.", clue: "Take back officially" },
  { word: "resilient", pos: "adj", definition: "able to recover quickly", example: "A resilient team.", clue: "Bounces back" },
  { word: "resolute", pos: "adj", definition: "admirably determined", example: "A resolute stand.", clue: "Firmly decided" },
  { word: "reticent", pos: "adj", definition: "reserved; not revealing much", example: "A reticent smile.", clue: "Keeps thoughts close" },
  { word: "reverent", pos: "adj", definition: "showing deep respect", example: "A reverent hush.", clue: "Deep respect quiet" },
  { word: "rhetoric", pos: "noun", definition: "persuasive language craft", example: "Empty rhetoric.", clue: "Persuasive language craft" },
  { word: "rigor", pos: "noun", definition: "strict thoroughness", example: "Intellectual rigor.", clue: "Strict thoroughness" },
  { word: "robust", pos: "adj", definition: "strong and sturdy", example: "A robust process.", clue: "Sturdy and strong" },
  { word: "rudimentary", pos: "adj", definition: "basic; elementary", example: "Rudimentary tools.", clue: "Basic starter level" },
  { word: "ruminate", pos: "verb", definition: "to think deeply", example: "She ruminated on the ending.", clue: "Chew on a thought" },
  { word: "sagacious", pos: "adj", definition: "wise and discerning", example: "A sagacious mentor.", clue: "Wise and sharp" },
  { word: "salient", pos: "adj", definition: "most noticeable", example: "Name the salient points.", clue: "Stands out most" },
  { word: "salubrious", pos: "adj", definition: "health-giving", example: "A salubrious walk.", clue: "Good for health" },
  { word: "sanguine", pos: "adj", definition: "optimistically cheerful", example: "A sanguine outlook.", clue: "Cheerfully hopeful" },
  { word: "sardonic", pos: "adj", definition: "grimly mocking", example: "A sardonic smile.", clue: "Bitter wry mock" },
  { word: "scrupulous", pos: "adj", definition: "diligent and principled", example: "Scrupulous sourcing.", clue: "Carefully principled" },
  { word: "sedulous", pos: "adj", definition: "diligent and careful", example: "Sedulous revision.", clue: "Diligent and steady" },
  { word: "seminal", pos: "adj", definition: "strongly influencing later work", example: "A seminal essay.", clue: "Seed of later work" },
  { word: "serendipity", pos: "noun", definition: "happy accidental discovery", example: "Serendipity led them there.", clue: "Happy accident find" },
  { word: "servile", pos: "adj", definition: "excessively submissive", example: "A servile tone.", clue: "Overly submissive" },
  { word: "sinecure", pos: "noun", definition: "a job with little work", example: "Felt like a sinecure.", clue: "Easy job, soft pay" },
  { word: "sobriety", pos: "noun", definition: "seriousness; clear-headedness", example: "Sobriety marked the day.", clue: "Serious clear-headed" },
  { word: "solicitous", pos: "adj", definition: "showing anxious concern", example: "A solicitous note.", clue: "Anxiously caring" },
  { word: "solvent", pos: "adj", definition: "able to pay debts", example: "A solvent business.", clue: "Able to pay debts" },
  { word: "somber", pos: "adj", definition: "dark or serious in tone", example: "A somber palette.", clue: "Dark and serious" },
  { word: "sophistry", pos: "noun", definition: "clever but false reasoning", example: "Sophistry dressed a weak claim.", clue: "Clever false reasoning" },
  { word: "soporific", pos: "adj", definition: "tending to induce sleep", example: "A soporific lecture.", clue: "Sleep-inducing" },
  { word: "spartan", pos: "adj", definition: "marked by austerity", example: "A spartan desk.", clue: "Bare and tough" },
  { word: "specious", pos: "adj", definition: "apparently true but false", example: "A specious argument.", clue: "Looks right, isn't" },
  { word: "sporadic", pos: "adj", definition: "occurring irregularly", example: "Sporadic updates.", clue: "Here and there" },
  { word: "spurious", pos: "adj", definition: "not genuine", example: "Spurious claims.", clue: "Fake claim" },
  { word: "staid", pos: "adj", definition: "sedate and unadventurous", example: "A staid design.", clue: "Sedate and proper" },
  { word: "stolid", pos: "adj", definition: "calm and showing little emotion", example: "A stolid presence.", clue: "Unemotional rock" },
  { word: "strident", pos: "adj", definition: "loud and harsh", example: "A strident tone.", clue: "Harsh loud voice" },
  { word: "stymie", pos: "verb", definition: "to hinder progress", example: "Confusion can stymie a team.", clue: "Block progress cold" },
  { word: "sublime", pos: "adj", definition: "inspiring awe by excellence", example: "A sublime quiet.", clue: "Awe-level beauty" },
  { word: "subterfuge", pos: "noun", definition: "deceit used to achieve a goal", example: "Subterfuge eroded trust.", clue: "Sneaky cover story" },
  { word: "succinct", pos: "adj", definition: "briefly and clearly expressed", example: "A succinct brief.", clue: "Brief and clear" },
  { word: "supercilious", pos: "adj", definition: "behaving as if superior", example: "A supercilious smirk.", clue: "Looking down the nose" },
  { word: "superfluous", pos: "adj", definition: "unnecessary", example: "Cut superfluous words.", clue: "Extra, not needed" },
  { word: "surreptitious", pos: "adj", definition: "kept secret", example: "A surreptitious glance.", clue: "Secret on the sly" },
  { word: "sycophant", pos: "noun", definition: "a flatterer of the powerful", example: "A sycophant filled the room.", clue: "Flattery climber" },
  { word: "tacit", pos: "adj", definition: "understood without being said", example: "Tacit approval.", clue: "Agreed without saying" },
  { word: "taciturn", pos: "adj", definition: "reserved in speech", example: "A taciturn neighbor.", clue: "Few words spoken" },
  { word: "tangential", pos: "adj", definition: "only slightly related", example: "A tangential remark.", clue: "Side-track related" },
  { word: "tantamount", pos: "adj", definition: "equivalent in effect", example: "Silence was tantamount to consent.", clue: "As good as equal to" },
  { word: "temerity", pos: "noun", definition: "reckless boldness", example: "Had the temerity to interrupt.", clue: "Nerve to dare" },
  { word: "tenacious", pos: "adj", definition: "holding firmly", example: "A tenacious editor.", clue: "Won't let go" },
  { word: "tenuous", pos: "adj", definition: "very weak or slight", example: "A tenuous connection.", clue: "Thin fragile link" },
  { word: "terse", pos: "adj", definition: "abruptly brief", example: "A terse reply.", clue: "Abruptly brief" },
  { word: "timorous", pos: "adj", definition: "nervous; timid", example: "A timorous knock.", clue: "Nervous timid" },
  { word: "torpid", pos: "adj", definition: "inactive; sluggish", example: "A torpid afternoon.", clue: "Sluggish inactive" },
  { word: "tractable", pos: "adj", definition: "easy to manage", example: "A tractable problem.", clue: "Manageable to handle" },
  { word: "transient", pos: "adj", definition: "lasting only briefly", example: "A transient mood.", clue: "Passing through" },
  { word: "trenchant", pos: "adj", definition: "incisive and forceful", example: "A trenchant critique.", clue: "Sharp cutting insight" },
  { word: "truculent", pos: "adj", definition: "aggressively defiant", example: "A truculent reply.", clue: "Aggressively defiant" },
  { word: "turgid", pos: "adj", definition: "swollen; pompously overblown", example: "Turgid prose.", clue: "Puffed-up prose" },
  { word: "ubiquitous", pos: "adj", definition: "present everywhere", example: "Ubiquitous screens.", clue: "Everywhere you look" },
  { word: "umbrage", pos: "noun", definition: "offense or annoyance", example: "She took umbrage.", clue: "Took offense" },
  { word: "unassailable", pos: "adj", definition: "unable to be attacked", example: "An unassailable argument.", clue: "Can't be knocked down" },
  { word: "uncanny", pos: "adj", definition: "strangely unsettling", example: "An uncanny resemblance.", clue: "Weirdly familiar" },
  { word: "unctuous", pos: "adj", definition: "excessively flattering", example: "An unctuous compliment.", clue: "Oily flattery" },
  { word: "undermine", pos: "verb", definition: "to weaken gradually", example: "Gossip can undermine trust.", clue: "Weaken from below" },
  { word: "unequivocal", pos: "adj", definition: "leaving no doubt", example: "An unequivocal yes.", clue: "Crystal clear yes/no" },
  { word: "unflappable", pos: "adj", definition: "remaining calm under stress", example: "An unflappable host.", clue: "Can't be rattled" },
  { word: "ungainly", pos: "adj", definition: "awkward", example: "An ungainly draft.", clue: "Clumsy awkward" },
  { word: "unilateral", pos: "adj", definition: "done by one side only", example: "A unilateral decision.", clue: "One side only" },
  { word: "unobtrusive", pos: "adj", definition: "not conspicuous", example: "An unobtrusive design.", clue: "Doesn't shout" },
  { word: "unprecedented", pos: "adj", definition: "never done before", example: "An unprecedented surge.", clue: "Never before seen" },
  { word: "unpretentious", pos: "adj", definition: "not trying to impress", example: "An unpretentious café.", clue: "No show-off energy" },
  { word: "unscrupulous", pos: "adj", definition: "without moral principles", example: "Unscrupulous tactics.", clue: "No moral brakes" },
  { word: "untenable", pos: "adj", definition: "not able to be maintained", example: "An untenable claim.", clue: "Can't hold that position" },
  { word: "upbraid", pos: "verb", definition: "to scold", example: "She upbraided the edit.", clue: "Scold sharply" },
  { word: "urbane", pos: "adj", definition: "suave and refined", example: "An urbane host.", clue: "City-smooth manners" },
  { word: "usurp", pos: "verb", definition: "to seize without right", example: "Do not usurp the agenda.", clue: "Seize without right" },
  { word: "utilitarian", pos: "adj", definition: "designed for use over beauty", example: "A utilitarian tool.", clue: "Function over flash" },
  { word: "vacillate", pos: "verb", definition: "to waver between options", example: "Don't vacillate forever.", clue: "Swing back and forth" },
  { word: "vacuous", pos: "adj", definition: "lacking thought", example: "A vacuous slogan.", clue: "Empty-headed" },
  { word: "vapid", pos: "adj", definition: "dull; lifeless", example: "A vapid conversation.", clue: "Dull and flat" },
  { word: "vehement", pos: "adj", definition: "showing strong feeling", example: "A vehement defense.", clue: "Forcefully intense" },
  { word: "venerate", pos: "verb", definition: "to regard with deep respect", example: "They venerate craft.", clue: "Deeply revere" },
  { word: "veracity", pos: "noun", definition: "truthfulness", example: "Veracity mattered more than spin.", clue: "Truthfulness" },
  { word: "verbose", pos: "adj", definition: "using too many words", example: "A verbose email.", clue: "Too many words" },
  { word: "verdant", pos: "adj", definition: "lushly green", example: "A verdant courtyard.", clue: "Lush green" },
  { word: "verisimilitude", pos: "noun", definition: "appearance of being true", example: "Verisimilitude made it stick.", clue: "Looks-true quality" },
  { word: "vernacular", pos: "noun", definition: "everyday spoken language", example: "Write in the vernacular.", clue: "Everyday spoken tongue" },
  { word: "vestige", pos: "noun", definition: "a remaining trace", example: "A vestige of the old design.", clue: "Last leftover trace" },
  { word: "vicarious", pos: "adj", definition: "experienced through another", example: "Vicarious thrills.", clue: "Felt through someone else" },
  { word: "vicissitude", pos: "noun", definition: "a change of fortune", example: "Vicissitudes of freelance life.", clue: "Ups and downs of fate" },
  { word: "vilify", pos: "verb", definition: "to speak abusively about", example: "Don't vilify critics.", clue: "Trash-talk unfairly" },
  { word: "vindicate", pos: "verb", definition: "to clear of blame or prove right", example: "Time will vindicate care.", clue: "Prove right eventually" },
  { word: "virtuoso", pos: "noun", definition: "a highly skilled performer", example: "A virtuoso of editing.", clue: "Master of the craft" },
  { word: "virulent", pos: "adj", definition: "extremely harmful", example: "A virulent rumor.", clue: "Poisonously strong" },
  { word: "visceral", pos: "adj", definition: "felt deep in the gut", example: "A visceral reaction.", clue: "Gut-level feel" },
  { word: "vitiate", pos: "verb", definition: "to spoil or impair", example: "Noise can vitiate focus.", clue: "Spoil the quality" },
  { word: "vitriolic", pos: "adj", definition: "filled with bitter criticism", example: "A vitriolic review.", clue: "Acid bitter critique" },
  { word: "vociferous", pos: "adj", definition: "loudly insistent", example: "Vociferous objections.", clue: "Loudly insistent" },
  { word: "volatile", pos: "adj", definition: "liable to change rapidly", example: "A volatile market.", clue: "Unstable and explosive" },
  { word: "volition", pos: "noun", definition: "the power of willing", example: "Of her own volition.", clue: "By one's own will" },
  { word: "voracious", pos: "adj", definition: "wanting great quantities", example: "A voracious reader.", clue: "Insatiably hungry" },
  { word: "wheedle", pos: "verb", definition: "to coax with flattery", example: "Don't wheedle for shortcuts.", clue: "Coax with sweet talk" },
  { word: "whimsical", pos: "adj", definition: "playfully quaint", example: "A whimsical aside.", clue: "Playfully odd" },
  { word: "wistful", pos: "adj", definition: "full of vague longing", example: "A wistful look.", clue: "Soft longing look" },
  { word: "zealous", pos: "adj", definition: "fervently devoted", example: "A zealous advocate.", clue: "Passionately devoted" },
  { word: "zenith", pos: "noun", definition: "the highest point", example: "A creative zenith.", clue: "Highest high point" },
  { word: "aberration", pos: "noun", definition: "a departure from normal", example: "An aberration, not a pattern.", clue: "Odd departure from normal" },
  { word: "absolve", pos: "verb", definition: "to free from guilt", example: "Absolved earlier doubt.", clue: "Wipe clean of guilt" },
  { word: "acrimony", pos: "noun", definition: "bitterness of feeling", example: "Acrimony soured the thread.", clue: "Bitter feeling leftover" },
  { word: "adulation", pos: "noun", definition: "excessive admiration", example: "Empty adulation.", clue: "Over-the-top praise" },
  { word: "aesthetic", pos: "noun", definition: "a sense of beauty or style", example: "Cream and ink aesthetic.", clue: "Sense of what looks right" },
  { word: "affinity", pos: "noun", definition: "a natural liking", example: "An affinity for longform.", clue: "Natural pull toward" },
  { word: "aggrandize", pos: "verb", definition: "to enhance power or status", example: "Don't aggrandize thin claims.", clue: "Puff up status" },
  { word: "ambivalent", pos: "adj", definition: "having mixed feelings", example: "Ambivalent about the pivot.", clue: "Yes and no at once" },
  { word: "amenable", pos: "adj", definition: "open to suggestion", example: "An amenable team.", clue: "Open to being guided" },
  { word: "amiable", pos: "adj", definition: "friendly", example: "An amiable guide.", clue: "Friendly warmth" },
  { word: "analogous", pos: "adj", definition: "comparable in key ways", example: "An analogous case.", clue: "Similar in structure" },
  { word: "anathema", pos: "noun", definition: "something intensely disliked", example: "Delay was anathema.", clue: "Utterly hated thing" },
  { word: "anodyne", pos: "adj", definition: "unlikely to offend", example: "An anodyne statement.", clue: "Blandly soothing" },
  { word: "antithesis", pos: "noun", definition: "the direct opposite", example: "Speed was the antithesis of care.", clue: "Exact opposite" },
  { word: "apathy", pos: "noun", definition: "lack of interest", example: "Apathy killed the project.", clue: "Can't-be-bothered void" },
  { word: "aplomb", pos: "noun", definition: "self-confident composure", example: "Handled with aplomb.", clue: "Cool confident poise" },
  { word: "apposite", pos: "adj", definition: "apt; well chosen", example: "An apposite example.", clue: "Perfectly fitting" },
  { word: "archetype", pos: "noun", definition: "a typical original pattern", example: "An archetype of teaching.", clue: "Original pattern type" },
  { word: "assuage", pos: "verb", definition: "to ease or relieve", example: "Music can assuage nerves.", clue: "Ease the ache" },
  { word: "attenuate", pos: "verb", definition: "to reduce in force", example: "Filters attenuate noise.", clue: "Thin out the force" },
  { word: "attrition", pos: "noun", definition: "gradual wearing down", example: "Attrition wore the team.", clue: "Wear-down over time" },
  { word: "august", pos: "adj", definition: "respected and impressive", example: "An august library.", clue: "Dignified grandeur" },
  { word: "axiomatic", pos: "adj", definition: "self-evidently true", example: "It seemed axiomatic.", clue: "True without needing proof" },
  { word: "catalyst", pos: "noun", definition: "something that precipitates change", example: "Curiosity was the catalyst.", clue: "Spark that starts change" },
  { word: "clandestine", pos: "adj", definition: "kept secret", example: "A clandestine draft.", clue: "Secret underground" },
  { word: "coalesce", pos: "verb", definition: "to come together as one", example: "Ideas coalesced overnight.", clue: "Merge into one" },
  { word: "epiphany", pos: "noun", definition: "a sudden revelation", example: "A quiet epiphany.", clue: "Sudden lightbulb" },
  { word: "galvanize", pos: "verb", definition: "to shock into action", example: "A story can galvanize.", clue: "Shock into motion" },
  { word: "mitigate", pos: "verb", definition: "to make less severe", example: "Mitigate risk early.", clue: "Soften the harm" },
  { word: "nuance", pos: "noun", definition: "a subtle difference", example: "Listen for nuance.", clue: "Fine shade of meaning" },
  { word: "petrichor", pos: "noun", definition: "the smell of earth after rain", example: "Petrichor after the storm.", clue: "Rain-on-earth smell" }
] as const)

export const WOTD_WORD_COUNT = WOTD_WORDS.length
