<script setup lang="ts">
definePageMeta({ layout: false })
/**
 * Soul of the Universe — one tap, one arrangement on nine pitches.
 * The score is utils/solfeggio-compose.mjs, generated by scripts/solfeggio-compose.py.
 * Web Audio only. The pitch list is a modern numerological set, not a therapy.
 */
import { useThemeStore } from '~/stores/theme'
import { composeSong } from '~/utils/solfeggio-compose.mjs'
import {
  PHI,
  phiRingRadii,
  pentagonVertices,
  goldenRectangleCorners,
} from '~/utils/solfeggio-math.mjs'

useSeoMeta({
  title: 'Soul of the Universe · Engage',
  description: 'One piece on nine pitches.',
  ogUrl: 'https://entertrainer.in/engage/solfeggio',
})

const MASTER_GAIN = 0.16
const LEAVE_FADE = 1.5
const FLOOR = 0.0008

type Phase = 'land' | 'hold' | 'leaving'
type ScoreEvent = { bar: number, beat: number, durBeats: number, hz: number, voice: string, gain: number, slide?: number }
type Section = { name: string, bar: number, bars: number }
type Song = {
  seed: number
  bpm: number
  meter: string
  totalBars: number
  duration: number
  centerHz: number
  sections: Section[]
  events: ScoreEvent[]
}
type LiveNote = { start: number, sources: AudioScheduledSourceNode[], nodes: AudioNode[] }
type DrawProfile = {
  rings: number
  stars: number[]
  rect: boolean
  spin: number
  rot: number
  twin: number
  scale: number
  accent: string
}

const SECTION_LABEL: Record<string, string> = {
  intro: 'Intro',
  theme: 'Theme',
  chorus: 'Chorus',
  development: 'Development',
  coda: 'Coda',
}

const theme = useThemeStore()
const phase = ref<Phase>('land')
const sounding = ref(0)
const playedOnce = ref(false)
const sectionName = ref('')
const sectionLabel = computed(() => SECTION_LABEL[sectionName.value] || '')
const vizEl = ref<HTMLCanvasElement | null>(null)

let currentSong: Song | null = null
let pieceOrigin = 0
let vizRaf = 0
let vizAngle = 0
let strokePhase = 0
let lastAudioTime = -1
let reduceMotion = false
let motionQuery: MediaQueryList | null = null
let resizeObserver: ResizeObserver | null = null

let audioCtx: AudioContext | null = null
let graphNodes: AudioNode[] = []
let master: GainNode | null = null
let drumBus: GainNode | null = null
let musicBus: GainNode | null = null
let chordFilter: BiquadFilterNode | null = null
let chordDuck: GainNode | null = null
let noiseBuf: AudioBuffer | null = null
let live: LiveNote[] = []
let generation = 0
let leaveTimer = 0
let tickTimer = 0

function audioContextCtor(): typeof AudioContext | null {
  if (typeof window === 'undefined') return null
  const w = window as Window & { webkitAudioContext?: typeof AudioContext }
  return window.AudioContext || w.webkitAudioContext || null
}

function ensureContext() {
  const AC = audioContextCtor()
  if (!AC) return null
  if (!audioCtx || audioCtx.state === 'closed') audioCtx = new AC()
  if (audioCtx.state === 'suspended') void audioCtx.resume()
  return audioCtx
}

function clearTimers() {
  if (leaveTimer) window.clearTimeout(leaveTimer)
  if (tickTimer) window.clearTimeout(tickTimer)
  leaveTimer = 0
  tickTimer = 0
}

function stopLive(when = 0) {
  for (const note of live) {
    const at = Math.max(when, note.start)
    for (const source of note.sources) {
      try { source.stop(at) } catch { /* already stopped, or not started */ }
    }
    for (const node of note.nodes) {
      try { node.disconnect() } catch { /* already disconnected */ }
    }
  }
  live = []
}

function disconnectGraph() {
  for (const node of graphNodes) {
    try { node.disconnect() } catch { /* already disconnected */ }
  }
  graphNodes = []
  master = null
  drumBus = null
  musicBus = null
  chordFilter = null
  chordDuck = null
}

function teardown() {
  clearTimers()
  stopVizLoop()
  stopLive(audioCtx ? audioCtx.currentTime : 0)
  disconnectGraph()
  currentSong = null
  pieceOrigin = 0
  lastAudioTime = -1
  sectionName.value = ''
  sounding.value = 0
}

function connectPan(ctx: AudioContext, source: AudioNode, dest: AudioNode, pan: number, when: number) {
  if (typeof ctx.createStereoPanner !== 'function') {
    source.connect(dest)
    return [] as AudioNode[]
  }
  const panner = ctx.createStereoPanner()
  panner.pan.setValueAtTime(pan, when)
  source.connect(panner)
  panner.connect(dest)
  return [panner]
}

function noiseBuffer(ctx: AudioContext) {
  if (noiseBuf && noiseBuf.sampleRate === ctx.sampleRate) return noiseBuf
  const n = Math.max(1, Math.floor(ctx.sampleRate * 0.25))
  const buf = ctx.createBuffer(1, n, ctx.sampleRate)
  const data = buf.getChannelData(0)
  let s = 0x6d2b79f5
  for (let i = 0; i < n; i++) {
    s = (Math.imul(s, 1664525) + 1013904223) | 0
    data[i] = ((s >>> 0) / 4294967296) * 2 - 1
  }
  noiseBuf = buf
  return buf
}

function beatLength(song: Song) {
  return 60 / song.bpm
}

function eventWhen(song: Song, event: ScoreEvent) {
  return (event.bar * 4 + event.beat) * beatLength(song)
}

function eventLength(song: Song, event: ScoreEvent) {
  return event.durBeats * beatLength(song)
}

let acidFrom = 0

function envGain(ctx: AudioContext, when: number, peak: number, attack: number, holdEnd: number, release: number) {
  const gain = ctx.createGain()
  const a = Math.max(0.004, attack)
  const end = Math.max(holdEnd, when + a) + Math.max(0.02, release)
  const level = Math.max(peak, FLOOR)
  gain.gain.setValueAtTime(FLOOR, when)
  gain.gain.exponentialRampToValueAtTime(level, when + a)
  gain.gain.setValueAtTime(level, Math.max(when + a, holdEnd))
  gain.gain.exponentialRampToValueAtTime(FLOOR, end)
  return { gain, end }
}

function startOsc(ctx: AudioContext, type: OscillatorType, hz: number, when: number, stop: number) {
  const osc = ctx.createOscillator()
  osc.type = type
  osc.frequency.setValueAtTime(Math.max(40, hz), when)
  osc.start(when)
  osc.stop(stop + 0.03)
  return osc
}

function pushLive(when: number, sources: AudioScheduledSourceNode[], nodes: AudioNode[]) {
  live.push({ start: when, sources, nodes })
}

function noiseBurst(ctx: AudioContext, when: number, stop: number) {
  const noise = ctx.createBufferSource()
  noise.buffer = noiseBuffer(ctx)
  noise.start(when)
  noise.stop(stop + 0.02)
  return noise
}

function shapeCurve(amount: number) {
  const curve = new Float32Array(256)
  for (let i = 0; i < curve.length; i++) {
    const x = (i / (curve.length - 1)) * 2 - 1
    curve[i] = Math.tanh(x * amount)
  }
  return curve
}

function spawnKick(ctx: AudioContext, dest: AudioNode, event: ScoreEvent, when: number) {
  const peak = Math.max(event.gain, FLOOR)
  const stopAt = when + 0.08
  const gain = ctx.createGain()
  gain.gain.setValueAtTime(FLOOR, when)
  gain.gain.exponentialRampToValueAtTime(peak, when + 0.004)
  gain.gain.exponentialRampToValueAtTime(FLOOR, stopAt)
  const osc = startOsc(ctx, 'sine', event.hz, when, stopAt)
  osc.frequency.exponentialRampToValueAtTime(Math.max(40, event.hz * 0.7), stopAt)
  osc.connect(gain)
  const noise = noiseBurst(ctx, when, when + 0.03)
  const filter = ctx.createBiquadFilter()
  filter.type = 'lowpass'
  filter.frequency.setValueAtTime(200, when)
  const nGain = ctx.createGain()
  nGain.gain.setValueAtTime(peak * 0.7, when)
  nGain.gain.exponentialRampToValueAtTime(FLOOR, when + 0.028)
  noise.connect(filter)
  filter.connect(nGain)
  nGain.connect(gain)
  const panners = connectPan(ctx, gain, dest, 0, when)
  pushLive(when, [osc, noise], [osc, noise, filter, nGain, gain, ...panners])
}

function spawnSnare(ctx: AudioContext, dest: AudioNode, event: ScoreEvent, when: number) {
  const peak = Math.max(event.gain, FLOOR)
  const stopAt = when + 0.12
  const gain = ctx.createGain()
  gain.gain.setValueAtTime(FLOOR, when)
  gain.gain.exponentialRampToValueAtTime(peak, when + 0.003)
  gain.gain.exponentialRampToValueAtTime(FLOOR, stopAt)
  const noise = noiseBurst(ctx, when, stopAt)
  const filter = ctx.createBiquadFilter()
  filter.type = 'bandpass'
  filter.frequency.setValueAtTime(1800, when)
  filter.Q.setValueAtTime(0.7, when)
  noise.connect(filter)
  filter.connect(gain)
  const osc = startOsc(ctx, 'triangle', event.hz, when, when + 0.05)
  const body = ctx.createGain()
  body.gain.setValueAtTime(peak * 0.28, when)
  body.gain.exponentialRampToValueAtTime(FLOOR, when + 0.045)
  osc.connect(body)
  body.connect(gain)
  const panners = connectPan(ctx, gain, dest, 0.03, when)
  pushLive(when, [noise, osc], [noise, osc, filter, body, gain, ...panners])
}

function spawnHat(ctx: AudioContext, dest: AudioNode, event: ScoreEvent, when: number) {
  const peak = Math.max(event.gain, FLOOR)
  const stopAt = when + 0.045
  const gain = ctx.createGain()
  gain.gain.setValueAtTime(FLOOR, when)
  gain.gain.exponentialRampToValueAtTime(peak, when + 0.002)
  gain.gain.exponentialRampToValueAtTime(FLOOR, stopAt)
  const noise = noiseBurst(ctx, when, stopAt)
  const filter = ctx.createBiquadFilter()
  filter.type = 'highpass'
  filter.frequency.setValueAtTime(7000, when)
  noise.connect(filter)
  filter.connect(gain)
  const panners = connectPan(ctx, gain, dest, -0.14, when)
  pushLive(when, [noise], [noise, filter, gain, ...panners])
}

function spawn808(ctx: AudioContext, dest: AudioNode, event: ScoreEvent, when: number) {
  const peak = Math.max(event.gain, FLOOR)
  const stopAt = when + 0.42
  const env = envGain(ctx, when, peak, 0.004, when + 0.08, 0.34)
  const osc = startOsc(ctx, 'sine', event.hz * 3.4, when, env.end)
  osc.frequency.exponentialRampToValueAtTime(Math.max(40, event.hz * 0.5), when + 0.26)
  const shaper = ctx.createWaveShaper()
  shaper.curve = shapeCurve(4.5)
  shaper.oversample = '2x'
  osc.connect(shaper)
  shaper.connect(env.gain)
  const panners = connectPan(ctx, env.gain, dest, 0, when)
  pushLive(when, [osc], [osc, shaper, env.gain, ...panners])
  void stopAt
}

function spawnCowbell(ctx: AudioContext, dest: AudioNode, event: ScoreEvent, when: number) {
  const peak = Math.max(event.gain, FLOOR)
  const env = envGain(ctx, when, peak, 0.002, when + 0.03, 0.12)
  const filter = ctx.createBiquadFilter()
  filter.type = 'bandpass'
  filter.frequency.setValueAtTime(event.hz * 2, when)
  filter.Q.setValueAtTime(8, when)
  const a = startOsc(ctx, 'square', event.hz, when, env.end)
  const b = startOsc(ctx, 'square', event.hz * 1.5, when, env.end)
  const mix = ctx.createGain()
  a.connect(mix)
  b.connect(mix)
  mix.connect(filter)
  filter.connect(env.gain)
  const panners = connectPan(ctx, env.gain, dest, 0.22, when)
  pushLive(when, [a, b], [a, b, mix, filter, env.gain, ...panners])
}

function spawnTabla(ctx: AudioContext, dest: AudioNode, event: ScoreEvent, when: number, bayan: boolean) {
  const peak = Math.max(event.gain, FLOOR)
  const stop = when + (bayan ? 0.22 : 0.09)
  const env = envGain(ctx, when, peak, 0.003, when + 0.02, bayan ? 0.2 : 0.07)
  const osc = startOsc(ctx, 'sine', event.hz * (bayan ? 2.2 : 1.7), when, env.end)
  osc.frequency.exponentialRampToValueAtTime(Math.max(40, event.hz * (bayan ? 0.55 : 0.82)), stop)
  const noise = noiseBurst(ctx, when, when + (bayan ? 0.05 : 0.03))
  const filter = ctx.createBiquadFilter()
  filter.type = bayan ? 'lowpass' : 'bandpass'
  filter.frequency.setValueAtTime(bayan ? 240 : 1800, when)
  filter.Q.setValueAtTime(bayan ? 0.7 : 2.4, when)
  const nGain = ctx.createGain()
  nGain.gain.setValueAtTime(peak * (bayan ? 0.45 : 0.7), when)
  nGain.gain.exponentialRampToValueAtTime(FLOOR, when + (bayan ? 0.05 : 0.03))
  noise.connect(filter)
  filter.connect(nGain)
  osc.connect(env.gain)
  nGain.connect(env.gain)
  const panners = connectPan(ctx, env.gain, dest, bayan ? -0.12 : 0.16, when)
  pushLive(when, [osc, noise], [osc, noise, filter, nGain, env.gain, ...panners])
}

function spawnMridangam(ctx: AudioContext, dest: AudioNode, event: ScoreEvent, when: number) {
  const peak = Math.max(event.gain, FLOOR)
  const env = envGain(ctx, when, peak, 0.003, when + 0.04, 0.16)
  const body = startOsc(ctx, 'sine', event.hz * 1.4, when, env.end)
  body.frequency.exponentialRampToValueAtTime(Math.max(40, event.hz), when + 0.12)
  const ring = startOsc(ctx, 'triangle', event.hz * 2, when, env.end)
  const ringGain = ctx.createGain()
  ringGain.gain.setValueAtTime(0.35, when)
  ring.connect(ringGain)
  const noise = noiseBurst(ctx, when, when + 0.02)
  const click = ctx.createGain()
  click.gain.setValueAtTime(peak * 0.4, when)
  click.gain.exponentialRampToValueAtTime(FLOOR, when + 0.02)
  noise.connect(click)
  body.connect(env.gain)
  ringGain.connect(env.gain)
  click.connect(env.gain)
  const panners = connectPan(ctx, env.gain, dest, 0.08, when)
  pushLive(when, [body, ring, noise], [body, ring, ringGain, noise, click, env.gain, ...panners])
}

function spawnTanpura(ctx: AudioContext, dest: AudioNode, event: ScoreEvent, when: number, dur: number) {
  const peak = Math.max(event.gain, FLOOR)
  const env = envGain(ctx, when, peak, 0.08, when + dur, 0.4)
  const osc = startOsc(ctx, 'sawtooth', event.hz, when, env.end)
  const jaw = ctx.createBiquadFilter()
  jaw.type = 'bandpass'
  jaw.frequency.setValueAtTime(Math.max(80, event.hz * 3), when)
  jaw.Q.setValueAtTime(6, when)
  const body = ctx.createGain()
  body.gain.value = 0.65
  osc.connect(body)
  osc.connect(jaw)
  body.connect(env.gain)
  jaw.connect(env.gain)
  const panners = connectPan(ctx, env.gain, dest, event.hz > 220 ? 0.06 : -0.06, when)
  pushLive(when, [osc], [osc, jaw, body, env.gain, ...panners])
}

function spawnPad(ctx: AudioContext, dest: AudioNode, event: ScoreEvent, when: number, dur: number) {
  const peak = Math.max(event.gain, FLOOR) * 0.7
  const env = envGain(ctx, when, peak, 0.45, when + dur, 1.7)
  const filter = ctx.createBiquadFilter()
  filter.type = 'lowpass'
  filter.frequency.setValueAtTime(900, when)
  filter.Q.setValueAtTime(0.4, when)
  const sources: OscillatorNode[] = []
  for (const ratio of [0.992, 1, 1.008]) {
    const osc = startOsc(ctx, 'sawtooth', event.hz * ratio, when, env.end)
    osc.connect(filter)
    sources.push(osc)
  }
  filter.connect(env.gain)
  const panners = connectPan(ctx, env.gain, dest, event.hz >= 639 ? 0.35 : -0.35, when)
  pushLive(when, sources, [...sources, filter, env.gain, ...panners])
}

function spawnChoir(ctx: AudioContext, dest: AudioNode, event: ScoreEvent, when: number, dur: number) {
  const peak = Math.max(event.gain, FLOOR)
  const env = envGain(ctx, when, peak, 0.18, when + dur, 0.7)
  const osc = startOsc(ctx, 'sawtooth', event.hz, when, env.end)
  const formants = [
    { f: 730, q: 8, g: 0.72 },
    { f: 1150, q: 6, g: 0.4 },
    { f: 2500, q: 5, g: 0.16 },
  ]
  const nodes: AudioNode[] = [osc, env.gain]
  for (const formant of formants) {
    const filter = ctx.createBiquadFilter()
    filter.type = 'bandpass'
    filter.frequency.setValueAtTime(formant.f, when)
    filter.Q.setValueAtTime(formant.q, when)
    const g = ctx.createGain()
    g.gain.setValueAtTime(formant.g, when)
    osc.connect(filter)
    filter.connect(g)
    g.connect(env.gain)
    nodes.push(filter, g)
  }
  const panners = connectPan(ctx, env.gain, dest, 0.12, when)
  pushLive(when, [osc], [...nodes, ...panners])
}

function spawnBow(ctx: AudioContext, dest: AudioNode, event: ScoreEvent, when: number, dur: number, kind: 'erhu' | 'violin' | 'cello') {
  const peak = Math.max(event.gain, FLOOR)
  const env = envGain(ctx, when, peak, kind === 'cello' ? 0.16 : kind === 'erhu' ? 0.09 : 0.05, when + dur, kind === 'cello' ? 0.35 : 0.16)
  const osc = startOsc(ctx, kind === 'cello' ? 'triangle' : 'sawtooth', event.hz, when, env.end)
  const lfo = startOsc(ctx, 'sine', kind === 'cello' ? 4.2 : 5.4, when, env.end)
  const lfoGain = ctx.createGain()
  lfoGain.gain.setValueAtTime(kind === 'erhu' ? 4 : kind === 'cello' ? 1.4 : 2.4, when)
  lfo.connect(lfoGain)
  lfoGain.connect(osc.frequency)
  const filter = ctx.createBiquadFilter()
  filter.type = kind === 'erhu' ? 'bandpass' : 'lowpass'
  filter.frequency.setValueAtTime(kind === 'erhu' ? 1450 : kind === 'cello' ? 420 : 1900, when)
  filter.Q.setValueAtTime(kind === 'erhu' ? 8 : kind === 'cello' ? 0.45 : 1.3, when)
  osc.connect(filter)
  filter.connect(env.gain)
  const panners = connectPan(ctx, env.gain, dest, kind === 'erhu' ? 0.26 : kind === 'cello' ? -0.18 : 0.12, when)
  pushLive(when, [osc, lfo], [osc, lfo, lfoGain, filter, env.gain, ...panners])
}

function spawnBreathy(ctx: AudioContext, dest: AudioNode, event: ScoreEvent, when: number, dur: number, dip: boolean, bright: boolean) {
  const peak = Math.max(event.gain, FLOOR)
  const env = envGain(ctx, when, peak, dip ? 0.03 : 0.06, when + dur, 0.22)
  const osc = startOsc(ctx, bright ? 'square' : 'triangle', event.hz, when, env.end)
  if (dip) {
    osc.frequency.setValueAtTime(Math.max(40, event.hz * 0.9), when)
    osc.frequency.exponentialRampToValueAtTime(Math.max(40, event.hz), when + 0.1)
  }
  const filter = ctx.createBiquadFilter()
  filter.type = 'bandpass'
  filter.frequency.setValueAtTime(bright ? 2200 : 1200, when)
  filter.Q.setValueAtTime(bright ? 1.2 : 2.2, when)
  const noise = noiseBurst(ctx, when, when + dur)
  const nGain = ctx.createGain()
  nGain.gain.setValueAtTime(peak * (dip ? 0.55 : bright ? 0.35 : 0.28), when)
  noise.connect(filter)
  filter.connect(nGain)
  osc.connect(env.gain)
  nGain.connect(env.gain)
  const panners = connectPan(ctx, env.gain, dest, dip ? -0.4 : bright ? 0.42 : -0.32, when)
  pushLive(when, [osc, noise], [osc, noise, filter, nGain, env.gain, ...panners])
}

function spawnPluck(ctx: AudioContext, dest: AudioNode, event: ScoreEvent, when: number, dur: number, kind: string) {
  const peak = Math.max(event.gain, FLOOR)
  const release = kind === 'koto' ? 0.18 : kind === 'harp' ? 1.1 : kind === 'sitar' ? 0.55 : kind === 'guitar' ? 0.4 : kind === 'veena' ? 0.7 : kind === 'pop' ? 0.16 : 0.45
  const env = envGain(ctx, when, peak, kind === 'harp' ? 0.012 : 0.004, when + Math.min(dur, 0.08), release)
  const osc = startOsc(ctx, kind === 'oud' || kind === 'harp' ? 'triangle' : 'sawtooth', event.hz, when, env.end)
  const filter = ctx.createBiquadFilter()
  filter.type = 'lowpass'
  const open = kind === 'koto' || kind === 'pop' ? 4200 : kind === 'oud' ? 700 : kind === 'veena' ? 1400 : 2200
  filter.frequency.setValueAtTime(open, when)
  filter.frequency.exponentialRampToValueAtTime(Math.max(180, open * 0.25), when + release)
  const noise = noiseBurst(ctx, when, when + 0.02)
  const nFilter = ctx.createBiquadFilter()
  nFilter.type = 'highpass'
  nFilter.frequency.setValueAtTime(kind === 'oud' ? 400 : 900, when)
  const nGain = ctx.createGain()
  nGain.gain.setValueAtTime(peak * 0.35, when)
  nGain.gain.exponentialRampToValueAtTime(FLOOR, when + 0.02)
  noise.connect(nFilter)
  nFilter.connect(nGain)
  osc.connect(filter)
  filter.connect(env.gain)
  nGain.connect(env.gain)
  const sources: AudioScheduledSourceNode[] = [osc, noise]
  const nodes: AudioNode[] = [osc, noise, filter, nFilter, nGain, env.gain]
  if (kind === 'sitar') {
    for (const ratio of [2, 3]) {
      const sym = startOsc(ctx, 'sine', event.hz * ratio, when, env.end + 0.4)
      const sg = ctx.createGain()
      sg.gain.setValueAtTime(peak * 0.12, when)
      sg.gain.exponentialRampToValueAtTime(FLOOR, env.end + 0.35)
      sym.connect(sg)
      sg.connect(env.gain)
      sources.push(sym)
      nodes.push(sym, sg)
    }
  }
  const pan = kind === 'sitar' ? -0.22 : kind === 'veena' ? -0.38 : kind === 'koto' ? 0.34 : kind === 'harp' ? 0.05 : kind === 'guitar' ? -0.16 : kind === 'pop' ? 0.2 : -0.26
  const panners = connectPan(ctx, env.gain, dest, pan, when)
  pushLive(when, sources, [...nodes, ...panners])
}

function spawnPiano(ctx: AudioContext, dest: AudioNode, event: ScoreEvent, when: number, dur: number) {
  const peak = Math.max(event.gain, FLOOR)
  const env = envGain(ctx, when, peak, 0.006, when + Math.min(dur, 0.12), 0.55)
  const ratios = [1, 2, 3.01, 4.03]
  const amps = [1, 0.42, 0.2, 0.08]
  const sources: OscillatorNode[] = []
  const nodes: AudioNode[] = [env.gain]
  for (let i = 0; i < ratios.length; i++) {
    const osc = startOsc(ctx, 'sine', event.hz * ratios[i], when, env.end)
    const g = ctx.createGain()
    g.gain.setValueAtTime(amps[i], when)
    g.gain.exponentialRampToValueAtTime(Math.max(0.02, amps[i] * 0.2), when + 0.4)
    osc.connect(g)
    g.connect(env.gain)
    sources.push(osc)
    nodes.push(osc, g)
  }
  const noise = noiseBurst(ctx, when, when + 0.015)
  const hammer = ctx.createBiquadFilter()
  hammer.type = 'highpass'
  hammer.frequency.setValueAtTime(1800, when)
  const hGain = ctx.createGain()
  hGain.gain.setValueAtTime(peak * 0.25, when)
  hGain.gain.exponentialRampToValueAtTime(FLOOR, when + 0.015)
  noise.connect(hammer)
  hammer.connect(hGain)
  hGain.connect(env.gain)
  const panners = connectPan(ctx, env.gain, dest, 0.08, when)
  pushLive(when, [...sources, noise], [...nodes, noise, hammer, hGain, ...panners])
}

function spawnTrumpet(ctx: AudioContext, dest: AudioNode, event: ScoreEvent, when: number, dur: number) {
  const peak = Math.max(event.gain, FLOOR)
  const env = envGain(ctx, when, peak, 0.008, when + dur, 0.06)
  const osc = startOsc(ctx, 'sawtooth', event.hz * 0.98, when, env.end)
  osc.frequency.exponentialRampToValueAtTime(Math.max(40, event.hz), when + 0.04)
  const filter = ctx.createBiquadFilter()
  filter.type = 'bandpass'
  filter.frequency.setValueAtTime(1600, when)
  filter.Q.setValueAtTime(5, when)
  osc.connect(filter)
  filter.connect(env.gain)
  const panners = connectPan(ctx, env.gain, dest, 0.3, when)
  pushLive(when, [osc], [osc, filter, env.gain, ...panners])
}

function spawnClarinet(ctx: AudioContext, dest: AudioNode, event: ScoreEvent, when: number, dur: number) {
  const peak = Math.max(event.gain, FLOOR)
  const env = envGain(ctx, when, peak, 0.04, when + dur, 0.12)
  const sources: OscillatorNode[] = []
  const nodes: AudioNode[] = [env.gain]
  const odds = [1, 3, 5]
  for (let i = 0; i < odds.length; i++) {
    const osc = startOsc(ctx, 'sine', event.hz * odds[i], when, env.end)
    const g = ctx.createGain()
    g.gain.setValueAtTime(1 / odds[i], when)
    osc.connect(g)
    g.connect(env.gain)
    sources.push(osc)
    nodes.push(osc, g)
  }
  const panners = connectPan(ctx, env.gain, dest, 0.18, when)
  pushLive(when, sources, [...nodes, ...panners])
}

function spawnSax(ctx: AudioContext, dest: AudioNode, event: ScoreEvent, when: number, dur: number) {
  const peak = Math.max(event.gain, FLOOR)
  const env = envGain(ctx, when, peak, 0.05, when + dur, 0.14)
  const osc = startOsc(ctx, 'sawtooth', event.hz, when, env.end)
  const filter = ctx.createBiquadFilter()
  filter.type = 'bandpass'
  filter.frequency.setValueAtTime(1400, when)
  filter.Q.setValueAtTime(3.2, when)
  const noise = noiseBurst(ctx, when, when + dur)
  const nGain = ctx.createGain()
  nGain.gain.setValueAtTime(peak * 0.08, when)
  osc.connect(filter)
  noise.connect(nGain)
  filter.connect(env.gain)
  nGain.connect(env.gain)
  const panners = connectPan(ctx, env.gain, dest, -0.28, when)
  pushLive(when, [osc, noise], [osc, noise, filter, nGain, env.gain, ...panners])
}

function spawnBells(ctx: AudioContext, dest: AudioNode, event: ScoreEvent, when: number) {
  const peak = Math.max(event.gain, FLOOR)
  const env = envGain(ctx, when, peak, 0.004, when + 0.05, 1.6)
  const sources: OscillatorNode[] = []
  const nodes: AudioNode[] = [env.gain]
  for (const [ratio, amp] of [[1, 1], [2.01, 0.45], [2.76, 0.28], [5.4, 0.08]] as const) {
    const osc = startOsc(ctx, 'sine', event.hz * ratio, when, env.end)
    const g = ctx.createGain()
    g.gain.setValueAtTime(amp, when)
    osc.connect(g)
    g.connect(env.gain)
    sources.push(osc)
    nodes.push(osc, g)
  }
  const panners = connectPan(ctx, env.gain, dest, 0.36, when)
  pushLive(when, sources, [...nodes, ...panners])
}

function spawnSupersaw(ctx: AudioContext, dest: AudioNode, event: ScoreEvent, when: number, dur: number) {
  const peak = Math.max(event.gain, FLOOR)
  const env = envGain(ctx, when, peak, 0.02, when + dur, 0.12)
  const filter = ctx.createBiquadFilter()
  filter.type = 'lowpass'
  filter.frequency.setValueAtTime(3200, when)
  filter.Q.setValueAtTime(0.6, when)
  const sources: OscillatorNode[] = []
  for (const ratio of [0.994, 1, 1.006]) {
    const osc = startOsc(ctx, 'sawtooth', event.hz * ratio, when, env.end)
    osc.connect(filter)
    sources.push(osc)
  }
  filter.connect(env.gain)
  const panners = connectPan(ctx, env.gain, dest, 0.14, when)
  pushLive(when, sources, [...sources, filter, env.gain, ...panners])
}

function spawnAcid(ctx: AudioContext, dest: AudioNode, event: ScoreEvent, when: number, dur: number) {
  const peak = Math.max(event.gain, FLOOR)
  const env = envGain(ctx, when, peak, 0.008, when + dur, 0.06)
  const from = event.slide && acidFrom > 0 ? acidFrom : event.hz
  const osc = startOsc(ctx, 'sawtooth', from, when, env.end)
  if (event.slide && Math.abs(from - event.hz) > 0.5) {
    osc.frequency.exponentialRampToValueAtTime(Math.max(40, event.hz), when + Math.min(0.16, Math.max(0.04, dur * 0.45)))
  }
  acidFrom = event.hz
  const filter = ctx.createBiquadFilter()
  filter.type = 'lowpass'
  filter.Q.setValueAtTime(14, when)
  filter.frequency.setValueAtTime(180, when)
  filter.frequency.exponentialRampToValueAtTime(2200, when + Math.max(0.05, dur * 0.4))
  filter.frequency.exponentialRampToValueAtTime(240, when + Math.max(0.08, dur))
  osc.connect(filter)
  filter.connect(env.gain)
  const panners = connectPan(ctx, env.gain, dest, 0, when)
  pushLive(when, [osc], [osc, filter, env.gain, ...panners])
}

function spawnBass(ctx: AudioContext, dest: AudioNode, event: ScoreEvent, when: number, dur: number) {
  const peak = Math.max(event.gain, FLOOR)
  const env = envGain(ctx, when, peak, 0.012, when + dur, 0.06)
  const osc = startOsc(ctx, 'triangle', event.hz, when, env.end)
  const sine = startOsc(ctx, 'sine', event.hz, when, env.end)
  const filter = ctx.createBiquadFilter()
  filter.type = 'lowpass'
  filter.frequency.setValueAtTime(280, when)
  osc.connect(filter)
  sine.connect(filter)
  filter.connect(env.gain)
  const panners = connectPan(ctx, env.gain, dest, -0.08, when)
  pushLive(when, [osc, sine], [osc, sine, filter, env.gain, ...panners])
}

const DRUMS = new Set(['kick', 'snare', 'hat', '808', 'cowbell', 'tablaBayan', 'tablaDayan', 'mridangam'])
const BED = new Set(['pad', 'choir', 'piano', 'guitar', 'pluck', 'harp', 'tanpura'])

function playEvent(ctx: AudioContext, dest: AudioNode, event: ScoreEvent, when: number, dur: number) {
  const voice = event.voice
  if (voice === 'kick') return spawnKick(ctx, dest, event, when)
  if (voice === 'snare') return spawnSnare(ctx, dest, event, when)
  if (voice === 'hat') return spawnHat(ctx, dest, event, when)
  if (voice === '808') return spawn808(ctx, dest, event, when)
  if (voice === 'cowbell') return spawnCowbell(ctx, dest, event, when)
  if (voice === 'tablaBayan') return spawnTabla(ctx, dest, event, when, true)
  if (voice === 'tablaDayan') return spawnTabla(ctx, dest, event, when, false)
  if (voice === 'mridangam') return spawnMridangam(ctx, dest, event, when)
  if (voice === 'tanpura') return spawnTanpura(ctx, dest, event, when, dur)
  if (voice === 'pad') return spawnPad(ctx, dest, event, when, dur)
  if (voice === 'choir') return spawnChoir(ctx, dest, event, when, dur)
  if (voice === 'erhu') return spawnBow(ctx, dest, event, when, dur, 'erhu')
  if (voice === 'violin') return spawnBow(ctx, dest, event, when, dur, 'violin')
  if (voice === 'cello') return spawnBow(ctx, dest, event, when, dur, 'cello')
  if (voice === 'shakuhachi') return spawnBreathy(ctx, dest, event, when, dur, true, false)
  if (voice === 'bansuri') return spawnBreathy(ctx, dest, event, when, dur, false, false)
  if (voice === 'dizi') return spawnBreathy(ctx, dest, event, when, dur, false, true)
  if (voice === 'sitar') return spawnPluck(ctx, dest, event, when, dur, 'sitar')
  if (voice === 'veena') return spawnPluck(ctx, dest, event, when, dur, 'veena')
  if (voice === 'oud') return spawnPluck(ctx, dest, event, when, dur, 'oud')
  if (voice === 'koto') return spawnPluck(ctx, dest, event, when, dur, 'koto')
  if (voice === 'guitar') return spawnPluck(ctx, dest, event, when, dur, 'guitar')
  if (voice === 'harp') return spawnPluck(ctx, dest, event, when, dur, 'harp')
  if (voice === 'pluck') return spawnPluck(ctx, dest, event, when, dur, 'pop')
  if (voice === 'piano') return spawnPiano(ctx, dest, event, when, dur)
  if (voice === 'trumpet') return spawnTrumpet(ctx, dest, event, when, dur)
  if (voice === 'clarinet') return spawnClarinet(ctx, dest, event, when, dur)
  if (voice === 'saxophone') return spawnSax(ctx, dest, event, when, dur)
  if (voice === 'bells') return spawnBells(ctx, dest, event, when)
  if (voice === 'supersaw') return spawnSupersaw(ctx, dest, event, when, dur)
  if (voice === 'acid') return spawnAcid(ctx, dest, event, when, dur)
  if (voice === 'bass') return spawnBass(ctx, dest, event, when, dur)
}

function scheduleSong(ctx: AudioContext, song: Song, origin: number) {
  if (!drumBus || !musicBus || !chordFilter) return
  acidFrom = 0
  for (const event of song.events) {
    const when = origin + eventWhen(song, event)
    if (when < ctx.currentTime - 0.02) continue
    const dest = DRUMS.has(event.voice) ? drumBus : BED.has(event.voice) ? chordFilter : musicBus
    playEvent(ctx, dest, event, when, eventLength(song, event))
  }
}

const SECTION_CUTOFF: Record<string, number> = {
  intro: 880,
  theme: 1400,
  chorus: 2400,
  development: 1200,
  coda: 760,
}

function scheduleStudio(ctx: AudioContext, song: Song, origin: number) {
  if (!chordFilter || !chordDuck) return
  const beat = beatLength(song)
  let prev = SECTION_CUTOFF.intro
  chordFilter.frequency.setValueAtTime(prev, origin)
  for (const section of song.sections) {
    const when = origin + section.bar * 4 * beat
    const target = SECTION_CUTOFF[section.name] || prev
    chordFilter.frequency.setValueAtTime(Math.max(prev, 40), when)
    chordFilter.frequency.exponentialRampToValueAtTime(target, when + Math.min(beat * 2, 0.45))
    prev = target
  }
  for (const event of song.events) {
    if (event.voice !== 'kick') continue
    const when = origin + eventWhen(song, event)
    if (when < ctx.currentTime - 0.02) continue
    chordDuck.gain.setValueAtTime(1, when)
    chordDuck.gain.linearRampToValueAtTime(DUCK, when + 0.01)
    chordDuck.gain.linearRampToValueAtTime(1, when + 0.08)
  }
}

function buildGraph(ctx: AudioContext) {
  const t = ctx.currentTime
  const drums = ctx.createGain()
  const music = ctx.createGain()
  const filter = ctx.createBiquadFilter()
  const duck = ctx.createGain()
  drums.gain.setValueAtTime(1, t)
  music.gain.setValueAtTime(1, t)
  filter.type = 'lowpass'
  filter.frequency.setValueAtTime(680, t)
  filter.Q.setValueAtTime(0.7, t)
  duck.gain.setValueAtTime(1, t)
  filter.connect(duck)
  duck.connect(music)
  const out = ctx.createGain()
  out.gain.cancelScheduledValues(t)
  out.gain.setValueAtTime(FLOOR, t)
  out.gain.exponentialRampToValueAtTime(MASTER_GAIN, t + 0.05)
  drums.connect(out)
  music.connect(out)
  out.connect(ctx.destination)
  drumBus = drums
  musicBus = music
  chordFilter = filter
  chordDuck = duck
  master = out
  graphNodes = [drums, music, filter, duck, out]
}

function sectionAt(song: Song, bar: number) {
  const clamped = Math.min(song.totalBars - 1, Math.max(0, Math.floor(bar)))
  for (const section of song.sections) {
    if (clamped >= section.bar && clamped < section.bar + section.bars) return section.name
  }
  return 'coda'
}

function leadHzAt(song: Song, beat: number) {
  let hz = 0
  for (const event of song.events) {
    if (event.voice !== 'supersaw' && event.voice !== 'sitar') continue
    const start = event.bar * 4 + event.beat
    if (start > beat + 0.0001) break
    hz = event.hz
  }
  return hz
}

function runSong(gen: number, song: Song, origin: number) {
  const step = () => {
    if (gen !== generation || !audioCtx || !currentSong) return
    if (phase.value === 'land') return
    const now = audioCtx.currentTime - origin
    const beat = now / beatLength(song)
    sectionName.value = sectionAt(song, beat / 4)
    sounding.value = leadHzAt(song, beat)
    if (phase.value === 'hold' && now >= song.duration + 0.14) {
      finishLeave(gen)
      return
    }
    tickTimer = window.setTimeout(step, 100)
  }
  step()
}

function begin() {
  if (phase.value !== 'land') return
  const gen = ++generation
  clearTimers()
  stopLive(audioCtx ? audioCtx.currentTime : 0)
  disconnectGraph()

  const ctx = ensureContext()
  if (!ctx) return

  const seed = (Math.random() * 0x100000000) >>> 0
  const song = composeSong(seed) as Song
  const origin = ctx.currentTime + 0.06
  buildGraph(ctx)
  scheduleStudio(ctx, song, origin)
  scheduleSong(ctx, song, origin)
  phase.value = 'hold'
  playedOnce.value = true
  currentSong = song
  pieceOrigin = origin
  vizAngle = 0
  strokePhase = 0
  lastAudioTime = -1
  sectionName.value = 'intro'
  sounding.value = 0
  runSong(gen, song, origin)
  startVizLoop()
  paintViz(false)
}

function finishLeave(gen: number) {
  if (gen !== generation) return
  teardown()
  vizAngle = 0
  strokePhase = 0
  phase.value = 'land'
  paintViz(false)
}

function leave() {
  if (phase.value !== 'hold' || !audioCtx || !master) return
  const gen = generation
  phase.value = 'leaving'
  const t = audioCtx.currentTime
  const current = Math.max(master.gain.value, FLOOR)
  master.gain.cancelScheduledValues(t)
  master.gain.setValueAtTime(current, t)
  master.gain.exponentialRampToValueAtTime(FLOOR, t + LEAVE_FADE)
  if (leaveTimer) window.clearTimeout(leaveTimer)
  leaveTimer = window.setTimeout(() => {
    if (audioCtx) stopLive(audioCtx.currentTime)
    finishLeave(gen)
  }, LEAVE_FADE * 1000 + 40)
}

function onThemeToggle(e: Event) {
  e.stopPropagation()
  e.preventDefault()
  theme.toggle()
}

function profileFor(section: string): DrawProfile {
  if (section === 'chorus') {
    return { rings: 8, stars: [3, 5, 7], rect: true, spin: 1.85, rot: -Math.PI / 2, twin: Math.PI / 5, scale: 1.14, accent: 'chorus' }
  }
  if (section === 'theme') {
    return { rings: 6, stars: [2, 4], rect: true, spin: 0.85, rot: -Math.PI / 2, twin: 0, scale: 1, accent: 'theme' }
  }
  if (section === 'development') {
    return { rings: 7, stars: [2, 5], rect: false, spin: 1.05, rot: -Math.PI / 2 + Math.PI / 5, twin: Math.PI / 5, scale: 1.04, accent: 'development' }
  }
  if (section === 'coda') {
    return { rings: 5, stars: [3], rect: true, spin: 0.42, rot: -Math.PI / 2, twin: 0, scale: 0.9, accent: 'coda' }
  }
  return { rings: 4, stars: [2], rect: false, spin: 0.36, rot: -Math.PI / 2, twin: 0, scale: 0.82, accent: 'intro' }
}

function musicalNow(audioTime: number) {
  if (!currentSong || phase.value === 'land') {
    return { section: 'intro', hz: 0, env: 0, spin: 0.36 }
  }
  const beat = (audioTime - pieceOrigin) / beatLength(currentSong)
  const section = sectionAt(currentSong, beat / 4)
  let hz = 0
  let active = false
  for (const event of currentSong.events) {
    const start = event.bar * 4 + event.beat
    if (start > beat + 0.0001) break
    if (event.voice !== 'supersaw' && event.voice !== 'sitar') continue
    hz = event.hz
    active = beat < start + event.durBeats
  }
  const env = active ? 1 : section === 'chorus' ? 0.62 : 0.3
  return { section, hz, env, spin: profileFor(section).spin }
}

function advanceViz(audioTime: number, hz: number, env: number, spin: number) {
  if (lastAudioTime < 0) {
    lastAudioTime = audioTime
    return
  }
  const dt = Math.min(0.1, Math.max(0, audioTime - lastAudioTime))
  lastAudioTime = audioTime
  const pitch = hz > 0 ? hz : 528
  const omega = (pitch / 528) * ((Math.PI * 2) / 28)
  const dir = spin < 0 ? -1 : 1
  vizAngle += dt * omega * Math.abs(spin) * dir * (0.35 + 0.65 * env)
  strokePhase += dt * pitch * 0.02 * (0.3 + 0.7 * env)
}

function fitViz(canvas: HTMLCanvasElement) {
  const dpr = Math.min(window.devicePixelRatio || 1, 2)
  const w = Math.max(1, canvas.clientWidth)
  const h = Math.max(1, canvas.clientHeight)
  const pw = Math.round(w * dpr)
  const ph = Math.round(h * dpr)
  if (canvas.width !== pw || canvas.height !== ph) {
    canvas.width = pw
    canvas.height = ph
  }
  return dpr
}

function drawStar(
  ctx: CanvasRenderingContext2D,
  radius: number,
  rotation: number,
  env: number,
  ink: string,
  star: string,
  dash: number,
  motion: boolean,
  inkStroke: boolean,
) {
  const verts = pentagonVertices(radius, rotation)
  ctx.beginPath()
  verts.forEach((v, i) => (i === 0 ? ctx.moveTo(v.x, v.y) : ctx.lineTo(v.x, v.y)))
  ctx.closePath()
  ctx.setLineDash([])
  ctx.strokeStyle = ink
  ctx.globalAlpha = inkStroke ? 0.72 : 0.4
  ctx.lineWidth = 1.2
  ctx.stroke()

  ctx.beginPath()
  for (let i = 0; i <= 5; i++) {
    const v = verts[(i * 2) % 5]
    if (i === 0) ctx.moveTo(v.x, v.y)
    else ctx.lineTo(v.x, v.y)
  }
  ctx.strokeStyle = star
  ctx.globalAlpha = 0.45 + 0.5 * env
  ctx.lineWidth = 1.35
  if (motion) {
    ctx.setLineDash([5, 8])
    ctx.lineDashOffset = -dash
  } else {
    ctx.setLineDash([])
  }
  ctx.stroke()
  ctx.setLineDash([])
}

function drawViz(
  ctx: CanvasRenderingContext2D,
  width: number,
  height: number,
  angle: number,
  env: number,
  dash: number,
  dark: boolean,
  motion: boolean,
  section: string,
) {
  const paper = dark ? '#121214' : '#fbf8ef'
  const ink = dark ? '#ede6d6' : '#161618'
  const cobalt = '#2F5BD8'
  const profile = profileFor(section)
  const star = profile.accent === 'chorus' ? (dark ? '#e8c547' : '#c8960a') : cobalt
  ctx.fillStyle = paper
  ctx.fillRect(0, 0, width, height)

  const minSide = Math.min(width, height)
  const count = profile.rings
  const outer = minSide * 0.46 * profile.scale * (0.94 + 0.06 * env)
  const radii = phiRingRadii(count, outer / (PHI ** (count - 1)))
  const cx = width / 2
  const cy = height / 2

  ctx.save()
  ctx.translate(cx, cy)
  ctx.rotate(angle)
  ctx.lineJoin = 'miter'
  ctx.lineCap = 'butt'

  for (let i = 0; i < radii.length; i++) {
    ctx.beginPath()
    ctx.arc(0, 0, radii[i], 0, Math.PI * 2)
    ctx.strokeStyle = i % 2 === 0 ? ink : star
    ctx.globalAlpha = 0.22 + 0.38 * (i / Math.max(1, count - 1))
    ctx.lineWidth = i === count - 1 ? 1.4 : 1
    ctx.stroke()
  }

  for (const index of profile.stars) {
    const radius = radii[Math.min(index, radii.length - 1)]
    drawStar(ctx, radius, profile.rot, env, ink, star, dash, motion, index === profile.stars[profile.stars.length - 1])
    if (profile.twin) {
      drawStar(ctx, radius * 0.72, profile.rot + profile.twin, env, ink, star, dash, false, false)
    }
  }

  if (profile.rect) {
    const rect = goldenRectangleCorners(radii[Math.min(2, radii.length - 1)] * 2)
    ctx.beginPath()
    rect.forEach((c, i) => (i === 0 ? ctx.moveTo(c.x, c.y) : ctx.lineTo(c.x, c.y)))
    ctx.closePath()
    ctx.setLineDash([])
    ctx.strokeStyle = profile.accent === 'chorus' ? star : ink
    ctx.globalAlpha = 0.78
    ctx.lineWidth = profile.accent === 'chorus' ? 1.8 : 1.25
    ctx.stroke()
  }

  ctx.restore()
  ctx.globalAlpha = 1
}

function paintViz(advanceClock: boolean) {
  const canvas = vizEl.value
  if (!canvas) return
  const dpr = fitViz(canvas)
  const ctx = canvas.getContext('2d')
  if (!ctx) return
  const musical = audioCtx && currentSong ? musicalNow(audioCtx.currentTime) : musicalNow(0)
  if (advanceClock && audioCtx && currentSong && !reduceMotion && phase.value !== 'land') {
    advanceViz(audioCtx.currentTime, musical.hz, musical.env, musical.spin)
  }
  const sectionIndex: Record<string, number> = {
    intro: 0, theme: 1, chorus: 2, development: 3, coda: 4,
  }
  const turn = sectionIndex[musical.section] ?? 0
  const angle = reduceMotion
    ? turn * (Math.PI / 5) + ((musical.hz || 0) / 1056) * 0.45
    : vizAngle
  ctx.setTransform(dpr, 0, 0, dpr, 0, 0)
  drawViz(
    ctx,
    canvas.clientWidth,
    canvas.clientHeight,
    angle,
    reduceMotion ? (musical.hz ? 1 : 0) : musical.env,
    reduceMotion ? 0 : strokePhase,
    theme.theme === 'dark',
    !reduceMotion && phase.value !== 'land',
    musical.section,
  )
}

function vizFrame() {
  vizRaf = window.requestAnimationFrame(vizFrame)
  paintViz(true)
}

function startVizLoop() {
  if (reduceMotion || vizRaf) return
  lastAudioTime = -1
  vizRaf = window.requestAnimationFrame(vizFrame)
}

function stopVizLoop() {
  if (!vizRaf) return
  window.cancelAnimationFrame(vizRaf)
  vizRaf = 0
}

function onMotionChange() {
  reduceMotion = !!motionQuery?.matches
  if (reduceMotion) stopVizLoop()
  else if (phase.value === 'hold' || phase.value === 'leaving') startVizLoop()
  paintViz(false)
}

onMounted(() => {
  theme.init()
  motionQuery = window.matchMedia('(prefers-reduced-motion: reduce)')
  reduceMotion = motionQuery.matches
  motionQuery.addEventListener('change', onMotionChange)
  nextTick(() => {
    const canvas = vizEl.value
    if (!canvas) return
    resizeObserver = new ResizeObserver(() => paintViz(false))
    resizeObserver.observe(canvas)
    paintViz(false)
  })
})

watch(() => theme.theme, () => paintViz(false))
watch(sounding, () => {
  if (reduceMotion) paintViz(false)
})
watch(sectionName, () => {
  if (reduceMotion) paintViz(false)
})

onBeforeUnmount(() => {
  generation += 1
  motionQuery?.removeEventListener('change', onMotionChange)
  resizeObserver?.disconnect()
  resizeObserver = null
  teardown()
  if (audioCtx && audioCtx.state !== 'closed') {
    void audioCtx.close().catch(() => {})
  }
  audioCtx = null
})
</script>

<template>
  <div class="sf" :data-phase="phase" :data-section="sectionName" :data-sf-theme="theme.theme">
    <canvas ref="vizEl" class="sf__viz" aria-hidden="true" />
    <NuxtLink
      to="/engage"
      class="sf__iconbtn sf__back"
      aria-label="Back to Engage"
    >
      <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M15 6 9 12l6 6" /></svg>
    </NuxtLink>

    <button
      type="button"
      class="sf__iconbtn sf__theme"
      :aria-label="`Switch to ${theme.theme === 'dark' ? 'light' : 'dark'} mode`"
      @click.stop.prevent="onThemeToggle"
    >
      <EdSignalIcon :name="theme.theme === 'dark' ? 'sun' : 'moon'" />
    </button>

    <div v-if="phase === 'land'" class="sf__land">
      <p class="sf__eyebrow sf__anim" style="--i:0">Solfeggio</p>
      <h1 class="sf__title sf__anim" style="--i:1">Soul of the Universe</h1>
      <p class="sf__lede sf__anim" style="--i:2">One piece on nine pitches.</p>
      <button
        class="sf__cta sf__anim sf__cta--pulse"
        style="--i:3"
        type="button"
        @click="begin"
      >
        {{ playedOnce ? 'Again' : 'Begin' }}
      </button>
      <p class="sf__fine">A listening piece built from a modern pitch list, not a medical device and not a therapy.</p>
    </div>

    <div v-else class="sf__hold" :class="{ 'sf__hold--leaving': phase === 'leaving' }">
      <p class="sf__section" aria-live="polite">{{ sectionLabel }}</p>
      <p class="sf__hz" aria-live="polite">
        <span class="sf__hz-num">{{ sounding || '—' }}</span><span v-if="sounding" class="sf__hz-unit"> Hz</span>
      </p>
      <p class="sf__hint">Headphones</p>
      <button
        class="sf__leave"
        type="button"
        :disabled="phase === 'leaving'"
        @click="leave"
      >
        Leave
      </button>
      <p class="sf__fine">A listening piece built from a modern pitch list, not a medical device and not a therapy.</p>
    </div>
  </div>
</template>

<style scoped>

.sf {
  --sf-paper: #fbf8ef;
  --sf-ink: #161618;
  --sf-cobalt: #2F5BD8;
  --sf-yellow: #ffd43b;
  --ink: var(--sf-ink);
  --accent: var(--sf-yellow);
  position: relative;
  width: 100%;
  height: 100svh;
  height: 100dvh;
  max-height: 100dvh;
  background: var(--sf-paper);
  color: var(--sf-ink);
  overflow: hidden;
  touch-action: manipulation;
  user-select: none;
  -webkit-user-select: none;
  -webkit-tap-highlight-color: transparent;
  transition: background 280ms ease, color 280ms ease;
}

.sf[data-sf-theme='dark'] {
  --sf-paper: #121214;
  --sf-ink: #ede6d6;
  --sf-yellow: #e8c547;
}

.sf__iconbtn {
  position: absolute;
  z-index: 20;
  top: max(10rem, env(safe-area-inset-top));
  width: 44rem;
  height: 44rem;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  padding: 0;
  border: none;
  border-radius: 999px;
  background: color-mix(in srgb, var(--sf-paper) 55%, transparent);
  color: color-mix(in srgb, var(--sf-ink) 70%, transparent);
  text-decoration: none;
  cursor: pointer;
  appearance: none;
  backdrop-filter: blur(6px);
  -webkit-backdrop-filter: blur(6px);
  transition: color 160ms ease, background 160ms ease, transform 120ms ease;
}
.sf__iconbtn:hover,
.sf__iconbtn:focus-visible {
  color: var(--sf-ink);
  background: color-mix(in srgb, var(--sf-paper) 82%, transparent);
}
.sf__iconbtn:focus-visible {
  outline: 2rem solid var(--sf-yellow);
  outline-offset: 2rem;
}
.sf__iconbtn:active { transform: scale(0.94); }

.sf__back { left: max(10rem, env(safe-area-inset-left)); }
.sf__back svg {
  width: 20rem;
  height: 20rem;
  fill: none;
  stroke: currentColor;
  stroke-width: 2.25;
  stroke-linecap: round;
  stroke-linejoin: round;
}

.sf__theme { right: max(10rem, env(safe-area-inset-right)); }
.sf__theme :deep(svg) {
  width: 18rem;
  height: 18rem;
  fill: none;
  stroke: currentColor;
  stroke-width: 1.75;
  stroke-linecap: round;
  stroke-linejoin: round;
}

.sf__viz {
  position: absolute;
  inset: 0;
  z-index: 0;
  width: 100%;
  height: 100%;
  display: block;
  pointer-events: none;
}

.sf__land,
.sf__hold {
  position: absolute;
  z-index: 1;
  inset: 0;
  display: grid;
  align-content: center;
  justify-items: center;
  gap: 12rem;
  padding: 28rem 24rem;
  padding-top: max(72rem, calc(env(safe-area-inset-top) + 56rem));
  padding-bottom: max(72rem, calc(env(safe-area-inset-bottom) + 56rem));
  text-align: center;
}

.sf__eyebrow {
  margin: 0;
  font: 800 11rem/1 var(--font-mono);
  letter-spacing: 0.22em;
  text-transform: uppercase;
  opacity: 0.72;
}

.sf__title {
  margin: 0;
  font: 700 clamp(52rem, 14vw, 104rem)/0.86 var(--font-display);
  letter-spacing: -0.06em;
  text-wrap: balance;
  text-shadow: 0 0 18rem var(--sf-paper), 0 0 6rem var(--sf-paper);
}

.sf__lede {
  margin: 0 0 6rem;
  font-size: 15rem;
  line-height: 1.4;
  max-width: 28ch;
  letter-spacing: 0.01em;
  opacity: 0.82;
}

.sf__cta {
  appearance: none;
  border: none;
  background: var(--sf-yellow);
  color: #161618;
  font: 800 15rem/1 var(--font-mono);
  letter-spacing: 0.16em;
  text-transform: uppercase;
  min-height: 44rem;
  padding: 18rem 36rem;
  border-radius: 999px;
  cursor: pointer;
  box-shadow:
    0 1rem 0 color-mix(in srgb, #161618 12%, transparent),
    0 8rem 20rem color-mix(in srgb, var(--sf-ink) 10%, transparent);
  transition: transform 160ms ease, box-shadow 160ms ease;
}
.sf__cta:hover,
.sf__cta:focus-visible { transform: translateY(-1rem); }
.sf__cta:focus-visible {
  outline: 2rem solid var(--sf-ink);
  outline-offset: 3rem;
}
.sf__cta:active {
  transform: translateY(2rem) scale(0.98);
  box-shadow:
    0 0 0 transparent,
    0 2rem 8rem color-mix(in srgb, var(--sf-ink) 8%, transparent);
}

.sf__anim {
  animation: sf-rise 480ms cubic-bezier(0.22, 1, 0.36, 1) both;
  animation-delay: calc(var(--i, 0) * 65ms + 30ms);
}

.sf__cta--pulse {
  animation:
    sf-rise 480ms cubic-bezier(0.22, 1, 0.36, 1) both,
    sf-cta-pulse 2.6s ease-in-out 650ms infinite;
  animation-delay: calc(var(--i, 0) * 65ms + 30ms), 650ms;
}

.sf__section {
  margin: 0;
  min-height: 13rem;
  font: 800 13rem/1 var(--font-mono);
  letter-spacing: 0.22em;
  text-transform: uppercase;
  opacity: 0.78;
}
.sf[data-section='chorus'] .sf__section {
  color: var(--sf-cobalt);
  opacity: 1;
}

.sf__hz {
  margin: 4rem 0 0;
  font: 700 clamp(56rem, 16vw, 96rem)/0.86 var(--font-display);
  letter-spacing: -0.06em;
  font-variant-numeric: tabular-nums;
  text-shadow: 0 0 16rem var(--sf-paper), 0 0 4rem var(--sf-paper);
}
.sf__hz-unit {
  font: 700 18rem/1 var(--font-mono);
  letter-spacing: 0.08em;
  opacity: 0.55;
}

.sf__hint {
  margin: 0;
  font: 700 11rem/1 var(--font-mono);
  letter-spacing: 0.18em;
  text-transform: uppercase;
  opacity: 0.42;
}

.sf__leave {
  appearance: none;
  min-width: 44rem;
  min-height: 44rem;
  margin-top: 4rem;
  padding: 12rem 22rem;
  border: none;
  border-radius: 999px;
  background: transparent;
  color: color-mix(in srgb, var(--sf-ink) 70%, transparent);
  font: 800 12rem/1 var(--font-mono);
  letter-spacing: 0.16em;
  text-transform: uppercase;
  cursor: pointer;
}
.sf__leave:hover,
.sf__leave:focus-visible { color: var(--sf-ink); }
.sf__leave:focus-visible {
  outline: 2rem solid var(--sf-yellow);
  outline-offset: 3rem;
}
.sf__leave:disabled {
  cursor: default;
  opacity: 0.45;
}

.sf__hold--leaving .sf__hz {
  opacity: 0.35;
  transition: opacity 2s linear;
}

.sf__fine {
  position: absolute;
  left: max(20rem, env(safe-area-inset-left));
  right: max(20rem, env(safe-area-inset-right));
  bottom: max(14rem, env(safe-area-inset-bottom));
  margin: 0;
  font-size: 11rem;
  line-height: 1.35;
  letter-spacing: 0.01em;
  opacity: 0.42;
}

@keyframes sf-rise {
  from { opacity: 0; transform: translateY(12rem); }
  to { opacity: 1; transform: none; }
}
@keyframes sf-cta-pulse {
  0%, 100% { transform: scale(1); }
  50% { transform: scale(1.025); }
}
@media (prefers-reduced-motion: reduce) {
  .sf,
  .sf__anim,
  .sf__cta--pulse,
  .sf__hold--leaving .sf__hz {
    animation: none !important;
    transition: none !important;
  }
  .sf__anim,
  .sf__cta--pulse { opacity: 1; transform: none; }
}
</style>
