<script setup lang="ts">
definePageMeta({ layout: false })
/**
 * Solfeggio — one tap, a full song on nine pitches.
 * The score is utils/solfeggio-compose.mjs, generated by scripts/solfeggio-compose.py.
 * Web Audio only. The pitch list is a modern numerological set, not a therapy.
 */
import { useThemeStore } from '~/stores/theme'
import { composeSong } from '~/utils/solfeggio-compose.mjs'
import {
  PHI,
  phiRingRadii,
  pentagonVertices,
  goldenRectangleCorners,
} from '~/utils/solfeggio-math.mjs'

useSeoMeta({
  title: 'Solfeggio · Engage',
  description: 'A full song from nine pitches.',
  ogUrl: 'https://entertrainer.in/engage/solfeggio',
})

const MASTER_GAIN = 0.16
const LEAVE_FADE = 1.5
const FLOOR = 0.0008

type Phase = 'land' | 'hold' | 'leaving'
type ScoreEvent = { bar: number, beat: number, durBeats: number, hz: number, voice: string, gain: number }
type Section = { name: string, bar: number, bars: number }
type Song = {
  seed: number
  bpm: number
  meter: string
  totalBars: number
  duration: number
  centerHz: number
  sections: Section[]
  events: ScoreEvent[]
}
type LiveNote = { start: number, sources: AudioScheduledSourceNode[], nodes: AudioNode[] }
type DrawProfile = {
  rings: number
  stars: number[]
  rect: boolean
  spin: number
  rot: number
  twin: number
  scale: number
  accent: string
}

const SECTION_LABEL: Record<string, string> = {
  intro: 'Intro',
  verse: 'Verse',
  chorus: 'Chorus',
  bridge: 'Bridge',
  outro: 'Outro',
}

const theme = useThemeStore()
const phase = ref<Phase>('land')
const sounding = ref(0)
const playedOnce = ref(false)
const sectionName = ref('')
const sectionLabel = computed(() => SECTION_LABEL[sectionName.value] || '')
const vizEl = ref<HTMLCanvasElement | null>(null)

let currentSong: Song | null = null
let pieceOrigin = 0
let vizRaf = 0
let vizAngle = 0
let strokePhase = 0
let lastAudioTime = -1
let reduceMotion = false
let motionQuery: MediaQueryList | null = null
let resizeObserver: ResizeObserver | null = null

let audioCtx: AudioContext | null = null
let graphNodes: AudioNode[] = []
let master: GainNode | null = null
let drumBus: GainNode | null = null
let musicBus: GainNode | null = null
let noiseBuf: AudioBuffer | null = null
let live: LiveNote[] = []
let generation = 0
let leaveTimer = 0
let tickTimer = 0

function audioContextCtor(): typeof AudioContext | null {
  if (typeof window === 'undefined') return null
  const w = window as Window & { webkitAudioContext?: typeof AudioContext }
  return window.AudioContext || w.webkitAudioContext || null
}

function ensureContext() {
  const AC = audioContextCtor()
  if (!AC) return null
  if (!audioCtx || audioCtx.state === 'closed') audioCtx = new AC()
  if (audioCtx.state === 'suspended') void audioCtx.resume()
  return audioCtx
}

function clearTimers() {
  if (leaveTimer) window.clearTimeout(leaveTimer)
  if (tickTimer) window.clearTimeout(tickTimer)
  leaveTimer = 0
  tickTimer = 0
}

function stopLive(when = 0) {
  for (const note of live) {
    const at = Math.max(when, note.start)
    for (const source of note.sources) {
      try { source.stop(at) } catch { /* already stopped, or not started */ }
    }
    for (const node of note.nodes) {
      try { node.disconnect() } catch { /* already disconnected */ }
    }
  }
  live = []
}

function disconnectGraph() {
  for (const node of graphNodes) {
    try { node.disconnect() } catch { /* already disconnected */ }
  }
  graphNodes = []
  master = null
  drumBus = null
  musicBus = null
}

function teardown() {
  clearTimers()
  stopVizLoop()
  stopLive(audioCtx ? audioCtx.currentTime : 0)
  disconnectGraph()
  currentSong = null
  pieceOrigin = 0
  lastAudioTime = -1
  sectionName.value = ''
  sounding.value = 0
}

function connectPan(ctx: AudioContext, source: AudioNode, dest: AudioNode, pan: number, when: number) {
  if (typeof ctx.createStereoPanner !== 'function') {
    source.connect(dest)
    return [] as AudioNode[]
  }
  const panner = ctx.createStereoPanner()
  panner.pan.setValueAtTime(pan, when)
  source.connect(panner)
  panner.connect(dest)
  return [panner]
}

function noiseBuffer(ctx: AudioContext) {
  if (noiseBuf && noiseBuf.sampleRate === ctx.sampleRate) return noiseBuf
  const n = Math.max(1, Math.floor(ctx.sampleRate * 0.25))
  const buf = ctx.createBuffer(1, n, ctx.sampleRate)
  const data = buf.getChannelData(0)
  let s = 0x6d2b79f5
  for (let i = 0; i < n; i++) {
    s = (Math.imul(s, 1664525) + 1013904223) | 0
    data[i] = ((s >>> 0) / 4294967296) * 2 - 1
  }
  noiseBuf = buf
  return buf
}

function beatLength(song: Song) {
  return 60 / song.bpm
}

function eventWhen(song: Song, event: ScoreEvent) {
  return (event.bar * 4 + event.beat) * beatLength(song)
}

function eventLength(song: Song, event: ScoreEvent) {
  return event.durBeats * beatLength(song)
}

function spawnKick(ctx: AudioContext, dest: AudioNode, event: ScoreEvent, when: number) {
  const peak = Math.max(event.gain, FLOOR)
  const stopAt = when + 0.08
  const gain = ctx.createGain()
  gain.gain.setValueAtTime(FLOOR, when)
  gain.gain.exponentialRampToValueAtTime(peak, when + 0.004)
  gain.gain.exponentialRampToValueAtTime(FLOOR, stopAt)

  const osc = ctx.createOscillator()
  osc.type = 'sine'
  osc.frequency.setValueAtTime(event.hz, when)
  osc.frequency.exponentialRampToValueAtTime(Math.max(40, event.hz * 0.7), stopAt)
  osc.connect(gain)

  const noise = ctx.createBufferSource()
  noise.buffer = noiseBuffer(ctx)
  const filter = ctx.createBiquadFilter()
  filter.type = 'lowpass'
  filter.frequency.setValueAtTime(200, when)
  filter.Q.setValueAtTime(0.7, when)
  const nGain = ctx.createGain()
  nGain.gain.setValueAtTime(peak * 0.7, when)
  nGain.gain.exponentialRampToValueAtTime(FLOOR, when + 0.028)
  noise.connect(filter)
  filter.connect(nGain)
  nGain.connect(gain)

  const panners = connectPan(ctx, gain, dest, 0, when)
  osc.start(when)
  noise.start(when)
  osc.stop(stopAt + 0.02)
  noise.stop(when + 0.04)
  live.push({
    start: when,
    sources: [osc, noise],
    nodes: [osc, noise, filter, nGain, gain, ...panners],
  })
}

function spawnSnare(ctx: AudioContext, dest: AudioNode, event: ScoreEvent, when: number) {
  const peak = Math.max(event.gain, FLOOR)
  const stopAt = when + 0.12
  const gain = ctx.createGain()
  gain.gain.setValueAtTime(FLOOR, when)
  gain.gain.exponentialRampToValueAtTime(peak, when + 0.003)
  gain.gain.exponentialRampToValueAtTime(FLOOR, stopAt)

  const noise = ctx.createBufferSource()
  noise.buffer = noiseBuffer(ctx)
  const filter = ctx.createBiquadFilter()
  filter.type = 'bandpass'
  filter.frequency.setValueAtTime(1800, when)
  filter.Q.setValueAtTime(0.7, when)
  noise.connect(filter)
  filter.connect(gain)

  const osc = ctx.createOscillator()
  osc.type = 'triangle'
  osc.frequency.setValueAtTime(event.hz, when)
  const body = ctx.createGain()
  body.gain.setValueAtTime(peak * 0.28, when)
  body.gain.exponentialRampToValueAtTime(FLOOR, when + 0.045)
  osc.connect(body)
  body.connect(gain)

  const panners = connectPan(ctx, gain, dest, 0.03, when)
  noise.start(when)
  osc.start(when)
  noise.stop(stopAt + 0.02)
  osc.stop(when + 0.06)
  live.push({
    start: when,
    sources: [noise, osc],
    nodes: [noise, osc, filter, body, gain, ...panners],
  })
}

function spawnHat(ctx: AudioContext, dest: AudioNode, event: ScoreEvent, when: number, open: boolean) {
  const peak = Math.max(event.gain, FLOOR)
  const stopAt = when + (open ? 0.09 : 0.04)
  const gain = ctx.createGain()
  gain.gain.setValueAtTime(FLOOR, when)
  gain.gain.exponentialRampToValueAtTime(peak, when + 0.002)
  gain.gain.exponentialRampToValueAtTime(FLOOR, stopAt)

  const noise = ctx.createBufferSource()
  noise.buffer = noiseBuffer(ctx)
  const filter = ctx.createBiquadFilter()
  filter.type = 'highpass'
  filter.frequency.setValueAtTime(open ? 4800 : 7000, when)
  filter.Q.setValueAtTime(0.7, when)
  noise.connect(filter)
  filter.connect(gain)

  const panners = connectPan(ctx, gain, dest, open ? 0.2 : -0.14, when)
  noise.start(when)
  noise.stop(stopAt + 0.02)
  live.push({
    start: when,
    sources: [noise],
    nodes: [noise, filter, gain, ...panners],
  })
}

function spawnTone(
  ctx: AudioContext,
  dest: AudioNode,
  event: ScoreEvent,
  when: number,
  dur: number,
  kind: 'bass' | 'chord' | 'lead',
) {
  const peak = Math.max(event.gain, FLOOR)
  const attack = kind === 'lead' ? 0.012 : kind === 'bass' ? 0.016 : 0.028
  const release = kind === 'lead' ? 0.055 : kind === 'bass' ? 0.07 : 0.09
  const stopAt = when + Math.max(dur, attack + 0.02)
  const end = stopAt + release
  const gain = ctx.createGain()
  gain.gain.setValueAtTime(FLOOR, when)
  gain.gain.exponentialRampToValueAtTime(peak, when + attack)
  gain.gain.setValueAtTime(peak, Math.max(when + attack, stopAt))
  gain.gain.exponentialRampToValueAtTime(FLOOR, end)

  const filter = ctx.createBiquadFilter()
  filter.type = 'lowpass'
  filter.frequency.setValueAtTime(kind === 'lead' ? 3800 : kind === 'bass' ? 320 : 1600, when)
  filter.Q.setValueAtTime(0.45, when)
  filter.connect(gain)

  const osc = ctx.createOscillator()
  osc.type = kind === 'chord' ? 'sine' : 'triangle'
  osc.frequency.setValueAtTime(event.hz, when)
  osc.connect(filter)

  const pan = kind === 'lead' ? 0.06 : kind === 'bass' ? -0.1 : (event.hz >= 528 ? 0.12 : -0.06)
  const panners = connectPan(ctx, gain, dest, pan, when)
  osc.start(when)
  osc.stop(end + 0.02)
  live.push({
    start: when,
    sources: [osc],
    nodes: [osc, filter, gain, ...panners],
  })
}

function scheduleSong(ctx: AudioContext, song: Song, origin: number) {
  if (!drumBus || !musicBus) return
  for (const event of song.events) {
    const when = origin + eventWhen(song, event)
    if (when < ctx.currentTime - 0.02) continue
    if (event.voice === 'kick') spawnKick(ctx, drumBus, event, when)
    else if (event.voice === 'snare') spawnSnare(ctx, drumBus, event, when)
    else if (event.voice === 'hat') spawnHat(ctx, drumBus, event, when, false)
    else if (event.voice === 'openhat') spawnHat(ctx, drumBus, event, when, true)
    else if (event.voice === 'bass') spawnTone(ctx, musicBus, event, when, eventLength(song, event), 'bass')
    else if (event.voice === 'chord') spawnTone(ctx, musicBus, event, when, eventLength(song, event), 'chord')
    else if (event.voice === 'lead') spawnTone(ctx, musicBus, event, when, eventLength(song, event), 'lead')
  }
}

function buildGraph(ctx: AudioContext) {
  const t = ctx.currentTime
  const drums = ctx.createGain()
  const music = ctx.createGain()
  drums.gain.setValueAtTime(1, t)
  music.gain.setValueAtTime(1, t)
  const out = ctx.createGain()
  out.gain.cancelScheduledValues(t)
  out.gain.setValueAtTime(FLOOR, t)
  out.gain.exponentialRampToValueAtTime(MASTER_GAIN, t + 0.05)
  drums.connect(out)
  music.connect(out)
  out.connect(ctx.destination)
  drumBus = drums
  musicBus = music
  master = out
  graphNodes = [drums, music, out]
}

function sectionAt(song: Song, bar: number) {
  const clamped = Math.min(song.totalBars - 1, Math.max(0, Math.floor(bar)))
  for (const section of song.sections) {
    if (clamped >= section.bar && clamped < section.bar + section.bars) return section.name
  }
  return 'outro'
}

function leadHzAt(song: Song, beat: number) {
  let hz = 0
  for (const event of song.events) {
    if (event.voice !== 'lead') continue
    const start = event.bar * 4 + event.beat
    if (start > beat + 0.0001) break
    hz = event.hz
  }
  return hz
}

function runSong(gen: number, song: Song, origin: number) {
  const step = () => {
    if (gen !== generation || !audioCtx || !currentSong) return
    if (phase.value === 'land') return
    const now = audioCtx.currentTime - origin
    const beat = now / beatLength(song)
    sectionName.value = sectionAt(song, beat / 4)
    sounding.value = leadHzAt(song, beat)
    if (phase.value === 'hold' && now >= song.duration + 0.14) {
      finishLeave(gen)
      return
    }
    tickTimer = window.setTimeout(step, 100)
  }
  step()
}

function begin() {
  if (phase.value !== 'land') return
  const gen = ++generation
  clearTimers()
  stopLive(audioCtx ? audioCtx.currentTime : 0)
  disconnectGraph()

  const ctx = ensureContext()
  if (!ctx) return

  const seed = (Math.random() * 0x100000000) >>> 0
  const song = composeSong(seed) as Song
  const origin = ctx.currentTime + 0.06
  buildGraph(ctx)
  scheduleSong(ctx, song, origin)
  phase.value = 'hold'
  playedOnce.value = true
  currentSong = song
  pieceOrigin = origin
  vizAngle = 0
  strokePhase = 0
  lastAudioTime = -1
  sectionName.value = 'intro'
  sounding.value = 0
  runSong(gen, song, origin)
  startVizLoop()
  paintViz(false)
}

function finishLeave(gen: number) {
  if (gen !== generation) return
  teardown()
  vizAngle = 0
  strokePhase = 0
  phase.value = 'land'
  paintViz(false)
}

function leave() {
  if (phase.value !== 'hold' || !audioCtx || !master) return
  const gen = generation
  phase.value = 'leaving'
  const t = audioCtx.currentTime
  const current = Math.max(master.gain.value, FLOOR)
  master.gain.cancelScheduledValues(t)
  master.gain.setValueAtTime(current, t)
  master.gain.exponentialRampToValueAtTime(FLOOR, t + LEAVE_FADE)
  if (leaveTimer) window.clearTimeout(leaveTimer)
  leaveTimer = window.setTimeout(() => {
    if (audioCtx) stopLive(audioCtx.currentTime)
    finishLeave(gen)
  }, LEAVE_FADE * 1000 + 40)
}

function onThemeToggle(e: Event) {
  e.stopPropagation()
  e.preventDefault()
  theme.toggle()
}

function profileFor(section: string): DrawProfile {
  if (section === 'chorus') {
    return { rings: 8, stars: [3, 5, 7], rect: true, spin: 1.85, rot: -Math.PI / 2, twin: Math.PI / 5, scale: 1.14, accent: 'chorus' }
  }
  if (section === 'verse') {
    return { rings: 6, stars: [2, 4], rect: true, spin: 0.85, rot: -Math.PI / 2, twin: 0, scale: 1, accent: 'verse' }
  }
  if (section === 'bridge') {
    return { rings: 7, stars: [2, 5], rect: false, spin: -1.25, rot: -Math.PI / 2 + Math.PI / 5, twin: Math.PI / 5, scale: 1.04, accent: 'bridge' }
  }
  if (section === 'outro') {
    return { rings: 5, stars: [3], rect: true, spin: 0.42, rot: -Math.PI / 2, twin: 0, scale: 0.9, accent: 'outro' }
  }
  return { rings: 4, stars: [2], rect: false, spin: 0.36, rot: -Math.PI / 2, twin: 0, scale: 0.82, accent: 'intro' }
}

function musicalNow(audioTime: number) {
  if (!currentSong || phase.value === 'land') {
    return { section: 'intro', hz: 0, env: 0, spin: 0.36 }
  }
  const beat = (audioTime - pieceOrigin) / beatLength(currentSong)
  const section = sectionAt(currentSong, beat / 4)
  let hz = 0
  let active = false
  for (const event of currentSong.events) {
    const start = event.bar * 4 + event.beat
    if (start > beat + 0.0001) break
    if (event.voice !== 'lead') continue
    hz = event.hz
    active = beat < start + event.durBeats
  }
  const env = active ? 1 : section === 'chorus' ? 0.62 : 0.3
  return { section, hz, env, spin: profileFor(section).spin }
}

function advanceViz(audioTime: number, hz: number, env: number, spin: number) {
  if (lastAudioTime < 0) {
    lastAudioTime = audioTime
    return
  }
  const dt = Math.min(0.1, Math.max(0, audioTime - lastAudioTime))
  lastAudioTime = audioTime
  const pitch = hz > 0 ? hz : 528
  const omega = (pitch / 528) * ((Math.PI * 2) / 28)
  const dir = spin < 0 ? -1 : 1
  vizAngle += dt * omega * Math.abs(spin) * dir * (0.35 + 0.65 * env)
  strokePhase += dt * pitch * 0.02 * (0.3 + 0.7 * env)
}

function fitViz(canvas: HTMLCanvasElement) {
  const dpr = Math.min(window.devicePixelRatio || 1, 2)
  const w = Math.max(1, canvas.clientWidth)
  const h = Math.max(1, canvas.clientHeight)
  const pw = Math.round(w * dpr)
  const ph = Math.round(h * dpr)
  if (canvas.width !== pw || canvas.height !== ph) {
    canvas.width = pw
    canvas.height = ph
  }
  return dpr
}

function drawStar(
  ctx: CanvasRenderingContext2D,
  radius: number,
  rotation: number,
  env: number,
  ink: string,
  star: string,
  dash: number,
  motion: boolean,
  inkStroke: boolean,
) {
  const verts = pentagonVertices(radius, rotation)
  ctx.beginPath()
  verts.forEach((v, i) => (i === 0 ? ctx.moveTo(v.x, v.y) : ctx.lineTo(v.x, v.y)))
  ctx.closePath()
  ctx.setLineDash([])
  ctx.strokeStyle = ink
  ctx.globalAlpha = inkStroke ? 0.72 : 0.4
  ctx.lineWidth = 1.2
  ctx.stroke()

  ctx.beginPath()
  for (let i = 0; i <= 5; i++) {
    const v = verts[(i * 2) % 5]
    if (i === 0) ctx.moveTo(v.x, v.y)
    else ctx.lineTo(v.x, v.y)
  }
  ctx.strokeStyle = star
  ctx.globalAlpha = 0.45 + 0.5 * env
  ctx.lineWidth = 1.35
  if (motion) {
    ctx.setLineDash([5, 8])
    ctx.lineDashOffset = -dash
  } else {
    ctx.setLineDash([])
  }
  ctx.stroke()
  ctx.setLineDash([])
}

function drawViz(
  ctx: CanvasRenderingContext2D,
  width: number,
  height: number,
  angle: number,
  env: number,
  dash: number,
  dark: boolean,
  motion: boolean,
  section: string,
) {
  const paper = dark ? '#121214' : '#fbf8ef'
  const ink = dark ? '#ede6d6' : '#161618'
  const cobalt = '#2F5BD8'
  const profile = profileFor(section)
  const star = profile.accent === 'chorus' ? (dark ? '#e8c547' : '#c8960a') : cobalt
  ctx.fillStyle = paper
  ctx.fillRect(0, 0, width, height)

  const minSide = Math.min(width, height)
  const count = profile.rings
  const outer = minSide * 0.46 * profile.scale * (0.94 + 0.06 * env)
  const radii = phiRingRadii(count, outer / (PHI ** (count - 1)))
  const cx = width / 2
  const cy = height / 2

  ctx.save()
  ctx.translate(cx, cy)
  ctx.rotate(angle)
  ctx.lineJoin = 'miter'
  ctx.lineCap = 'butt'

  for (let i = 0; i < radii.length; i++) {
    ctx.beginPath()
    ctx.arc(0, 0, radii[i], 0, Math.PI * 2)
    ctx.strokeStyle = i % 2 === 0 ? ink : star
    ctx.globalAlpha = 0.22 + 0.38 * (i / Math.max(1, count - 1))
    ctx.lineWidth = i === count - 1 ? 1.4 : 1
    ctx.stroke()
  }

  for (const index of profile.stars) {
    const radius = radii[Math.min(index, radii.length - 1)]
    drawStar(ctx, radius, profile.rot, env, ink, star, dash, motion, index === profile.stars[profile.stars.length - 1])
    if (profile.twin) {
      drawStar(ctx, radius * 0.72, profile.rot + profile.twin, env, ink, star, dash, false, false)
    }
  }

  if (profile.rect) {
    const rect = goldenRectangleCorners(radii[Math.min(2, radii.length - 1)] * 2)
    ctx.beginPath()
    rect.forEach((c, i) => (i === 0 ? ctx.moveTo(c.x, c.y) : ctx.lineTo(c.x, c.y)))
    ctx.closePath()
    ctx.setLineDash([])
    ctx.strokeStyle = profile.accent === 'chorus' ? star : ink
    ctx.globalAlpha = 0.78
    ctx.lineWidth = profile.accent === 'chorus' ? 1.8 : 1.25
    ctx.stroke()
  }

  ctx.restore()
  ctx.globalAlpha = 1
}

function paintViz(advanceClock: boolean) {
  const canvas = vizEl.value
  if (!canvas) return
  const dpr = fitViz(canvas)
  const ctx = canvas.getContext('2d')
  if (!ctx) return
  const musical = audioCtx && currentSong ? musicalNow(audioCtx.currentTime) : musicalNow(0)
  if (advanceClock && audioCtx && currentSong && !reduceMotion && phase.value !== 'land') {
    advanceViz(audioCtx.currentTime, musical.hz, musical.env, musical.spin)
  }
  const sectionIndex: Record<string, number> = {
    intro: 0, verse: 1, chorus: 2, bridge: 3, outro: 4,
  }
  const turn = sectionIndex[musical.section] ?? 0
  const angle = reduceMotion
    ? turn * (Math.PI / 5) + ((musical.hz || 0) / 1056) * 0.45
    : vizAngle
  ctx.setTransform(dpr, 0, 0, dpr, 0, 0)
  drawViz(
    ctx,
    canvas.clientWidth,
    canvas.clientHeight,
    angle,
    reduceMotion ? (musical.hz ? 1 : 0) : musical.env,
    reduceMotion ? 0 : strokePhase,
    theme.theme === 'dark',
    !reduceMotion && phase.value !== 'land',
    musical.section,
  )
}

function vizFrame() {
  vizRaf = window.requestAnimationFrame(vizFrame)
  paintViz(true)
}

function startVizLoop() {
  if (reduceMotion || vizRaf) return
  lastAudioTime = -1
  vizRaf = window.requestAnimationFrame(vizFrame)
}

function stopVizLoop() {
  if (!vizRaf) return
  window.cancelAnimationFrame(vizRaf)
  vizRaf = 0
}

function onMotionChange() {
  reduceMotion = !!motionQuery?.matches
  if (reduceMotion) stopVizLoop()
  else if (phase.value === 'hold' || phase.value === 'leaving') startVizLoop()
  paintViz(false)
}

onMounted(() => {
  theme.init()
  motionQuery = window.matchMedia('(prefers-reduced-motion: reduce)')
  reduceMotion = motionQuery.matches
  motionQuery.addEventListener('change', onMotionChange)
  nextTick(() => {
    const canvas = vizEl.value
    if (!canvas) return
    resizeObserver = new ResizeObserver(() => paintViz(false))
    resizeObserver.observe(canvas)
    paintViz(false)
  })
})

watch(() => theme.theme, () => paintViz(false))
watch(sounding, () => {
  if (reduceMotion) paintViz(false)
})
watch(sectionName, () => {
  if (reduceMotion) paintViz(false)
})

onBeforeUnmount(() => {
  generation += 1
  motionQuery?.removeEventListener('change', onMotionChange)
  resizeObserver?.disconnect()
  resizeObserver = null
  teardown()
  if (audioCtx && audioCtx.state !== 'closed') {
    void audioCtx.close().catch(() => {})
  }
  audioCtx = null
})
</script>

<template>
  <div class="sf" :data-phase="phase" :data-section="sectionName" :data-sf-theme="theme.theme">
    <canvas ref="vizEl" class="sf__viz" aria-hidden="true" />
    <NuxtLink
      to="/engage"
      class="sf__iconbtn sf__back"
      aria-label="Back to Engage"
    >
      <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M15 6 9 12l6 6" /></svg>
    </NuxtLink>

    <button
      type="button"
      class="sf__iconbtn sf__theme"
      :aria-label="`Switch to ${theme.theme === 'dark' ? 'light' : 'dark'} mode`"
      @click.stop.prevent="onThemeToggle"
    >
      <EdSignalIcon :name="theme.theme === 'dark' ? 'sun' : 'moon'" />
    </button>

    <div v-if="phase === 'land'" class="sf__land">
      <p class="sf__eyebrow sf__anim" style="--i:0">Engage</p>
      <h1 class="sf__title sf__anim" style="--i:1">Solfeggio</h1>
      <p class="sf__lede sf__anim" style="--i:2">A full song from nine pitches.</p>
      <button
        class="sf__cta sf__anim sf__cta--pulse"
        style="--i:3"
        type="button"
        @click="begin"
      >
        {{ playedOnce ? 'Again' : 'Begin' }}
      </button>
      <p class="sf__fine">A listening piece built from a modern pitch list, not a medical device and not a therapy.</p>
    </div>

    <div v-else class="sf__hold" :class="{ 'sf__hold--leaving': phase === 'leaving' }">
      <p class="sf__section" aria-live="polite">{{ sectionLabel }}</p>
      <p class="sf__hz" aria-live="polite">
        <span class="sf__hz-num">{{ sounding || '—' }}</span><span v-if="sounding" class="sf__hz-unit"> Hz</span>
      </p>
      <p class="sf__hint">Headphones</p>
      <button
        class="sf__leave"
        type="button"
        :disabled="phase === 'leaving'"
        @click="leave"
      >
        Leave
      </button>
      <p class="sf__fine">A listening piece built from a modern pitch list, not a medical device and not a therapy.</p>
    </div>
  </div>
</template>

<style scoped>

.sf {
  --sf-paper: #fbf8ef;
  --sf-ink: #161618;
  --sf-cobalt: #2F5BD8;
  --sf-yellow: #ffd43b;
  --ink: var(--sf-ink);
  --accent: var(--sf-yellow);
  position: relative;
  width: 100%;
  height: 100svh;
  height: 100dvh;
  max-height: 100dvh;
  background: var(--sf-paper);
  color: var(--sf-ink);
  overflow: hidden;
  touch-action: manipulation;
  user-select: none;
  -webkit-user-select: none;
  -webkit-tap-highlight-color: transparent;
  transition: background 280ms ease, color 280ms ease;
}

.sf[data-sf-theme='dark'] {
  --sf-paper: #121214;
  --sf-ink: #ede6d6;
  --sf-yellow: #e8c547;
}

.sf__iconbtn {
  position: absolute;
  z-index: 20;
  top: max(10rem, env(safe-area-inset-top));
  width: 44rem;
  height: 44rem;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  padding: 0;
  border: none;
  border-radius: 999px;
  background: color-mix(in srgb, var(--sf-paper) 55%, transparent);
  color: color-mix(in srgb, var(--sf-ink) 70%, transparent);
  text-decoration: none;
  cursor: pointer;
  appearance: none;
  backdrop-filter: blur(6px);
  -webkit-backdrop-filter: blur(6px);
  transition: color 160ms ease, background 160ms ease, transform 120ms ease;
}
.sf__iconbtn:hover,
.sf__iconbtn:focus-visible {
  color: var(--sf-ink);
  background: color-mix(in srgb, var(--sf-paper) 82%, transparent);
}
.sf__iconbtn:focus-visible {
  outline: 2rem solid var(--sf-yellow);
  outline-offset: 2rem;
}
.sf__iconbtn:active { transform: scale(0.94); }

.sf__back { left: max(10rem, env(safe-area-inset-left)); }
.sf__back svg {
  width: 20rem;
  height: 20rem;
  fill: none;
  stroke: currentColor;
  stroke-width: 2.25;
  stroke-linecap: round;
  stroke-linejoin: round;
}

.sf__theme { right: max(10rem, env(safe-area-inset-right)); }
.sf__theme :deep(svg) {
  width: 18rem;
  height: 18rem;
  fill: none;
  stroke: currentColor;
  stroke-width: 1.75;
  stroke-linecap: round;
  stroke-linejoin: round;
}

.sf__viz {
  position: absolute;
  inset: 0;
  z-index: 0;
  width: 100%;
  height: 100%;
  display: block;
  pointer-events: none;
}

.sf__land,
.sf__hold {
  position: absolute;
  z-index: 1;
  inset: 0;
  display: grid;
  align-content: center;
  justify-items: center;
  gap: 12rem;
  padding: 28rem 24rem;
  padding-top: max(72rem, calc(env(safe-area-inset-top) + 56rem));
  padding-bottom: max(72rem, calc(env(safe-area-inset-bottom) + 56rem));
  text-align: center;
}

.sf__eyebrow {
  margin: 0;
  font: 800 11rem/1 var(--font-mono);
  letter-spacing: 0.22em;
  text-transform: uppercase;
  opacity: 0.72;
}

.sf__title {
  margin: 0;
  font: 700 clamp(52rem, 14vw, 104rem)/0.86 var(--font-display);
  letter-spacing: -0.06em;
  text-wrap: balance;
  text-shadow: 0 0 18rem var(--sf-paper), 0 0 6rem var(--sf-paper);
}

.sf__lede {
  margin: 0 0 6rem;
  font-size: 15rem;
  line-height: 1.4;
  max-width: 28ch;
  letter-spacing: 0.01em;
  opacity: 0.82;
}

.sf__cta {
  appearance: none;
  border: none;
  background: var(--sf-yellow);
  color: #161618;
  font: 800 15rem/1 var(--font-mono);
  letter-spacing: 0.16em;
  text-transform: uppercase;
  min-height: 44rem;
  padding: 18rem 36rem;
  border-radius: 999px;
  cursor: pointer;
  box-shadow:
    0 1rem 0 color-mix(in srgb, #161618 12%, transparent),
    0 8rem 20rem color-mix(in srgb, var(--sf-ink) 10%, transparent);
  transition: transform 160ms ease, box-shadow 160ms ease;
}
.sf__cta:hover,
.sf__cta:focus-visible { transform: translateY(-1rem); }
.sf__cta:focus-visible {
  outline: 2rem solid var(--sf-ink);
  outline-offset: 3rem;
}
.sf__cta:active {
  transform: translateY(2rem) scale(0.98);
  box-shadow:
    0 0 0 transparent,
    0 2rem 8rem color-mix(in srgb, var(--sf-ink) 8%, transparent);
}

.sf__anim {
  animation: sf-rise 480ms cubic-bezier(0.22, 1, 0.36, 1) both;
  animation-delay: calc(var(--i, 0) * 65ms + 30ms);
}

.sf__cta--pulse {
  animation:
    sf-rise 480ms cubic-bezier(0.22, 1, 0.36, 1) both,
    sf-cta-pulse 2.6s ease-in-out 650ms infinite;
  animation-delay: calc(var(--i, 0) * 65ms + 30ms), 650ms;
}

.sf__section {
  margin: 0;
  min-height: 13rem;
  font: 800 13rem/1 var(--font-mono);
  letter-spacing: 0.22em;
  text-transform: uppercase;
  opacity: 0.78;
}
.sf[data-section='chorus'] .sf__section {
  color: var(--sf-cobalt);
  opacity: 1;
}

.sf__hz {
  margin: 4rem 0 0;
  font: 700 clamp(56rem, 16vw, 96rem)/0.86 var(--font-display);
  letter-spacing: -0.06em;
  font-variant-numeric: tabular-nums;
  text-shadow: 0 0 16rem var(--sf-paper), 0 0 4rem var(--sf-paper);
}
.sf__hz-unit {
  font: 700 18rem/1 var(--font-mono);
  letter-spacing: 0.08em;
  opacity: 0.55;
}

.sf__hint {
  margin: 0;
  font: 700 11rem/1 var(--font-mono);
  letter-spacing: 0.18em;
  text-transform: uppercase;
  opacity: 0.42;
}

.sf__leave {
  appearance: none;
  min-width: 44rem;
  min-height: 44rem;
  margin-top: 4rem;
  padding: 12rem 22rem;
  border: none;
  border-radius: 999px;
  background: transparent;
  color: color-mix(in srgb, var(--sf-ink) 70%, transparent);
  font: 800 12rem/1 var(--font-mono);
  letter-spacing: 0.16em;
  text-transform: uppercase;
  cursor: pointer;
}
.sf__leave:hover,
.sf__leave:focus-visible { color: var(--sf-ink); }
.sf__leave:focus-visible {
  outline: 2rem solid var(--sf-yellow);
  outline-offset: 3rem;
}
.sf__leave:disabled {
  cursor: default;
  opacity: 0.45;
}

.sf__hold--leaving .sf__hz {
  opacity: 0.35;
  transition: opacity 2s linear;
}

.sf__fine {
  position: absolute;
  left: max(20rem, env(safe-area-inset-left));
  right: max(20rem, env(safe-area-inset-right));
  bottom: max(14rem, env(safe-area-inset-bottom));
  margin: 0;
  font-size: 11rem;
  line-height: 1.35;
  letter-spacing: 0.01em;
  opacity: 0.42;
}

@keyframes sf-rise {
  from { opacity: 0; transform: translateY(12rem); }
  to { opacity: 1; transform: none; }
}
@keyframes sf-cta-pulse {
  0%, 100% { transform: scale(1); }
  50% { transform: scale(1.025); }
}
@media (prefers-reduced-motion: reduce) {
  .sf,
  .sf__anim,
  .sf__cta--pulse,
  .sf__hold--leaving .sf__hz {
    animation: none !important;
    transition: none !important;
  }
  .sf__anim,
  .sf__cta--pulse { opacity: 1; transform: none; }
}
</style>
