/**
 * Generated by scripts/solfeggio-compose.py — do not edit by hand.
 * Python is the generator. The cent values and the phrase tables below are
 * baked from that run. composePiece is the same integer score as the script:
 * same seed, same events. This is a listening piece from a modern pitch list,
 * not a therapy.
 *
 * 528/396 and 852/639 are exactly 4/3.
 * 963/639 is 8.1088394103703649 cents sharp of 3/2.
 */

export const CENTER_HZ = 528
// Unique names so Nuxt auto-import does not collide with utils/solfeggio-math.mjs.
export const PIECE_FOURTH_CENTS = 498.04499913461251
export const PIECE_FIFTH_CENTS = 701.95500086538743
export const PIECE_NEAR_FIFTH_CENTS = 710.0638402757578
export const PIECE_NEAR_FIFTH_SHARP_CENTS = 8.1088394103703649

const PULSE_MS = Object.freeze([1200, 1280, 1360, 1440, 1520, 1600])
const MOTIFS = Object.freeze([[[396, 4, 1], [417, 2, 2], [528, 6, 0], [396, 4, 2], [528, 8, 0]], [[417, 3, 1], [396, 4, 2], [528, 6, 1], [639, 3, 2], [417, 2, 1], [528, 8, 0]], [[396, 6, 2], [528, 4, 1], [417, 3, 2], [528, 8, 0]], [[528, 4, 1], [417, 2, 1], [396, 4, 2], [417, 3, 1], [528, 8, 0]], [[396, 4, 2], [417, 2, 1], [396, 3, 2], [417, 4, 1], [528, 8, 0]]])
const VARIATIONS = Object.freeze([[[417, 3, 2], [396, 4, 1], [639, 3, 2], [528, 8, 0]], [[417, 2, 2], [528, 4, 1], [396, 4, 2], [528, 6, 0]], [[396, 4, 1], [417, 2, 2], [639, 3, 2], [528, 8, 0]]])
const B_PHRASES = Object.freeze([[[639, 4, 1], [741, 2, 1], [852, 6, 2], [963, 3, 2], [852, 4, 1], [639, 8, 0]], [[852, 4, 1], [741, 2, 1], [639, 4, 2], [741, 2, 1], [852, 6, 2], [963, 3, 1], [852, 8, 0]], [[639, 6, 2], [741, 2, 1], [852, 4, 2], [963, 3, 2], [741, 2, 1], [852, 8, 0]]])
const CADENCES = Object.freeze([[[417, 3, 2], [396, 4, 3], [528, 12, 0]], [[396, 4, 2], [417, 3, 2], [528, 14, 0]], [[417, 2, 2], [396, 3, 3], [417, 3, 2], [528, 12, 0]]])
const GAINS = Object.freeze({
  "foundation": 400,
  "chordLow": 200,
  "chordHigh": 160,
  "chordOct": 120,
  "melody": 340,
  "pulse": 150,
  "fadeFoundation": 220,
  "fadeCenter": 170,
  "cadenceLow": 180,
  "cadenceHigh": 240
})

function toGain(milli) {
  return milli / 1000
}

function makeRng(seed) {
  let a = seed >>> 0
  function nextU32() {
    a = (a + 0x6D2B79F5) | 0
    let t = Math.imul(a ^ (a >>> 15), 1 | a)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return (t ^ (t >>> 14)) >>> 0
  }
  return {
    below(n) {
      return nextU32() % n
    },
  }
}

function phraseMs(phrase, step) {
  let total = 0
  for (let i = 0; i < phrase.length; i++) total += (phrase[i][1] + phrase[i][2]) * step
  return total
}

function decorate(phrase, lift) {
  const out = []
  for (let i = 0; i < phrase.length; i++) {
    const hz = lift && phrase[i][0] === 528 ? 1056 : phrase[i][0]
    out.push([hz, phrase[i][1], phrase[i][2]])
  }
  return out
}

function tickOn(i, pattern) {
  if (pattern === 0) return i % 4 !== 3
  if (pattern === 1) return i % 5 !== 4
  return i % 4 === 0 || i % 4 === 2
}

function octDown(hz) {
  return hz / 2
}

/**
 * @param {number} seed
 * @returns {{
 *   seed: number,
 *   centerHz: number,
 *   foundationHz: number,
 *   pulseMs: number,
 *   duration: number,
 *   motif: number[],
 *   sections: { name: string, t: number, dur: number }[],
 *   events: { t: number, dur: number, hz: number, voice: string, gain: number }[],
 * }}
 */
export function composePiece(seed) {
  const seed32 = seed >>> 0
  const rng = makeRng(seed32)
  const pulse = PULSE_MS[rng.below(PULSE_MS.length)]
  const foundation = rng.below(2) === 0 ? 174 : 285
  const motif = decorate(MOTIFS[rng.below(MOTIFS.length)], rng.below(2) === 1)
  const variation = VARIATIONS[rng.below(VARIATIONS.length)]
  const bPhrase = B_PHRASES[rng.below(B_PHRASES.length)]
  const cadence = CADENCES[rng.below(CADENCES.length)]
  const pattern = rng.below(3)
  let introMs = (8 + rng.below(4)) * pulse
  let aGap = (2 + rng.below(2)) * pulse
  const fadePulses = 6 + rng.below(3)
  const target = 104000 + rng.below(21000)

  const step = Math.floor(pulse / 4)
  const aLead = pulse
  const aTail = 2 * pulse
  let aMs = aLead + phraseMs(motif, step) + aGap + phraseMs(variation, step) + aTail
  const bLead = pulse
  let bTail = 2 * pulse
  let bMs = bLead + phraseMs(bPhrase, step) + bTail
  const rLead = pulse
  let rTail = 2 * pulse
  let rMs = rLead + phraseMs(motif, step) + rTail
  const cTail = pulse
  const cMs = phraseMs(cadence, step) + cTail
  let fMs = fadePulses * pulse
  let totalMs = introMs + aMs + bMs + rMs + cMs + fMs

  let guard = 0
  while (totalMs < target && totalMs + pulse <= 136000 && guard < 80) {
    const which = guard % 5
    if (which === 0) introMs += pulse
    else if (which === 1) {
      aGap += pulse
      aMs += pulse
    } else if (which === 2) {
      bTail += pulse
      bMs += pulse
    } else if (which === 3) {
      rTail += pulse
      rMs += pulse
    } else {
      fMs += pulse
    }
    totalMs += pulse
    guard += 1
  }

  const specs = [
    ['intro', introMs],
    ['A', aMs],
    ['B', bMs],
    ['return', rMs],
    ['cadence', cMs],
    ['fade', fMs],
  ]
  const sections = []
  const sec = {}
  let cursor = 0
  for (let i = 0; i < specs.length; i++) {
    const name = specs[i][0]
    const dur = specs[i][1]
    sections.push({ name, t: cursor, dur })
    sec[name] = [cursor, cursor + dur]
    cursor += dur
  }
  const durationMs = cursor
  const events = []

  function add(t, dur, hz, voice, milli) {
    if (dur < 50 || t < 0 || t >= durationMs) return
    let length = dur
    if (t + length > durationMs) length = durationMs - t
    if (length < 50) return
    events.push({
      t: t | 0,
      dur: length | 0,
      hz,
      voice,
      gain: milli | 0,
    })
  }

  function layBed(t0, t1, hz, voice, milli, hold, overlap) {
    if (t1 - t0 < 80) return
    let t = t0
    while (t < t1) {
      const dur = t + hold <= t1 ? hold : t1 - t
      if (dur >= 50) add(t, dur, hz, voice, milli)
      if (t + hold >= t1) break
      const advance = hold - overlap
      if (advance <= 0) break
      t += advance
    }
  }

  function place(phrase, start) {
    let t = start
    for (let i = 0; i < phrase.length; i++) {
      const dur = phrase[i][1] * step
      add(t, dur, phrase[i][0], 'melody', GAINS.melody)
      t += dur + phrase[i][2] * step
    }
  }

  const fadeT = sec.fade[0]
  const fadeEnd = sec.fade[1]
  layBed(
    0,
    Math.min(durationMs, fadeT + Math.floor(pulse / 2)),
    foundation,
    'foundation',
    GAINS.foundation,
    6 * pulse,
    pulse,
  )
  add(fadeT, fadeEnd - fadeT, foundation, 'foundation', GAINS.fadeFoundation)
  add(fadeT, fadeEnd - fadeT, CENTER_HZ, 'chord', GAINS.fadeCenter)

  function layChord(name, low, high) {
    const t0 = sec[name][0]
    const t1 = sec[name][1]
    const breath = Math.min(Math.floor(pulse / 2), Math.floor((t1 - t0) / 5))
    const end = t1 - breath
    layBed(t0, end, low, 'chord', GAINS.chordLow, 4 * pulse, pulse)
    layBed(t0 + pulse, end, high, 'chord', GAINS.chordHigh, 4 * pulse, pulse)
    layBed(t0, end, octDown(low), 'chord', GAINS.chordOct, 5 * pulse, pulse)
  }

  layChord('A', 396, 528)
  layChord('B', 639, 852)
  layChord('return', 396, 528)

  const ct0 = sec.cadence[0]
  const ct1 = sec.cadence[1]
  const half = Math.floor((ct1 - ct0) / 2)
  add(ct0, half, 396, 'chord', GAINS.cadenceLow)
  add(ct0, ct1 - ct0, CENTER_HZ, 'chord', GAINS.cadenceHigh)

  const at0 = sec.A[0]
  place(motif, at0 + aLead)
  place(variation, at0 + aLead + phraseMs(motif, step) + aGap)
  const bt0 = sec.B[0]
  place(bPhrase, bt0 + bLead)
  const rt0 = sec.return[0]
  place(motif, rt0 + rLead)
  place(cadence, ct0)

  let tick = 0
  let pulseAt = 0
  while (pulseAt < fadeT) {
    if (tickOn(tick, pattern)) add(pulseAt, 70, foundation, 'pulse', GAINS.pulse)
    tick += 1
    pulseAt += pulse
  }

  events.sort((a, b) => (
    a.t - b.t
    || (a.voice < b.voice ? -1 : a.voice > b.voice ? 1 : 0)
    || a.hz - b.hz
    || a.dur - b.dur
    || a.gain - b.gain
  ))

  const seconds = (ms) => ms / 1000
  return {
    seed: seed32,
    centerHz: CENTER_HZ,
    foundationHz: foundation,
    pulseMs: pulse,
    duration: seconds(durationMs),
    motif: motif.map((note) => note[0]),
    sections: sections.map((section) => ({
      name: section.name,
      t: seconds(section.t),
      dur: seconds(section.dur),
    })),
    events: events.map((event) => ({
      t: seconds(event.t),
      dur: seconds(event.dur),
      hz: event.hz,
      voice: event.voice,
      gain: toGain(event.gain),
    })),
  }
}
