/**
 * Generated by scripts/solfeggio-compose.py — do not edit by hand.
 * Soul of the Universe. One arrangement, nine pitches, 4-bar sentences.
 * Same seed, same score. Not a therapy.
 *
 * 528/396 and 852/639 are exactly 4/3.
 * 963/639 is 8.1088394103703649 cents sharp of 3/2.
 */

export const CENTER_HZ = 528
export const PIECE_FOURTH_CENTS = 498.04499913461251
export const PIECE_FIFTH_CENTS = 701.95500086538743
export const PIECE_NEAR_FIFTH_CENTS = 710.0638402757578
export const PIECE_NEAR_FIFTH_SHARP_CENTS = 8.1088394103703649
export const TITLE = 'Soul of the Universe'

const LEAD = Object.freeze([528, 570, 639, 741, 792, 852, 963, 1056])
const GAINS = Object.freeze({"kick": 320, "snare": 240, "hat": 64, "808": 360, "cowbell": 72, "tablaBayan": 200, "tablaDayan": 140, "mridangam": 160, "tanpura": 120, "pad": 56, "choir": 48, "bass": 280, "acid": 150, "cello": 100, "piano": 64, "guitar": 80, "pluck": 88, "oud": 72, "koto": 64, "harp": 70, "supersaw": 140, "sitar": 150, "violin": 80, "veena": 84, "bansuri": 64, "dizi": 56, "erhu": 60, "trumpet": 72, "saxophone": 64, "clarinet": 52, "shakuhachi": 60, "bells": 56})
const TONES = Object.freeze({"528": [528, 639, 792], "396": [396, 528, 639], "639": [639, 792, 963], "852": [852, 1056, 639], "741": [741, 852, 963]})
const SCALE_REG = Object.freeze([348, 396, 417, 528, 570, 639, 696, 741, 792, 834, 852, 963, 1056, 1140, 1278, 1392])
const ROOTS = Object.freeze([528, 396, 639, 528, 528, 396, 639, 528, 528, 396, 639, 528, 396, 852, 639, 528, 396, 852, 639, 528, 528, 639, 741, 528, 528, 639, 741, 528, 396, 852, 639, 528, 396, 852, 639, 528, 639, 741, 852, 528, 741, 639, 396, 528, 396, 852, 639, 528, 396, 852, 639, 528, 639, 396, 528, 528])
const GRIDS = Object.freeze({"intro": [[4, 4, 3, 3, 2, 2, 1, 1], [2, 2, 1, 1, 0, 1, 2, 2], [2, 2, 1, 1, 0, 0, 1, 1], [0, 0, 0, 0, 0, 0, 0, 0]], "theme": [[4, 4, 3, 3, 2, 2, 1, 1], [2, 2, 1, 1, 0, 1, 2, 2], [2, 2, 3, 3, 2, 2, 1, 1], [1, 1, 0, 0, 0, 0, 0, 0], [4, 4, 3, 3, 2, 2, 3, 3], [4, 4, 3, 3, 2, 2, 1, 1], [1, 1, 2, 2, 1, 1, 0, 0], [1, 1, 0, 0, 0, 0, 0, 0]], "chorus": [[4, 4, 5, 5, 4, 4, 3, 3], [2, 2, 3, 3, 2, 2, 1, 1], [1, 1, 2, 2, 1, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [4, 4, 5, 5, 4, 4, 3, 3], [2, 2, 3, 3, 2, 2, 1, 1], [1, 1, 2, 2, 1, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]], "development": [[4, 4, 3, 3, 3, 3, 2, 2], [2, 2, 1, 1, 1, 1, 2, 2], [2, 3, 2, 1, 1, 0, 1, 0], [0, 0, 0, 0, 0, 0, 0, 0], [6, 6, 5, 5, 5, 5, 4, 4], [4, 4, 3, 3, 3, 3, 2, 2], [2, 1, 0, 1, 2, 1, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]], "coda": [[2, 2, 1, 1, 0, 1, 2, 2], [1, 0, 1, 2, 1, 0, 1, 2], [1, 1, 0, 0, 1, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]], "themeVar": [[[5, 5, 4, 4, 3, 3, 2, 2], [3, 3, 2, 2, 1, 2, 3, 3], [3, 3, 4, 4, 3, 3, 2, 2], [2, 2, 1, 1, 0, 0, 0, 0], [5, 5, 4, 4, 3, 3, 4, 4], [5, 5, 4, 4, 3, 3, 2, 2], [2, 2, 3, 3, 2, 2, 1, 1], [2, 2, 1, 1, 0, 0, 0, 0]], [[4, 3, 4, 3, 3, 2, 3, 2], [2, 1, 2, 1, 1, 0, 1, 2], [2, 3, 2, 1, 1, 0, 1, 0], [0, 0, 0, 0, 0, 0, 0, 0], [4, 3, 4, 5, 4, 3, 2, 3], [4, 3, 2, 1, 2, 1, 0, 1], [1, 2, 1, 0, 1, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]]]})

function makeRng(seed) {
  let a = seed >>> 0
  function nextU32() {
    a = (a + 0x6D2B79F5) | 0
    let t = Math.imul(a ^ (a >>> 15), 1 | a)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return (t ^ (t >>> 14)) >>> 0
  }
  return {
    below(n) {
      return nextU32() % n
    },
  }
}

function scaleIndex(hz) {
  for (let i = 0; i < SCALE_REG.length; i++) {
    if (Math.abs(SCALE_REG[i] - hz) < 1e-6) return i
  }
  throw new Error('hz ' + hz)
}

function octavesBetween(base, lo, hi) {
  let hz = base
  while (hz < lo) hz *= 2
  const out = []
  while (hz <= hi + 1e-9) {
    out.push(hz)
    hz *= 2
  }
  return out
}

function candidates(root) {
  const tones = TONES[String(root)]
  const found = []
  for (let i = 0; i < tones.length; i++) {
    const extra = octavesBetween(tones[i], 360, 1200)
    for (let k = 0; k < extra.length; k++) found.push(extra[k])
  }
  found.sort((a, b) => a - b)
  const uniq = []
  for (let i = 0; i < found.length; i++) {
    if (!uniq.length || Math.abs(found[i] - uniq[uniq.length - 1]) > 1e-6) uniq.push(found[i])
  }
  return uniq
}

function cmpKey(a, b) {
  for (let i = 0; i < a.length; i++) {
    if (a[i] < b[i]) return -1
    if (a[i] > b[i]) return 1
  }
  return 0
}

function voiceLead(prev, cands) {
  const prevS = prev.slice().sort((a, b) => a - b)
  let best = null
  let bestKey = null
  for (let i = 0; i < cands.length; i++) {
    for (let j = i + 1; j < cands.length; j++) {
      for (let k = j + 1; k < cands.length; k++) {
        const ordered = [cands[i], cands[j], cands[k]].sort((a, b) => a - b)
        const dists = [
          Math.abs(scaleIndex(ordered[0]) - scaleIndex(prevS[0])),
          Math.abs(scaleIndex(ordered[1]) - scaleIndex(prevS[1])),
          Math.abs(scaleIndex(ordered[2]) - scaleIndex(prevS[2])),
        ]
        const key = [dists[0] + dists[1] + dists[2], dists[0], dists[1], dists[2], ordered[0], ordered[1], ordered[2]]
        if (bestKey === null || cmpKey(key, bestKey) < 0) {
          bestKey = key
          best = ordered
        }
      }
    }
  }
  return best
}

function bassHz(root) {
  let hz = root
  while (hz > 300) hz /= 2
  while (hz < 90) hz *= 2
  return hz
}

function acidHz(root) {
  let hz = bassHz(root) * 2
  if (hz > 400) hz = bassHz(root)
  return hz
}

function breath(name, rel) {
  if (name === 'intro' && rel === 0) return true
  if (name === 'development' && rel % 4 === 2) return true
  if (name === 'coda' && rel === 3) return true
  return false
}

function fill(name, rel) {
  if (breath(name, rel) || name === 'coda') return false
  return rel % 4 === 3
}

/**
 * @param {number} seed
 */
export function composeSong(seed) {
  const seed32 = seed >>> 0
  const rng = makeRng(seed32)
  const bpm = 78 + rng.below(23)
  const variation = rng.below(2)
  const plan = [
    ['intro', 4],
    ['theme', 8],
    ['chorus', 8],
    ['theme', 8],
    ['chorus', 8],
    ['development', 8],
    ['chorus', 8],
    ['coda', 4],
  ]
  const sections = []
  let bar = 0
  for (let i = 0; i < plan.length; i++) {
    sections.push({ name: plan[i][0], bar, bars: plan[i][1] })
    bar += plan[i][1]
  }
  const totalBars = bar
  const events = []

  function add(at, beat, dur, hz, voice, slide) {
    events.push({
      bar: at,
      beat,
      durBeats: dur,
      hz,
      voice,
      gain: GAINS[voice] / 1000,
      slide: slide || 0,
    })
  }

  function layTokens(start, tokens, voice) {
    let k = 0
    while (k < 8) {
      let j = k + 1
      while (j < 8 && tokens[j] === tokens[k]) j += 1
      add(start, k * 0.5, (j - k) * 0.5, LEAD[tokens[k]], voice, 0)
      k = j
    }
  }

  let voicing = voiceLead([528, 741, 963], candidates(ROOTS[0]))
  let prevRoot = null
  let themePass = 0
  for (let s = 0; s < sections.length; s++) {
    const section = sections[s]
    let grid
    if (section.name === 'theme') {
      grid = themePass === 1 ? GRIDS.themeVar[variation] : GRIDS.theme
      themePass += 1
    } else {
      grid = GRIDS[section.name]
    }
    for (let rel = 0; rel < section.bars; rel++) {
      const at = section.bar + rel
      const root = ROOTS[at]
      if (at > 0) voicing = voiceLead(voicing, candidates(root))
      const low = voicing[0]
      const mid = voicing[1]
      const high = voicing[2]
      const bhz = bassHz(root)
      const ahz = acidHz(root)
      const slide = prevRoot === null || prevRoot === root ? 0 : 1
      prevRoot = root
      add(at, 0, 4, 264, 'tanpura', 0)
      add(at, 0, 4, 198, 'tanpura', 0)
      const tones = [low, mid, high]
      for (let v = 0; v < tones.length; v++) {
        add(at, 0, 4, tones[v], 'pad', 0)
        add(at, 0, 4, tones[v], 'choir', 0)
        add(at, 0, 4, tones[v], 'piano', 0)
      }
      add(at, 0, 4, mid, 'erhu', 0)
      add(at, 0, 4, bhz, 'cello', 0)
      add(at, 0, 2, low, 'oud', 0)
      add(at, 0, 3, high, 'saxophone', 0)
      add(at, 1, 2, mid, 'clarinet', 0)
      add(at, 0, 0.5, root >= 396 ? root : root * 2, 'trumpet', 0)
      for (const beat of [0, 2]) {
        add(at, beat, 1, bhz, 'bass', 0)
        for (let v = 0; v < tones.length; v++) add(at, beat, 0.5, tones[v], 'guitar', 0)
      }
      for (const beat of [0.5, 2.5]) {
        for (let v = 0; v < tones.length; v++) add(at, beat, 0.5, tones[v], 'pluck', 0)
      }
      add(at, 1, 0.5, high, 'koto', 0)
      add(at, 3, 0.5, high, 'koto', 0)
      add(at, 0, 1.5, ahz, 'acid', slide)
      add(at, 2, 0.5, ahz, 'acid', 0)
      add(at, 2.5, 0.5, ahz, 'acid', 0)
      add(at, 3.5, 0.5, ahz, 'acid', 0)
      if (rel % 4 === 0) {
        add(at, 0, 1.5, low, 'harp', 0)
        add(at, 0.5, 1.5, mid, 'harp', 0)
        add(at, 1, 2, high, 'harp', 0)
        add(at, 0, 1.5, 1056, 'bells', 0)
      }
      if (rel % 4 === 3) {
        add(at, 2, 2, 528, 'shakuhachi', 0)
        add(at, 2, 2, 1056, 'bells', 0)
      }
      const row = grid[rel]
      if (rel % 4 < 2) {
        layTokens(at, row, 'supersaw')
        layTokens(at, row, 'violin')
        layTokens(at, row, 'bansuri')
      } else {
        layTokens(at, row, 'sitar')
        layTokens(at, row, 'veena')
        layTokens(at, row, 'dizi')
      }
      if (breath(section.name, rel)) continue
      if (fill(section.name, rel)) {
        add(at, 0, 0.5, 87, 'kick', 0)
        add(at, 0, 0.5, 87, '808', 0)
        add(at, 2, 0.5, 87, 'kick', 0)
        add(at, 2, 0.5, 87, '808', 0)
        for (const beat of [2, 2.5, 3, 3.5]) add(at, beat, 0.25, 174, 'snare', 0)
        for (const beat of [0, 0.5, 1, 1.5]) add(at, beat, 0.5, 4560, 'hat', 0)
        add(at, 0.5, 0.5, 741, 'cowbell', 0)
        add(at, 0, 0.5, 87, 'tablaBayan', 0)
        add(at, 1.5, 0.25, 528, 'tablaDayan', 0)
        add(at, 0, 0.5, 174, 'mridangam', 0)
        continue
      }
      for (const beat of [0, 2]) {
        add(at, beat, 0.5, 87, 'kick', 0)
        add(at, beat, 0.5, 87, '808', 0)
      }
      for (const beat of [1, 3]) add(at, beat, 0.5, 174, 'snare', 0)
      for (const beat of [0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5]) add(at, beat, 0.5, 4560, 'hat', 0)
      for (const beat of [0.5, 2, 2.5, 3.5]) add(at, beat, 0.25, 741, 'cowbell', 0)
      add(at, 0, 0.5, 87, 'tablaBayan', 0)
      add(at, 1.5, 0.25, 528, 'tablaDayan', 0)
      add(at, 3, 0.25, 528, 'tablaDayan', 0)
      add(at, 0, 0.5, 174, 'mridangam', 0)
      add(at, 2.5, 0.25, 285, 'mridangam', 0)
    }
  }

  events.sort((a, b) => (
    a.bar - b.bar
    || a.beat - b.beat
    || (a.voice < b.voice ? -1 : a.voice > b.voice ? 1 : 0)
    || a.hz - b.hz
    || a.durBeats - b.durBeats
    || a.gain - b.gain
    || a.slide - b.slide
  ))

  return {
    seed: seed32,
    title: TITLE,
    bpm,
    meter: '4/4',
    pocket: 'backbeat',
    variation,
    totalBars,
    duration: totalBars * 4 * 60 / bpm,
    centerHz: CENTER_HZ,
    sections,
    events,
  }
}
