/**
 * Pulls DM Sans and Fraunces down from Google Fonts and writes them into
 * `public/fonts/` with a local `assets/css/fonts.css` to match.
 *
 * The site used to link the Google stylesheet directly, which costs a DNS
 * lookup, a TLS handshake and a CSS round trip on two extra origins before any
 * text can be shaped — and until it lands, every heading renders in Georgia and
 * then reflows. Self-hosting removes the third-party hop and the reflow, and it
 * keeps the site rendering as designed on a network that cannot reach Google.
 *
 * Only the `src` URLs change: the `@font-face` blocks keep Google's own
 * `unicode-range` subsetting, so a browser still downloads only the subsets the
 * page actually uses (~226 KB for latin, not the full 792 KB on disk).
 *
 * Re-run when the axes in FONTS_URL change:  node scripts/fetch-fonts.mjs
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const OUT_DIR = resolve(ROOT, 'public/fonts')
const CSS_OUT = resolve(ROOT, 'assets/css/fonts.css')

// Fraunces carries its SOFT and WONK axes here. WONK swaps in the quirky
// alternates (single-storey g, curled y) and SOFT rounds the terminals — the two
// things that stop a variable serif reading as a stock system serif. They are
// applied via font-variation-settings on display headings only.
const FONTS_URL = 'https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,100..900;1,9..40,100..900&family=Fraunces:ital,opsz,wght,SOFT,WONK@0,9..144,300..700,0..100,0..1;1,9..144,300..700,0..100,0..1&display=swap'

// Without a modern desktop UA the API serves ttf instead of woff2.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

const css = await (await fetch(FONTS_URL, { headers: { 'User-Agent': UA } })).text()
if (!css.includes('@font-face')) throw new Error('Google Fonts returned no @font-face blocks')

mkdirSync(OUT_DIR, { recursive: true })

const urls = [...new Set(css.match(/https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2/g) ?? [])]
if (!urls.length) throw new Error('no woff2 URLs in the stylesheet')

let total = 0
const local = new Map()
for (const url of urls) {
  // `s/fraunces/v38/6NUT….woff2` -> `fraunces-v38-6NUT….woff2`, so the file name
  // still says which family and version it came from.
  const parts = url.split('/s/')[1].split('/')
  const name = `${parts[0]}-${parts[1]}-${parts[2]}`
  const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer())
  writeFileSync(resolve(OUT_DIR, name), buf)
  local.set(url, `/fonts/${name}`)
  total += buf.length
  console.log(`${String(buf.length).padStart(7)}  ${name}`)
}

const header = `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.
   Source: ${FONTS_URL}
   Google's own unicode-range subsetting is preserved, so a browser still fetches
   only the subsets a page uses. */\n\n`

let out = css
for (const [remote, path] of local) out = out.split(remote).join(path)
writeFileSync(CSS_OUT, header + out.trim() + '\n')

console.log(`\n${urls.length} files, ${(total / 1024).toFixed(0)} KB -> public/fonts/`)
console.log(`stylesheet -> ${CSS_OUT.replace(ROOT + '/', '')}`)
