/**
 * Pulls DM Sans and Fraunces down from Google Fonts and writes them into
 * `public/fonts/` with a local `assets/css/fonts.css` to match.
 *
 * The site used to link the Google stylesheet directly, which costs a DNS
 * lookup, a TLS handshake and a CSS round trip on two extra origins before any
 * text can be shaped — and until it lands, every heading renders in Georgia and
 * then reflows. Self-hosting removes the third-party hop and the reflow, and it
 * keeps the site rendering as designed on a network that cannot reach Google.
 *
 * Only the `src` URLs change: the `@font-face` blocks keep Google's own
 * `unicode-range` subsetting, so a browser still downloads only the subsets the
 * page actually uses (~226 KB for latin, not the full 792 KB on disk).
 *
 * Re-run when the axes in FONTS_URL change:  node scripts/fetch-fonts.mjs
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const OUT_DIR = resolve(ROOT, 'public/fonts')

const REQUESTS = [
  {
    // The site's own two faces, loaded on every page. Fraunces carries its SOFT
    // and WONK axes here: WONK swaps in the quirky alternates (single-storey g,
    // curled y) and SOFT rounds the terminals — the two things that stop a
    // variable serif reading as a stock system serif. They are applied via
    // font-variation-settings on display headings only.
    out: 'assets/css/fonts.css',
    url: 'https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,100..900;1,9..40,100..900&family=Fraunces:ital,opsz,wght,SOFT,WONK@0,9..144,300..700,0..100,0..1;1,9..144,300..700,0..100,0..1&display=swap'
  },
  {
    // /my-work/strong is a lesson with its own typographic world — a geometric
    // display face, a UI sans and a mono. It is still a page on this site, so it
    // gets the same treatment rather than its own third-party stylesheet.
    out: 'assets/css/fonts-strong.css',
    url: 'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&family=Inter:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500;600&display=swap'
  }
]

// Without a modern desktop UA the API serves ttf instead of woff2.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

mkdirSync(OUT_DIR, { recursive: true })
let grandTotal = 0
for (const req of REQUESTS) grandTotal += await localise(req)
console.log(`\n${(grandTotal / 1024).toFixed(0)} KB on disk in public/fonts/`)

async function localise({ url: FONTS_URL, out }) {
const CSS_OUT = resolve(ROOT, out)
const css = await (await fetch(FONTS_URL, { headers: { 'User-Agent': UA } })).text()
if (!css.includes('@font-face')) throw new Error('Google Fonts returned no @font-face blocks')

const urls = [...new Set(css.match(/https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2/g) ?? [])]
if (!urls.length) throw new Error('no woff2 URLs in the stylesheet')

let total = 0
const local = new Map()
for (const url of urls) {
  // `s/fraunces/v38/6NUT….woff2` -> `fraunces-v38-6NUT….woff2`, so the file name
  // still says which family and version it came from.
  const parts = url.split('/s/')[1].split('/')
  const name = `${parts[0]}-${parts[1]}-${parts[2]}`
  const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer())
  writeFileSync(resolve(OUT_DIR, name), buf)
  local.set(url, `/fonts/${name}`)
  total += buf.length
  console.log(`${String(buf.length).padStart(7)}  ${name}`)
}

const header = `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.
   Source: ${FONTS_URL}
   Google's own unicode-range subsetting is preserved, so a browser still fetches
   only the subsets a page uses. */\n\n`

let sheet = css
for (const [remote, path] of local) sheet = sheet.split(remote).join(path)
writeFileSync(CSS_OUT, header + sheet.trim() + '\n')

console.log(`${urls.length} files -> ${out}\n`)
return total
}
