import assert from 'node:assert/strict'
import { createServer } from 'node:http'
import { readFile } from 'node:fs/promises'
import { resolve, extname } from 'node:path'
import { chromium } from 'playwright-core'
import serverlessChromium from '@sparticuz/chromium'
// Static game runtime test. Nuxt route compilation is verified by the production build.
const root = resolve('public')
const server = createServer(async (req, res) => {
  try {
    const file = resolve(root, '.' + new URL(req.url, 'http://localhost').pathname)
    if (!file.startsWith(root + '/')) throw Error('Invalid path')
    res.setHeader('Content-Type', {'.html':'text/html','.js':'application/javascript','.css':'text/css','.png':'image/png','.glb':'model/gltf-binary','.mp3':'audio/mpeg','.wav':'audio/wav'}[extname(file)] || 'application/octet-stream')
    res.end(await readFile(file))
  } catch { res.statusCode = 404; res.end() }
}).listen(0, '127.0.0.1')
await new Promise(r => server.on('listening', r))
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_EXECUTABLE || await serverlessChromium.executablePath(), args: serverlessChromium.args, headless: true })
try {
  const page = await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true})
  const errors=[]
  page.on('pageerror', e => errors.push(e.stack))
  page.on('console', m => { if(m.type()==='error') errors.push(m.text()) })
  await page.goto(`http://127.0.0.1:${server.address().port}/fever/index.html`)
  await page.waitForFunction(() => window.feverSnapshot?.().models.length === 4)
  assert.equal(await page.evaluate(() => feverSnapshot().camera), 'PerspectiveCamera')
  assert.equal(await page.evaluate(() => feverSnapshot().audio.context),'locked')
  await page.screenshot({path:'/tmp/fever-title.png'})
  await page.click('#action')
  assert.equal(await page.evaluate(() => feverSnapshot().phase), 'intro')
  assert.equal(await page.evaluate(() => feverSnapshot().time), 0)
  await page.waitForFunction(() => feverSnapshot().introTime > 1.4)
  await page.screenshot({path:'/tmp/fever-intro.png'})
  await page.waitForFunction(()=>feverSnapshot().audio.loaded===4&&feverSnapshot().audio.musicPlaying)
  await page.click('#pause')
  assert.equal(await page.evaluate(()=>feverSnapshot().audio.musicPlaying),false)
  const introTime=await page.evaluate(() => feverSnapshot().introTime)
  await page.waitForTimeout(200)
  assert.equal(await page.evaluate(() => feverSnapshot().introTime),introTime)
  await page.click('#action')
  await page.waitForFunction(() => feverSnapshot().active.some(r => !r.green))
  const roach = await page.evaluate(() => feverSnapshot().active.find(r => !r.green))
  await page.mouse.move(roach.x, roach.y); await page.mouse.down()
  await page.waitForFunction(() => feverSnapshot().kills > 0)
  await page.mouse.up()
  assert.ok(await page.evaluate(() => feverSnapshot().splatters > 0))
  assert.equal(await page.evaluate(() => getComputedStyle(document.body).userSelect), 'none')
  assert.equal(await page.evaluate(() => document.querySelector('#world').dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,cancelable:true}))),false)
  await page.screenshot({path:'/tmp/fever-play.png'})
  assert.equal(await page.evaluate(() => feverSnapshot().coins), 9)
  assert.ok(await page.evaluate(()=>feverSnapshot().audio.plays>0))
  await page.click('#turret'); await page.click('#turret')
  assert.equal(await page.evaluate(() => feverSnapshot().coins), 9)
  await page.click('#turret'); await page.mouse.click(250,480)
  assert.deepEqual(await page.evaluate(() => [feverSnapshot().turrets, feverSnapshot().coins]), [1,3])
  await page.click('#pause')
  const t=await page.evaluate(() => feverSnapshot().time)
  await page.waitForTimeout(400)
  assert.equal(await page.evaluate(() => feverSnapshot().time),t)
  await page.click('#action')
  await page.click('#settings');
  await page.click('#quality'); assert.equal(await page.evaluate(() => feverSnapshot().quality), 'high')
  await page.click('#quality'); assert.equal(await page.evaluate(() => feverSnapshot().quality), 'low')
  await page.click('#music');assert.equal(await page.evaluate(()=>feverSnapshot().audio.musicPlaying),false)
  await page.click('#music');await page.waitForFunction(()=>feverSnapshot().audio.musicPlaying)
  await page.click('#sound');assert.equal(await page.evaluate(()=>feverSnapshot().audio.sfxOn),false)
  await page.click('#sound')
  await page.click('#dream');await page.waitForFunction(()=>feverSnapshot().dreamAmount===0)
  await page.click('#dream');await page.click('#settings')
  for(const viewport of [{width:320,height:568},{width:844,height:390},{width:1280,height:720}]) {
    await page.setViewportSize(viewport)
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)
    assert.ok(await page.locator('#turret').isVisible())
    const boxes=await page.evaluate(()=>['pause','settings','fullscreen','turret'].map(id=>{const r=document.getElementById(id).getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height}}))
    assert.ok(boxes.every(r=>r.w>=48&&r.h>=48),'Thumb controls are at least 48px')
    assert.ok(boxes.slice(0,3).every(r=>r.x<innerWidth*0.45&&r.y>innerHeight*0.45),'Utility controls sit in the left thumb zone')
    assert.ok(boxes[3].x>innerWidth*0.45&&boxes[3].y>innerHeight*0.45,'Turret sits in the right thumb zone')
  }
  await page.setViewportSize({width:390,height:844})
  await page.evaluate(() => window.dispatchEvent(new Event('blur')))
  assert.equal(await page.evaluate(() => feverSnapshot().paused), true)
  await page.screenshot({path:'/tmp/fever-verified.png'})
  // Restart through the public page and exercise skip and reduced-motion paths.
  await page.reload()
  await page.waitForSelector('#loading',{state:'hidden'})
  await page.click('#action');await page.click('#skip-intro')
  assert.equal(await page.evaluate(() => feverSnapshot().phase),'play')
  // Real touch input: two fast taps expose damage and finish a target.
  await page.waitForFunction(()=>feverSnapshot().active.some(r=>!r.green))
  let target=await page.evaluate(()=>feverSnapshot().active.find(r=>!r.green))
  await page.touchscreen.tap(target.x,target.y)
  assert.ok(await page.evaluate(()=>feverSnapshot().damaged>0))
  target=await page.evaluate(()=>feverSnapshot().active.find(r=>!r.green))
  await page.touchscreen.tap(target.x,target.y)
  assert.equal(await page.evaluate(()=>feverSnapshot().kills),1)
  assert.equal(await page.evaluate(()=>feverSnapshot().attackKind),'TAP')
  assert.ok(await page.evaluate(()=>feverSnapshot().attackCombo>=2))
  assert.ok(await page.evaluate(()=>feverSnapshot().slowTime>0))
  await page.screenshot({path:'/tmp/fever-combo.png'})
  await page.waitForFunction(()=>feverSnapshot().active.some(r=>!r.green))
  target=await page.evaluate(()=>feverSnapshot().active.find(r=>!r.green))
  const session=await page.context().newCDPSession(page)
  const y=Math.max(190,Math.min(680,target.y)),x=Math.max(30,Math.min(330,target.x))
  // Sweep from clear floor through the projected target with a single large move.
  await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:x-25,y:y+32}]})
  await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:target.x+12,y:target.y-12}]})
  await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]})
  assert.equal(await page.evaluate(()=>feverSnapshot().attackKind),'SWIPE')
  assert.equal(await page.evaluate(()=>feverSnapshot().kills),2)
  assert.equal(await page.evaluate(()=>feverSnapshot().held),false)
  await session.detach()
  await page.emulateMedia({reducedMotion:'reduce'});await page.reload()
  await page.waitForSelector('#loading',{state:'hidden'});await page.click('#action')
  await page.waitForFunction(() => feverSnapshot().phase==='play')
  assert.ok(await page.evaluate(() => feverSnapshot().introTime < .5))
  assert.equal(await page.evaluate(()=>feverSnapshot().dreamAmount),0)
  assert.equal(await page.evaluate(()=>feverSnapshot().audio.failures),0)
  assert.deepEqual(errors, [])
  console.log('PASS: recorded audio decode/play/mute/pause, touch tap/swipe/combo damage, dream toggle, 44px toolbar, hero + three CC0 props, WebGL shaders, cinematic completion/pause/skip/reduced motion, squash/splatter/reward, placement/cancellation, pause/blur, quality modes, touch selection guards and mobile/landscape/desktop layouts.')
} finally { await browser.close(); server.close() }
